#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 12
#define STATE_COUNT 140
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 61
#define ALIAS_COUNT 1
#define TOKEN_COUNT 36
#define EXTERNAL_TOKEN_COUNT 11
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4

enum {
  anon_sym_LBRACE_POUND = 1,
  anon_sym_RBRACE = 2,
  anon_sym_if = 3,
  anon_sym_each = 4,
  anon_sym_await = 5,
  anon_sym_LBRACE_COLON = 6,
  anon_sym_elseif = 7,
  anon_sym_elseif2 = 8,
  anon_sym_else = 9,
  anon_sym_then = 10,
  anon_sym_catch = 11,
  anon_sym_LBRACE_SLASH = 12,
  anon_sym_LT = 13,
  anon_sym_GT = 14,
  anon_sym_SLASH_GT = 15,
  anon_sym_LT_SLASH = 16,
  anon_sym_EQ = 17,
  aux_sym_attribute_name_token1 = 18,
  anon_sym_SQUOTE = 19,
  aux_sym_quoted_attribute_value_token1 = 20,
  anon_sym_DQUOTE = 21,
  aux_sym_quoted_attribute_value_token2 = 22,
  aux_sym__text_token1 = 23,
  anon_sym_LBRACE = 24,
  anon_sym_LBRACE_RBRACE = 25,
  sym__start_tag_name = 26,
  sym__script_start_tag_name = 27,
  sym__style_start_tag_name = 28,
  sym__end_tag_name = 29,
  sym_errorneous_end_tag_name = 30,
  sym__implicit_end_tag = 31,
  sym_raw_text = 32,
  sym_raw_text_expr = 33,
  sym_comment = 34,
  sym_html = 35,
  sym_document = 36,
  sym__node = 37,
  sym_element = 38,
  sym_special_block_start = 39,
  sym__special_block_start_tag = 40,
  sym_special_block_intermediate = 41,
  sym__special_block_intermediate_tag = 42,
  sym_special_block_end = 43,
  sym__special_block_end_tag = 44,
  sym_start_tag = 45,
  sym_self_closing_tag = 46,
  sym_end_tag = 47,
  sym_script_element = 48,
  sym_script_start_tag = 49,
  sym_style_element = 50,
  sym_style_start_tag = 51,
  sym_attribute = 52,
  sym_attribute_name = 53,
  sym_attribute_value = 54,
  sym_expr_attribute_value = 55,
  sym_quoted_attribute_value = 56,
  sym__text = 57,
  sym__expression = 58,
  aux_sym_document_repeat1 = 59,
  aux_sym_start_tag_repeat1 = 60,
  alias_sym_expression = 61,
};

static const char *ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACE_POUND] = "{#",
  [anon_sym_RBRACE] = "}",
  [anon_sym_if] = "if_tag",
  [anon_sym_each] = "each_tag",
  [anon_sym_await] = "await_tag",
  [anon_sym_LBRACE_COLON] = "{:",
  [anon_sym_elseif] = "elseif_tag",
  [anon_sym_elseif2] = "elseif_tag",
  [anon_sym_else] = "else_tag",
  [anon_sym_then] = "then_tag",
  [anon_sym_catch] = "catch",
  [anon_sym_LBRACE_SLASH] = "{/",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_SLASH_GT] = "/>",
  [anon_sym_LT_SLASH] = "</",
  [anon_sym_EQ] = "=",
  [aux_sym_attribute_name_token1] = "attribute_name_token1",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_quoted_attribute_value_token1] = "attribute_value",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_quoted_attribute_value_token2] = "attribute_value",
  [aux_sym__text_token1] = "text",
  [anon_sym_LBRACE] = "{",
  [anon_sym_LBRACE_RBRACE] = "{}",
  [sym__start_tag_name] = "tag_name",
  [sym__script_start_tag_name] = "tag_name",
  [sym__style_start_tag_name] = "tag_name",
  [sym__end_tag_name] = "tag_name",
  [sym_errorneous_end_tag_name] = "errorneous_end_tag_name",
  [sym__implicit_end_tag] = "_implicit_end_tag",
  [sym_raw_text] = "raw_text",
  [sym_raw_text_expr] = "raw_text_expr",
  [sym_comment] = "comment",
  [sym_html] = "html",
  [sym_document] = "document",
  [sym__node] = "_node",
  [sym_element] = "element",
  [sym_special_block_start] = "special_block_start",
  [sym__special_block_start_tag] = "_special_block_start_tag",
  [sym_special_block_intermediate] = "special_block_intermediate",
  [sym__special_block_intermediate_tag] = "_special_block_intermediate_tag",
  [sym_special_block_end] = "special_block_end",
  [sym__special_block_end_tag] = "_special_block_end_tag",
  [sym_start_tag] = "start_tag",
  [sym_self_closing_tag] = "self_closing_tag",
  [sym_end_tag] = "end_tag",
  [sym_script_element] = "script_element",
  [sym_script_start_tag] = "start_tag",
  [sym_style_element] = "style_element",
  [sym_style_start_tag] = "start_tag",
  [sym_attribute] = "attribute",
  [sym_attribute_name] = "attribute_name",
  [sym_attribute_value] = "attribute_value",
  [sym_expr_attribute_value] = "expr_attribute_value",
  [sym_quoted_attribute_value] = "quoted_attribute_value",
  [sym__text] = "_text",
  [sym__expression] = "_expression",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_start_tag_repeat1] = "start_tag_repeat1",
  [alias_sym_expression] = "expression",
};

static TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACE_POUND] = anon_sym_LBRACE_POUND,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_each] = anon_sym_each,
  [anon_sym_await] = anon_sym_await,
  [anon_sym_LBRACE_COLON] = anon_sym_LBRACE_COLON,
  [anon_sym_elseif] = anon_sym_elseif,
  [anon_sym_elseif2] = anon_sym_elseif,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_then] = anon_sym_then,
  [anon_sym_catch] = anon_sym_catch,
  [anon_sym_LBRACE_SLASH] = anon_sym_LBRACE_SLASH,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_SLASH_GT] = anon_sym_SLASH_GT,
  [anon_sym_LT_SLASH] = anon_sym_LT_SLASH,
  [anon_sym_EQ] = anon_sym_EQ,
  [aux_sym_attribute_name_token1] = aux_sym_attribute_name_token1,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_quoted_attribute_value_token1] = sym_attribute_value,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_quoted_attribute_value_token2] = sym_attribute_value,
  [aux_sym__text_token1] = aux_sym__text_token1,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_LBRACE_RBRACE] = anon_sym_LBRACE_RBRACE,
  [sym__start_tag_name] = sym__start_tag_name,
  [sym__script_start_tag_name] = sym__start_tag_name,
  [sym__style_start_tag_name] = sym__start_tag_name,
  [sym__end_tag_name] = sym__start_tag_name,
  [sym_errorneous_end_tag_name] = sym_errorneous_end_tag_name,
  [sym__implicit_end_tag] = sym__implicit_end_tag,
  [sym_raw_text] = sym_raw_text,
  [sym_raw_text_expr] = sym_raw_text_expr,
  [sym_comment] = sym_comment,
  [sym_html] = sym_html,
  [sym_document] = sym_document,
  [sym__node] = sym__node,
  [sym_element] = sym_element,
  [sym_special_block_start] = sym_special_block_start,
  [sym__special_block_start_tag] = sym__special_block_start_tag,
  [sym_special_block_intermediate] = sym_special_block_intermediate,
  [sym__special_block_intermediate_tag] = sym__special_block_intermediate_tag,
  [sym_special_block_end] = sym_special_block_end,
  [sym__special_block_end_tag] = sym__special_block_end_tag,
  [sym_start_tag] = sym_start_tag,
  [sym_self_closing_tag] = sym_self_closing_tag,
  [sym_end_tag] = sym_end_tag,
  [sym_script_element] = sym_script_element,
  [sym_script_start_tag] = sym_start_tag,
  [sym_style_element] = sym_style_element,
  [sym_style_start_tag] = sym_start_tag,
  [sym_attribute] = sym_attribute,
  [sym_attribute_name] = sym_attribute_name,
  [sym_attribute_value] = sym_attribute_value,
  [sym_expr_attribute_value] = sym_expr_attribute_value,
  [sym_quoted_attribute_value] = sym_quoted_attribute_value,
  [sym__text] = sym__text,
  [sym__expression] = sym__expression,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_start_tag_repeat1] = aux_sym_start_tag_repeat1,
  [alias_sym_expression] = alias_sym_expression,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACE_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_each] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_await] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_elseif] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_elseif2] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_then] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_catch] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_attribute_name_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_attribute_value_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_attribute_value_token2] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__text_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym__start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__script_start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__style_start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__end_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_errorneous_end_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__implicit_end_tag] = {
    .visible = false,
    .named = true,
  },
  [sym_raw_text] = {
    .visible = true,
    .named = true,
  },
  [sym_raw_text_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_html] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym__node] = {
    .visible = false,
    .named = true,
  },
  [sym_element] = {
    .visible = true,
    .named = true,
  },
  [sym_special_block_start] = {
    .visible = true,
    .named = true,
  },
  [sym__special_block_start_tag] = {
    .visible = false,
    .named = true,
  },
  [sym_special_block_intermediate] = {
    .visible = true,
    .named = true,
  },
  [sym__special_block_intermediate_tag] = {
    .visible = false,
    .named = true,
  },
  [sym_special_block_end] = {
    .visible = true,
    .named = true,
  },
  [sym__special_block_end_tag] = {
    .visible = false,
    .named = true,
  },
  [sym_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_self_closing_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_script_element] = {
    .visible = true,
    .named = true,
  },
  [sym_script_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_style_element] = {
    .visible = true,
    .named = true,
  },
  [sym_style_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_name] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [sym_expr_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [sym__text] = {
    .visible = false,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_start_tag_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_expression] = {
    .visible = true,
    .named = true,
  },
};

static TSSymbol ts_alias_sequences[3][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = alias_sym_expression,
  },
  [2] = {
    [0] = sym_attribute_name,
  },
};

static uint16_t ts_non_terminal_alias_map[] = {
  sym__expression, 3,
    sym__expression,
    alias_sym_expression,
    sym_attribute_name,
  0,
};

static inline bool aux_sym_attribute_name_token1_character_set_1(int32_t lookahead) {
  return
    lookahead == 0 ||
    lookahead == '\t' ||
    lookahead == '\n' ||
    lookahead == '\r' ||
    lookahead == ' ' ||
    lookahead == '"' ||
    lookahead == '\'' ||
    lookahead == '/' ||
    ('<' <= lookahead && lookahead <= '>') ||
    lookahead == '{' ||
    lookahead == '}';
}

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(27);
      if (lookahead == '"') ADVANCE(74);
      if (lookahead == '\'') ADVANCE(71);
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == '<') ADVANCE(47);
      if (lookahead == '=') ADVANCE(51);
      if (lookahead == '>') ADVANCE(48);
      if (lookahead == 'a') ADVANCE(69);
      if (lookahead == 'c') ADVANCE(52);
      if (lookahead == 'e') ADVANCE(53);
      if (lookahead == 'i') ADVANCE(59);
      if (lookahead == 't') ADVANCE(61);
      if (lookahead == '{') ADVANCE(79);
      if (lookahead == '}') ADVANCE(29);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (lookahead != 0) ADVANCE(70);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(74);
      if (lookahead == '\'') ADVANCE(71);
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == '=') ADVANCE(51);
      if (lookahead == '>') ADVANCE(48);
      if (lookahead == '{') ADVANCE(80);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '}') ADVANCE(70);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(74);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(75);
      if (lookahead != 0) ADVANCE(76);
      END_STATE();
    case 3:
      if (lookahead == '\'') ADVANCE(71);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(72);
      if (lookahead != 0) ADVANCE(73);
      END_STATE();
    case 4:
      if (lookahead == '>') ADVANCE(49);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(25);
      if (lookahead == 'c') ADVANCE(6);
      if (lookahead == 'e') ADVANCE(7);
      if (lookahead == 'i') ADVANCE(13);
      if (lookahead == 't') ADVANCE(16);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(5)
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(24);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(9);
      if (lookahead == 'l') ADVANCE(22);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(19);
      END_STATE();
    case 9:
      if (lookahead == 'c') ADVANCE(17);
      END_STATE();
    case 10:
      if (lookahead == 'c') ADVANCE(18);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(21);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(40);
      END_STATE();
    case 13:
      if (lookahead == 'f') ADVANCE(30);
      END_STATE();
    case 14:
      if (lookahead == 'f') ADVANCE(38);
      END_STATE();
    case 15:
      if (lookahead == 'f') ADVANCE(37);
      END_STATE();
    case 16:
      if (lookahead == 'h') ADVANCE(11);
      END_STATE();
    case 17:
      if (lookahead == 'h') ADVANCE(32);
      END_STATE();
    case 18:
      if (lookahead == 'h') ADVANCE(44);
      END_STATE();
    case 19:
      if (lookahead == 'i') ADVANCE(23);
      END_STATE();
    case 20:
      if (lookahead == 'i') ADVANCE(15);
      END_STATE();
    case 21:
      if (lookahead == 'n') ADVANCE(42);
      END_STATE();
    case 22:
      if (lookahead == 's') ADVANCE(12);
      END_STATE();
    case 23:
      if (lookahead == 't') ADVANCE(34);
      END_STATE();
    case 24:
      if (lookahead == 't') ADVANCE(10);
      END_STATE();
    case 25:
      if (lookahead == 'w') ADVANCE(8);
      END_STATE();
    case 26:
      if (eof) ADVANCE(27);
      if (lookahead == '<') ADVANCE(47);
      if (lookahead == '{') ADVANCE(79);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(77);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(78);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_LBRACE_POUND);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_if);
      if (!aux_sym_attribute_name_token1_character_set_1(lookahead)) ADVANCE(70);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_each);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_each);
      if (!aux_sym_attribute_name_token1_character_set_1(lookahead)) ADVANCE(70);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_await);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_await);
      if (!aux_sym_attribute_name_token1_character_set_1(lookahead)) ADVANCE(70);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_LBRACE_COLON);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_elseif);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_elseif2);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_elseif2);
      if (!aux_sym_attribute_name_token1_character_set_1(lookahead)) ADVANCE(70);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_else);
      if (lookahead == ' ') ADVANCE(20);
      if (lookahead == 'i') ADVANCE(14);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_else);
      if (lookahead == 'i') ADVANCE(60);
      if (!aux_sym_attribute_name_token1_character_set_1(lookahead)) ADVANCE(70);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_then);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_then);
      if (!aux_sym_attribute_name_token1_character_set_1(lookahead)) ADVANCE(70);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_catch);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_catch);
      if (!aux_sym_attribute_name_token1_character_set_1(lookahead)) ADVANCE(70);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_LBRACE_SLASH);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '/') ADVANCE(50);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_SLASH_GT);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(aux_sym_attribute_name_token1);
      if (lookahead == 'a') ADVANCE(68);
      if (!aux_sym_attribute_name_token1_character_set_1(lookahead)) ADVANCE(70);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(aux_sym_attribute_name_token1);
      if (lookahead == 'a') ADVANCE(55);
      if (lookahead == 'l') ADVANCE(66);
      if (!aux_sym_attribute_name_token1_character_set_1(lookahead)) ADVANCE(70);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(aux_sym_attribute_name_token1);
      if (lookahead == 'a') ADVANCE(64);
      if (!aux_sym_attribute_name_token1_character_set_1(lookahead)) ADVANCE(70);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(aux_sym_attribute_name_token1);
      if (lookahead == 'c') ADVANCE(62);
      if (!aux_sym_attribute_name_token1_character_set_1(lookahead)) ADVANCE(70);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym_attribute_name_token1);
      if (lookahead == 'c') ADVANCE(63);
      if (!aux_sym_attribute_name_token1_character_set_1(lookahead)) ADVANCE(70);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(aux_sym_attribute_name_token1);
      if (lookahead == 'e') ADVANCE(65);
      if (!aux_sym_attribute_name_token1_character_set_1(lookahead)) ADVANCE(70);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(aux_sym_attribute_name_token1);
      if (lookahead == 'e') ADVANCE(41);
      if (!aux_sym_attribute_name_token1_character_set_1(lookahead)) ADVANCE(70);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(aux_sym_attribute_name_token1);
      if (lookahead == 'f') ADVANCE(31);
      if (!aux_sym_attribute_name_token1_character_set_1(lookahead)) ADVANCE(70);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(aux_sym_attribute_name_token1);
      if (lookahead == 'f') ADVANCE(39);
      if (!aux_sym_attribute_name_token1_character_set_1(lookahead)) ADVANCE(70);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(aux_sym_attribute_name_token1);
      if (lookahead == 'h') ADVANCE(57);
      if (!aux_sym_attribute_name_token1_character_set_1(lookahead)) ADVANCE(70);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(aux_sym_attribute_name_token1);
      if (lookahead == 'h') ADVANCE(33);
      if (!aux_sym_attribute_name_token1_character_set_1(lookahead)) ADVANCE(70);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(aux_sym_attribute_name_token1);
      if (lookahead == 'h') ADVANCE(45);
      if (!aux_sym_attribute_name_token1_character_set_1(lookahead)) ADVANCE(70);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(aux_sym_attribute_name_token1);
      if (lookahead == 'i') ADVANCE(67);
      if (!aux_sym_attribute_name_token1_character_set_1(lookahead)) ADVANCE(70);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(aux_sym_attribute_name_token1);
      if (lookahead == 'n') ADVANCE(43);
      if (!aux_sym_attribute_name_token1_character_set_1(lookahead)) ADVANCE(70);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(aux_sym_attribute_name_token1);
      if (lookahead == 's') ADVANCE(58);
      if (!aux_sym_attribute_name_token1_character_set_1(lookahead)) ADVANCE(70);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(aux_sym_attribute_name_token1);
      if (lookahead == 't') ADVANCE(35);
      if (!aux_sym_attribute_name_token1_character_set_1(lookahead)) ADVANCE(70);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(aux_sym_attribute_name_token1);
      if (lookahead == 't') ADVANCE(56);
      if (!aux_sym_attribute_name_token1_character_set_1(lookahead)) ADVANCE(70);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(aux_sym_attribute_name_token1);
      if (lookahead == 'w') ADVANCE(54);
      if (!aux_sym_attribute_name_token1_character_set_1(lookahead)) ADVANCE(70);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(aux_sym_attribute_name_token1);
      if (!aux_sym_attribute_name_token1_character_set_1(lookahead)) ADVANCE(70);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(72);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(73);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token1);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(73);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token2);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(75);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(76);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token2);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(76);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(aux_sym__text_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(77);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>' &&
          lookahead != '{') ADVANCE(78);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(aux_sym__text_token1);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>' &&
          lookahead != '{') ADVANCE(78);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead == '#') ADVANCE(28);
      if (lookahead == '/') ADVANCE(46);
      if (lookahead == ':') ADVANCE(36);
      if (lookahead == '}') ADVANCE(81);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead == '}') ADVANCE(81);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_LBRACE_RBRACE);
      END_STATE();
    default:
      return false;
  }
}

static TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 26, .external_lex_state = 2},
  [2] = {.lex_state = 26, .external_lex_state = 3},
  [3] = {.lex_state = 26, .external_lex_state = 3},
  [4] = {.lex_state = 26, .external_lex_state = 3},
  [5] = {.lex_state = 26, .external_lex_state = 3},
  [6] = {.lex_state = 26, .external_lex_state = 3},
  [7] = {.lex_state = 26, .external_lex_state = 2},
  [8] = {.lex_state = 26, .external_lex_state = 2},
  [9] = {.lex_state = 26, .external_lex_state = 3},
  [10] = {.lex_state = 26, .external_lex_state = 3},
  [11] = {.lex_state = 26, .external_lex_state = 3},
  [12] = {.lex_state = 26, .external_lex_state = 3},
  [13] = {.lex_state = 26, .external_lex_state = 3},
  [14] = {.lex_state = 26, .external_lex_state = 3},
  [15] = {.lex_state = 26, .external_lex_state = 3},
  [16] = {.lex_state = 26, .external_lex_state = 3},
  [17] = {.lex_state = 26, .external_lex_state = 3},
  [18] = {.lex_state = 26, .external_lex_state = 3},
  [19] = {.lex_state = 26, .external_lex_state = 3},
  [20] = {.lex_state = 26, .external_lex_state = 3},
  [21] = {.lex_state = 26, .external_lex_state = 3},
  [22] = {.lex_state = 26, .external_lex_state = 3},
  [23] = {.lex_state = 26, .external_lex_state = 3},
  [24] = {.lex_state = 26, .external_lex_state = 3},
  [25] = {.lex_state = 26, .external_lex_state = 3},
  [26] = {.lex_state = 26, .external_lex_state = 3},
  [27] = {.lex_state = 26, .external_lex_state = 3},
  [28] = {.lex_state = 26, .external_lex_state = 3},
  [29] = {.lex_state = 26, .external_lex_state = 2},
  [30] = {.lex_state = 26, .external_lex_state = 2},
  [31] = {.lex_state = 26, .external_lex_state = 2},
  [32] = {.lex_state = 26, .external_lex_state = 2},
  [33] = {.lex_state = 26, .external_lex_state = 2},
  [34] = {.lex_state = 26, .external_lex_state = 2},
  [35] = {.lex_state = 26, .external_lex_state = 2},
  [36] = {.lex_state = 26, .external_lex_state = 2},
  [37] = {.lex_state = 26, .external_lex_state = 2},
  [38] = {.lex_state = 1, .external_lex_state = 4},
  [39] = {.lex_state = 26, .external_lex_state = 2},
  [40] = {.lex_state = 26, .external_lex_state = 2},
  [41] = {.lex_state = 1, .external_lex_state = 4},
  [42] = {.lex_state = 1, .external_lex_state = 4},
  [43] = {.lex_state = 1, .external_lex_state = 4},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 26, .external_lex_state = 2},
  [46] = {.lex_state = 26, .external_lex_state = 2},
  [47] = {.lex_state = 1, .external_lex_state = 4},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 26, .external_lex_state = 2},
  [50] = {.lex_state = 26, .external_lex_state = 2},
  [51] = {.lex_state = 26, .external_lex_state = 2},
  [52] = {.lex_state = 26, .external_lex_state = 2},
  [53] = {.lex_state = 26, .external_lex_state = 2},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 1},
  [56] = {.lex_state = 1},
  [57] = {.lex_state = 1},
  [58] = {.lex_state = 1},
  [59] = {.lex_state = 1, .external_lex_state = 4},
  [60] = {.lex_state = 5},
  [61] = {.lex_state = 5},
  [62] = {.lex_state = 1, .external_lex_state = 4},
  [63] = {.lex_state = 1},
  [64] = {.lex_state = 1, .external_lex_state = 4},
  [65] = {.lex_state = 1, .external_lex_state = 4},
  [66] = {.lex_state = 1, .external_lex_state = 4},
  [67] = {.lex_state = 1, .external_lex_state = 4},
  [68] = {.lex_state = 1, .external_lex_state = 4},
  [69] = {.lex_state = 1},
  [70] = {.lex_state = 1, .external_lex_state = 4},
  [71] = {.lex_state = 1, .external_lex_state = 4},
  [72] = {.lex_state = 1, .external_lex_state = 4},
  [73] = {.lex_state = 1, .external_lex_state = 4},
  [74] = {.lex_state = 5},
  [75] = {.lex_state = 5},
  [76] = {.lex_state = 1},
  [77] = {.lex_state = 1},
  [78] = {.lex_state = 1},
  [79] = {.lex_state = 1},
  [80] = {.lex_state = 1},
  [81] = {.lex_state = 1},
  [82] = {.lex_state = 5},
  [83] = {.lex_state = 5},
  [84] = {.lex_state = 1},
  [85] = {.lex_state = 1},
  [86] = {.lex_state = 1},
  [87] = {.lex_state = 0, .external_lex_state = 5},
  [88] = {.lex_state = 0, .external_lex_state = 5},
  [89] = {.lex_state = 0, .external_lex_state = 5},
  [90] = {.lex_state = 0, .external_lex_state = 5},
  [91] = {.lex_state = 0, .external_lex_state = 6},
  [92] = {.lex_state = 0, .external_lex_state = 6},
  [93] = {.lex_state = 0, .external_lex_state = 5},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0, .external_lex_state = 7},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0, .external_lex_state = 7},
  [98] = {.lex_state = 0, .external_lex_state = 8},
  [99] = {.lex_state = 0, .external_lex_state = 7},
  [100] = {.lex_state = 0, .external_lex_state = 7},
  [101] = {.lex_state = 0, .external_lex_state = 5},
  [102] = {.lex_state = 0, .external_lex_state = 5},
  [103] = {.lex_state = 2},
  [104] = {.lex_state = 3},
  [105] = {.lex_state = 2},
  [106] = {.lex_state = 3},
  [107] = {.lex_state = 0, .external_lex_state = 8},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0, .external_lex_state = 5},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0, .external_lex_state = 8},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 0},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 0, .external_lex_state = 9},
  [130] = {.lex_state = 0},
  [131] = {.lex_state = 0, .external_lex_state = 8},
  [132] = {.lex_state = 0, .external_lex_state = 8},
  [133] = {.lex_state = 0, .external_lex_state = 8},
  [134] = {.lex_state = 0, .external_lex_state = 9},
  [135] = {.lex_state = 0},
  [136] = {.lex_state = 0, .external_lex_state = 8},
  [137] = {.lex_state = 0},
  [138] = {.lex_state = 0, .external_lex_state = 8},
  [139] = {.lex_state = 0},
};

enum {
  ts_external_token__start_tag_name = 0,
  ts_external_token__script_start_tag_name = 1,
  ts_external_token__style_start_tag_name = 2,
  ts_external_token__end_tag_name = 3,
  ts_external_token_errorneous_end_tag_name = 4,
  ts_external_token_SLASH_GT = 5,
  ts_external_token__implicit_end_tag = 6,
  ts_external_token_raw_text = 7,
  ts_external_token_raw_text_expr = 8,
  ts_external_token_comment = 9,
  ts_external_token_html = 10,
};

static TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__start_tag_name] = sym__start_tag_name,
  [ts_external_token__script_start_tag_name] = sym__script_start_tag_name,
  [ts_external_token__style_start_tag_name] = sym__style_start_tag_name,
  [ts_external_token__end_tag_name] = sym__end_tag_name,
  [ts_external_token_errorneous_end_tag_name] = sym_errorneous_end_tag_name,
  [ts_external_token_SLASH_GT] = anon_sym_SLASH_GT,
  [ts_external_token__implicit_end_tag] = sym__implicit_end_tag,
  [ts_external_token_raw_text] = sym_raw_text,
  [ts_external_token_raw_text_expr] = sym_raw_text_expr,
  [ts_external_token_comment] = sym_comment,
  [ts_external_token_html] = sym_html,
};

static bool ts_external_scanner_states[10][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__start_tag_name] = true,
    [ts_external_token__script_start_tag_name] = true,
    [ts_external_token__style_start_tag_name] = true,
    [ts_external_token__end_tag_name] = true,
    [ts_external_token_errorneous_end_tag_name] = true,
    [ts_external_token_SLASH_GT] = true,
    [ts_external_token__implicit_end_tag] = true,
    [ts_external_token_raw_text] = true,
    [ts_external_token_raw_text_expr] = true,
    [ts_external_token_comment] = true,
    [ts_external_token_html] = true,
  },
  [2] = {
    [ts_external_token_comment] = true,
  },
  [3] = {
    [ts_external_token__implicit_end_tag] = true,
    [ts_external_token_comment] = true,
  },
  [4] = {
    [ts_external_token_SLASH_GT] = true,
  },
  [5] = {
    [ts_external_token_raw_text] = true,
  },
  [6] = {
    [ts_external_token__start_tag_name] = true,
    [ts_external_token__script_start_tag_name] = true,
    [ts_external_token__style_start_tag_name] = true,
  },
  [7] = {
    [ts_external_token_raw_text_expr] = true,
    [ts_external_token_html] = true,
  },
  [8] = {
    [ts_external_token_raw_text_expr] = true,
  },
  [9] = {
    [ts_external_token__end_tag_name] = true,
  },
};

static uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACE_POUND] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_each] = ACTIONS(1),
    [anon_sym_await] = ACTIONS(1),
    [anon_sym_LBRACE_COLON] = ACTIONS(1),
    [anon_sym_elseif2] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_then] = ACTIONS(1),
    [anon_sym_catch] = ACTIONS(1),
    [anon_sym_LBRACE_SLASH] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_SLASH_GT] = ACTIONS(1),
    [anon_sym_LT_SLASH] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [aux_sym_attribute_name_token1] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_LBRACE_RBRACE] = ACTIONS(1),
    [sym__start_tag_name] = ACTIONS(1),
    [sym__script_start_tag_name] = ACTIONS(1),
    [sym__style_start_tag_name] = ACTIONS(1),
    [sym__end_tag_name] = ACTIONS(1),
    [sym_errorneous_end_tag_name] = ACTIONS(1),
    [sym__implicit_end_tag] = ACTIONS(1),
    [sym_raw_text] = ACTIONS(1),
    [sym_raw_text_expr] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [sym_html] = ACTIONS(1),
  },
  [1] = {
    [sym_document] = STATE(116),
    [sym__node] = STATE(8),
    [sym_element] = STATE(8),
    [sym_special_block_start] = STATE(8),
    [sym_special_block_intermediate] = STATE(8),
    [sym_special_block_end] = STATE(8),
    [sym_start_tag] = STATE(2),
    [sym_self_closing_tag] = STATE(34),
    [sym_script_element] = STATE(8),
    [sym_script_start_tag] = STATE(90),
    [sym_style_element] = STATE(8),
    [sym_style_start_tag] = STATE(89),
    [sym__text] = STATE(8),
    [sym__expression] = STATE(35),
    [aux_sym_document_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LBRACE_POUND] = ACTIONS(5),
    [anon_sym_LBRACE_COLON] = ACTIONS(7),
    [anon_sym_LBRACE_SLASH] = ACTIONS(9),
    [anon_sym_LT] = ACTIONS(11),
    [aux_sym__text_token1] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [anon_sym_LBRACE_RBRACE] = ACTIONS(17),
    [sym_comment] = ACTIONS(13),
  },
};

static uint16_t ts_small_parse_table[] = {
  [0] = 16,
    ACTIONS(19), 1,
      anon_sym_LBRACE_POUND,
    ACTIONS(21), 1,
      anon_sym_LBRACE_COLON,
    ACTIONS(23), 1,
      anon_sym_LBRACE_SLASH,
    ACTIONS(25), 1,
      anon_sym_LT,
    ACTIONS(27), 1,
      anon_sym_LT_SLASH,
    ACTIONS(31), 1,
      anon_sym_LBRACE,
    ACTIONS(33), 1,
      anon_sym_LBRACE_RBRACE,
    ACTIONS(35), 1,
      sym__implicit_end_tag,
    STATE(4), 1,
      sym_start_tag,
    STATE(22), 1,
      sym__expression,
    STATE(23), 1,
      sym_self_closing_tag,
    STATE(39), 1,
      sym_end_tag,
    STATE(87), 1,
      sym_style_start_tag,
    STATE(88), 1,
      sym_script_start_tag,
    ACTIONS(29), 2,
      sym_comment,
      aux_sym__text_token1,
    STATE(5), 9,
      sym__node,
      sym_element,
      sym_special_block_start,
      sym_special_block_intermediate,
      sym_special_block_end,
      sym_script_element,
      sym_style_element,
      sym__text,
      aux_sym_document_repeat1,
  [58] = 16,
    ACTIONS(19), 1,
      anon_sym_LBRACE_POUND,
    ACTIONS(21), 1,
      anon_sym_LBRACE_COLON,
    ACTIONS(23), 1,
      anon_sym_LBRACE_SLASH,
    ACTIONS(25), 1,
      anon_sym_LT,
    ACTIONS(31), 1,
      anon_sym_LBRACE,
    ACTIONS(33), 1,
      anon_sym_LBRACE_RBRACE,
    ACTIONS(37), 1,
      anon_sym_LT_SLASH,
    ACTIONS(41), 1,
      sym__implicit_end_tag,
    STATE(4), 1,
      sym_start_tag,
    STATE(13), 1,
      sym_end_tag,
    STATE(22), 1,
      sym__expression,
    STATE(23), 1,
      sym_self_closing_tag,
    STATE(87), 1,
      sym_style_start_tag,
    STATE(88), 1,
      sym_script_start_tag,
    ACTIONS(39), 2,
      sym_comment,
      aux_sym__text_token1,
    STATE(6), 9,
      sym__node,
      sym_element,
      sym_special_block_start,
      sym_special_block_intermediate,
      sym_special_block_end,
      sym_script_element,
      sym_style_element,
      sym__text,
      aux_sym_document_repeat1,
  [116] = 16,
    ACTIONS(19), 1,
      anon_sym_LBRACE_POUND,
    ACTIONS(21), 1,
      anon_sym_LBRACE_COLON,
    ACTIONS(23), 1,
      anon_sym_LBRACE_SLASH,
    ACTIONS(25), 1,
      anon_sym_LT,
    ACTIONS(31), 1,
      anon_sym_LBRACE,
    ACTIONS(33), 1,
      anon_sym_LBRACE_RBRACE,
    ACTIONS(37), 1,
      anon_sym_LT_SLASH,
    ACTIONS(45), 1,
      sym__implicit_end_tag,
    STATE(4), 1,
      sym_start_tag,
    STATE(21), 1,
      sym_end_tag,
    STATE(22), 1,
      sym__expression,
    STATE(23), 1,
      sym_self_closing_tag,
    STATE(87), 1,
      sym_style_start_tag,
    STATE(88), 1,
      sym_script_start_tag,
    ACTIONS(43), 2,
      sym_comment,
      aux_sym__text_token1,
    STATE(3), 9,
      sym__node,
      sym_element,
      sym_special_block_start,
      sym_special_block_intermediate,
      sym_special_block_end,
      sym_script_element,
      sym_style_element,
      sym__text,
      aux_sym_document_repeat1,
  [174] = 16,
    ACTIONS(19), 1,
      anon_sym_LBRACE_POUND,
    ACTIONS(21), 1,
      anon_sym_LBRACE_COLON,
    ACTIONS(23), 1,
      anon_sym_LBRACE_SLASH,
    ACTIONS(25), 1,
      anon_sym_LT,
    ACTIONS(27), 1,
      anon_sym_LT_SLASH,
    ACTIONS(31), 1,
      anon_sym_LBRACE,
    ACTIONS(33), 1,
      anon_sym_LBRACE_RBRACE,
    ACTIONS(47), 1,
      sym__implicit_end_tag,
    STATE(4), 1,
      sym_start_tag,
    STATE(22), 1,
      sym__expression,
    STATE(23), 1,
      sym_self_closing_tag,
    STATE(49), 1,
      sym_end_tag,
    STATE(87), 1,
      sym_style_start_tag,
    STATE(88), 1,
      sym_script_start_tag,
    ACTIONS(39), 2,
      sym_comment,
      aux_sym__text_token1,
    STATE(6), 9,
      sym__node,
      sym_element,
      sym_special_block_start,
      sym_special_block_intermediate,
      sym_special_block_end,
      sym_script_element,
      sym_style_element,
      sym__text,
      aux_sym_document_repeat1,
  [232] = 15,
    ACTIONS(49), 1,
      anon_sym_LBRACE_POUND,
    ACTIONS(52), 1,
      anon_sym_LBRACE_COLON,
    ACTIONS(55), 1,
      anon_sym_LBRACE_SLASH,
    ACTIONS(58), 1,
      anon_sym_LT,
    ACTIONS(61), 1,
      anon_sym_LT_SLASH,
    ACTIONS(66), 1,
      anon_sym_LBRACE,
    ACTIONS(69), 1,
      anon_sym_LBRACE_RBRACE,
    ACTIONS(72), 1,
      sym__implicit_end_tag,
    STATE(4), 1,
      sym_start_tag,
    STATE(22), 1,
      sym__expression,
    STATE(23), 1,
      sym_self_closing_tag,
    STATE(87), 1,
      sym_style_start_tag,
    STATE(88), 1,
      sym_script_start_tag,
    ACTIONS(63), 2,
      sym_comment,
      aux_sym__text_token1,
    STATE(6), 9,
      sym__node,
      sym_element,
      sym_special_block_start,
      sym_special_block_intermediate,
      sym_special_block_end,
      sym_script_element,
      sym_style_element,
      sym__text,
      aux_sym_document_repeat1,
  [287] = 14,
    ACTIONS(72), 1,
      ts_builtin_sym_end,
    ACTIONS(74), 1,
      anon_sym_LBRACE_POUND,
    ACTIONS(77), 1,
      anon_sym_LBRACE_COLON,
    ACTIONS(80), 1,
      anon_sym_LBRACE_SLASH,
    ACTIONS(83), 1,
      anon_sym_LT,
    ACTIONS(89), 1,
      anon_sym_LBRACE,
    ACTIONS(92), 1,
      anon_sym_LBRACE_RBRACE,
    STATE(2), 1,
      sym_start_tag,
    STATE(34), 1,
      sym_self_closing_tag,
    STATE(35), 1,
      sym__expression,
    STATE(89), 1,
      sym_style_start_tag,
    STATE(90), 1,
      sym_script_start_tag,
    ACTIONS(86), 2,
      sym_comment,
      aux_sym__text_token1,
    STATE(7), 9,
      sym__node,
      sym_element,
      sym_special_block_start,
      sym_special_block_intermediate,
      sym_special_block_end,
      sym_script_element,
      sym_style_element,
      sym__text,
      aux_sym_document_repeat1,
  [339] = 14,
    ACTIONS(5), 1,
      anon_sym_LBRACE_POUND,
    ACTIONS(7), 1,
      anon_sym_LBRACE_COLON,
    ACTIONS(9), 1,
      anon_sym_LBRACE_SLASH,
    ACTIONS(11), 1,
      anon_sym_LT,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_LBRACE_RBRACE,
    ACTIONS(95), 1,
      ts_builtin_sym_end,
    STATE(2), 1,
      sym_start_tag,
    STATE(34), 1,
      sym_self_closing_tag,
    STATE(35), 1,
      sym__expression,
    STATE(89), 1,
      sym_style_start_tag,
    STATE(90), 1,
      sym_script_start_tag,
    ACTIONS(97), 2,
      sym_comment,
      aux_sym__text_token1,
    STATE(7), 9,
      sym__node,
      sym_element,
      sym_special_block_start,
      sym_special_block_intermediate,
      sym_special_block_end,
      sym_script_element,
      sym_style_element,
      sym__text,
      aux_sym_document_repeat1,
  [391] = 2,
    ACTIONS(101), 3,
      sym__implicit_end_tag,
      sym_comment,
      aux_sym__text_token1,
    ACTIONS(99), 7,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      anon_sym_LBRACE_RBRACE,
  [406] = 2,
    ACTIONS(105), 3,
      sym__implicit_end_tag,
      sym_comment,
      aux_sym__text_token1,
    ACTIONS(103), 7,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      anon_sym_LBRACE_RBRACE,
  [421] = 2,
    ACTIONS(109), 3,
      sym__implicit_end_tag,
      sym_comment,
      aux_sym__text_token1,
    ACTIONS(107), 7,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      anon_sym_LBRACE_RBRACE,
  [436] = 2,
    ACTIONS(113), 3,
      sym__implicit_end_tag,
      sym_comment,
      aux_sym__text_token1,
    ACTIONS(111), 7,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      anon_sym_LBRACE_RBRACE,
  [451] = 2,
    ACTIONS(117), 3,
      sym__implicit_end_tag,
      sym_comment,
      aux_sym__text_token1,
    ACTIONS(115), 7,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      anon_sym_LBRACE_RBRACE,
  [466] = 2,
    ACTIONS(121), 3,
      sym__implicit_end_tag,
      sym_comment,
      aux_sym__text_token1,
    ACTIONS(119), 7,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      anon_sym_LBRACE_RBRACE,
  [481] = 2,
    ACTIONS(125), 3,
      sym__implicit_end_tag,
      sym_comment,
      aux_sym__text_token1,
    ACTIONS(123), 7,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      anon_sym_LBRACE_RBRACE,
  [496] = 2,
    ACTIONS(129), 3,
      sym__implicit_end_tag,
      sym_comment,
      aux_sym__text_token1,
    ACTIONS(127), 7,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      anon_sym_LBRACE_RBRACE,
  [511] = 2,
    ACTIONS(133), 3,
      sym__implicit_end_tag,
      sym_comment,
      aux_sym__text_token1,
    ACTIONS(131), 7,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      anon_sym_LBRACE_RBRACE,
  [526] = 2,
    ACTIONS(137), 3,
      sym__implicit_end_tag,
      sym_comment,
      aux_sym__text_token1,
    ACTIONS(135), 7,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      anon_sym_LBRACE_RBRACE,
  [541] = 2,
    ACTIONS(141), 3,
      sym__implicit_end_tag,
      sym_comment,
      aux_sym__text_token1,
    ACTIONS(139), 7,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      anon_sym_LBRACE_RBRACE,
  [556] = 2,
    ACTIONS(145), 3,
      sym__implicit_end_tag,
      sym_comment,
      aux_sym__text_token1,
    ACTIONS(143), 7,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      anon_sym_LBRACE_RBRACE,
  [571] = 2,
    ACTIONS(149), 3,
      sym__implicit_end_tag,
      sym_comment,
      aux_sym__text_token1,
    ACTIONS(147), 7,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      anon_sym_LBRACE_RBRACE,
  [586] = 2,
    ACTIONS(153), 3,
      sym__implicit_end_tag,
      sym_comment,
      aux_sym__text_token1,
    ACTIONS(151), 7,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      anon_sym_LBRACE_RBRACE,
  [601] = 2,
    ACTIONS(157), 3,
      sym__implicit_end_tag,
      sym_comment,
      aux_sym__text_token1,
    ACTIONS(155), 7,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      anon_sym_LBRACE_RBRACE,
  [616] = 2,
    ACTIONS(161), 3,
      sym__implicit_end_tag,
      sym_comment,
      aux_sym__text_token1,
    ACTIONS(159), 7,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      anon_sym_LBRACE_RBRACE,
  [631] = 2,
    ACTIONS(165), 3,
      sym__implicit_end_tag,
      sym_comment,
      aux_sym__text_token1,
    ACTIONS(163), 7,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      anon_sym_LBRACE_RBRACE,
  [646] = 2,
    ACTIONS(169), 3,
      sym__implicit_end_tag,
      sym_comment,
      aux_sym__text_token1,
    ACTIONS(167), 7,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      anon_sym_LBRACE_RBRACE,
  [661] = 2,
    ACTIONS(173), 3,
      sym__implicit_end_tag,
      sym_comment,
      aux_sym__text_token1,
    ACTIONS(171), 7,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      anon_sym_LBRACE_RBRACE,
  [676] = 2,
    ACTIONS(177), 3,
      sym__implicit_end_tag,
      sym_comment,
      aux_sym__text_token1,
    ACTIONS(175), 7,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      anon_sym_LBRACE_RBRACE,
  [691] = 2,
    ACTIONS(129), 3,
      sym_comment,
      ts_builtin_sym_end,
      aux_sym__text_token1,
    ACTIONS(127), 6,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT,
      anon_sym_LBRACE,
      anon_sym_LBRACE_RBRACE,
  [705] = 2,
    ACTIONS(137), 3,
      sym_comment,
      ts_builtin_sym_end,
      aux_sym__text_token1,
    ACTIONS(135), 6,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT,
      anon_sym_LBRACE,
      anon_sym_LBRACE_RBRACE,
  [719] = 2,
    ACTIONS(145), 3,
      sym_comment,
      ts_builtin_sym_end,
      aux_sym__text_token1,
    ACTIONS(143), 6,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT,
      anon_sym_LBRACE,
      anon_sym_LBRACE_RBRACE,
  [733] = 2,
    ACTIONS(161), 3,
      sym_comment,
      ts_builtin_sym_end,
      aux_sym__text_token1,
    ACTIONS(159), 6,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT,
      anon_sym_LBRACE,
      anon_sym_LBRACE_RBRACE,
  [747] = 2,
    ACTIONS(141), 3,
      sym_comment,
      ts_builtin_sym_end,
      aux_sym__text_token1,
    ACTIONS(139), 6,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT,
      anon_sym_LBRACE,
      anon_sym_LBRACE_RBRACE,
  [761] = 2,
    ACTIONS(157), 3,
      sym_comment,
      ts_builtin_sym_end,
      aux_sym__text_token1,
    ACTIONS(155), 6,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT,
      anon_sym_LBRACE,
      anon_sym_LBRACE_RBRACE,
  [775] = 2,
    ACTIONS(153), 3,
      sym_comment,
      ts_builtin_sym_end,
      aux_sym__text_token1,
    ACTIONS(151), 6,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT,
      anon_sym_LBRACE,
      anon_sym_LBRACE_RBRACE,
  [789] = 2,
    ACTIONS(133), 3,
      sym_comment,
      ts_builtin_sym_end,
      aux_sym__text_token1,
    ACTIONS(131), 6,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT,
      anon_sym_LBRACE,
      anon_sym_LBRACE_RBRACE,
  [803] = 2,
    ACTIONS(125), 3,
      sym_comment,
      ts_builtin_sym_end,
      aux_sym__text_token1,
    ACTIONS(123), 6,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT,
      anon_sym_LBRACE,
      anon_sym_LBRACE_RBRACE,
  [817] = 8,
    ACTIONS(179), 1,
      anon_sym_GT,
    ACTIONS(181), 1,
      anon_sym_SLASH_GT,
    ACTIONS(183), 1,
      aux_sym_attribute_name_token1,
    ACTIONS(185), 1,
      anon_sym_LBRACE,
    ACTIONS(187), 1,
      anon_sym_LBRACE_RBRACE,
    STATE(59), 1,
      sym_attribute_name,
    STATE(68), 1,
      sym__expression,
    STATE(41), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [843] = 2,
    ACTIONS(149), 3,
      sym_comment,
      ts_builtin_sym_end,
      aux_sym__text_token1,
    ACTIONS(147), 6,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT,
      anon_sym_LBRACE,
      anon_sym_LBRACE_RBRACE,
  [857] = 2,
    ACTIONS(173), 3,
      sym_comment,
      ts_builtin_sym_end,
      aux_sym__text_token1,
    ACTIONS(171), 6,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT,
      anon_sym_LBRACE,
      anon_sym_LBRACE_RBRACE,
  [871] = 8,
    ACTIONS(183), 1,
      aux_sym_attribute_name_token1,
    ACTIONS(185), 1,
      anon_sym_LBRACE,
    ACTIONS(187), 1,
      anon_sym_LBRACE_RBRACE,
    ACTIONS(189), 1,
      anon_sym_GT,
    ACTIONS(191), 1,
      anon_sym_SLASH_GT,
    STATE(59), 1,
      sym_attribute_name,
    STATE(68), 1,
      sym__expression,
    STATE(43), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [897] = 8,
    ACTIONS(179), 1,
      anon_sym_GT,
    ACTIONS(183), 1,
      aux_sym_attribute_name_token1,
    ACTIONS(185), 1,
      anon_sym_LBRACE,
    ACTIONS(187), 1,
      anon_sym_LBRACE_RBRACE,
    ACTIONS(193), 1,
      anon_sym_SLASH_GT,
    STATE(59), 1,
      sym_attribute_name,
    STATE(68), 1,
      sym__expression,
    STATE(47), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [923] = 7,
    ACTIONS(197), 1,
      aux_sym_attribute_name_token1,
    ACTIONS(200), 1,
      anon_sym_LBRACE,
    ACTIONS(203), 1,
      anon_sym_LBRACE_RBRACE,
    STATE(59), 1,
      sym_attribute_name,
    STATE(68), 1,
      sym__expression,
    ACTIONS(195), 2,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    STATE(43), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [947] = 7,
    ACTIONS(206), 1,
      aux_sym_attribute_name_token1,
    ACTIONS(208), 1,
      anon_sym_SQUOTE,
    ACTIONS(210), 1,
      anon_sym_DQUOTE,
    ACTIONS(212), 1,
      anon_sym_LBRACE,
    ACTIONS(214), 1,
      anon_sym_LBRACE_RBRACE,
    STATE(79), 1,
      sym__expression,
    STATE(86), 3,
      sym_attribute_value,
      sym_expr_attribute_value,
      sym_quoted_attribute_value,
  [971] = 2,
    ACTIONS(169), 3,
      sym_comment,
      ts_builtin_sym_end,
      aux_sym__text_token1,
    ACTIONS(167), 6,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT,
      anon_sym_LBRACE,
      anon_sym_LBRACE_RBRACE,
  [985] = 2,
    ACTIONS(121), 3,
      sym_comment,
      ts_builtin_sym_end,
      aux_sym__text_token1,
    ACTIONS(119), 6,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT,
      anon_sym_LBRACE,
      anon_sym_LBRACE_RBRACE,
  [999] = 8,
    ACTIONS(183), 1,
      aux_sym_attribute_name_token1,
    ACTIONS(185), 1,
      anon_sym_LBRACE,
    ACTIONS(187), 1,
      anon_sym_LBRACE_RBRACE,
    ACTIONS(189), 1,
      anon_sym_GT,
    ACTIONS(216), 1,
      anon_sym_SLASH_GT,
    STATE(59), 1,
      sym_attribute_name,
    STATE(68), 1,
      sym__expression,
    STATE(43), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1025] = 7,
    ACTIONS(185), 1,
      anon_sym_LBRACE,
    ACTIONS(187), 1,
      anon_sym_LBRACE_RBRACE,
    ACTIONS(218), 1,
      aux_sym_attribute_name_token1,
    ACTIONS(220), 1,
      anon_sym_SQUOTE,
    ACTIONS(222), 1,
      anon_sym_DQUOTE,
    STATE(66), 1,
      sym__expression,
    STATE(65), 3,
      sym_attribute_value,
      sym_expr_attribute_value,
      sym_quoted_attribute_value,
  [1049] = 2,
    ACTIONS(117), 3,
      sym_comment,
      ts_builtin_sym_end,
      aux_sym__text_token1,
    ACTIONS(115), 6,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT,
      anon_sym_LBRACE,
      anon_sym_LBRACE_RBRACE,
  [1063] = 2,
    ACTIONS(113), 3,
      sym_comment,
      ts_builtin_sym_end,
      aux_sym__text_token1,
    ACTIONS(111), 6,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT,
      anon_sym_LBRACE,
      anon_sym_LBRACE_RBRACE,
  [1077] = 2,
    ACTIONS(109), 3,
      sym_comment,
      ts_builtin_sym_end,
      aux_sym__text_token1,
    ACTIONS(107), 6,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT,
      anon_sym_LBRACE,
      anon_sym_LBRACE_RBRACE,
  [1091] = 2,
    ACTIONS(105), 3,
      sym_comment,
      ts_builtin_sym_end,
      aux_sym__text_token1,
    ACTIONS(103), 6,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT,
      anon_sym_LBRACE,
      anon_sym_LBRACE_RBRACE,
  [1105] = 2,
    ACTIONS(101), 3,
      sym_comment,
      ts_builtin_sym_end,
      aux_sym__text_token1,
    ACTIONS(99), 6,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT,
      anon_sym_LBRACE,
      anon_sym_LBRACE_RBRACE,
  [1119] = 7,
    ACTIONS(212), 1,
      anon_sym_LBRACE,
    ACTIONS(214), 1,
      anon_sym_LBRACE_RBRACE,
    ACTIONS(224), 1,
      anon_sym_GT,
    ACTIONS(226), 1,
      aux_sym_attribute_name_token1,
    STATE(63), 1,
      sym_attribute_name,
    STATE(80), 1,
      sym__expression,
    STATE(56), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1142] = 7,
    ACTIONS(212), 1,
      anon_sym_LBRACE,
    ACTIONS(214), 1,
      anon_sym_LBRACE_RBRACE,
    ACTIONS(226), 1,
      aux_sym_attribute_name_token1,
    ACTIONS(228), 1,
      anon_sym_GT,
    STATE(63), 1,
      sym_attribute_name,
    STATE(80), 1,
      sym__expression,
    STATE(56), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1165] = 7,
    ACTIONS(195), 1,
      anon_sym_GT,
    ACTIONS(230), 1,
      aux_sym_attribute_name_token1,
    ACTIONS(233), 1,
      anon_sym_LBRACE,
    ACTIONS(236), 1,
      anon_sym_LBRACE_RBRACE,
    STATE(63), 1,
      sym_attribute_name,
    STATE(80), 1,
      sym__expression,
    STATE(56), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1188] = 7,
    ACTIONS(212), 1,
      anon_sym_LBRACE,
    ACTIONS(214), 1,
      anon_sym_LBRACE_RBRACE,
    ACTIONS(226), 1,
      aux_sym_attribute_name_token1,
    ACTIONS(239), 1,
      anon_sym_GT,
    STATE(63), 1,
      sym_attribute_name,
    STATE(80), 1,
      sym__expression,
    STATE(55), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1211] = 7,
    ACTIONS(212), 1,
      anon_sym_LBRACE,
    ACTIONS(214), 1,
      anon_sym_LBRACE_RBRACE,
    ACTIONS(226), 1,
      aux_sym_attribute_name_token1,
    ACTIONS(241), 1,
      anon_sym_GT,
    STATE(63), 1,
      sym_attribute_name,
    STATE(80), 1,
      sym__expression,
    STATE(54), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1234] = 3,
    ACTIONS(245), 1,
      anon_sym_EQ,
    ACTIONS(247), 1,
      anon_sym_LBRACE,
    ACTIONS(243), 4,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      aux_sym_attribute_name_token1,
      anon_sym_LBRACE_RBRACE,
  [1247] = 3,
    ACTIONS(251), 1,
      anon_sym_else,
    STATE(107), 1,
      sym__special_block_intermediate_tag,
    ACTIONS(249), 4,
      anon_sym_elseif,
      anon_sym_elseif2,
      anon_sym_then,
      anon_sym_catch,
  [1260] = 3,
    ACTIONS(255), 1,
      anon_sym_else,
    STATE(98), 1,
      sym__special_block_intermediate_tag,
    ACTIONS(253), 4,
      anon_sym_elseif,
      anon_sym_elseif2,
      anon_sym_then,
      anon_sym_catch,
  [1273] = 2,
    ACTIONS(259), 1,
      anon_sym_LBRACE,
    ACTIONS(257), 5,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      anon_sym_EQ,
      aux_sym_attribute_name_token1,
      anon_sym_LBRACE_RBRACE,
  [1284] = 3,
    ACTIONS(247), 1,
      anon_sym_LBRACE,
    ACTIONS(261), 1,
      anon_sym_EQ,
    ACTIONS(243), 3,
      anon_sym_GT,
      aux_sym_attribute_name_token1,
      anon_sym_LBRACE_RBRACE,
  [1296] = 2,
    ACTIONS(119), 1,
      anon_sym_LBRACE,
    ACTIONS(121), 4,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      aux_sym_attribute_name_token1,
      anon_sym_LBRACE_RBRACE,
  [1306] = 2,
    ACTIONS(265), 1,
      anon_sym_LBRACE,
    ACTIONS(263), 4,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      aux_sym_attribute_name_token1,
      anon_sym_LBRACE_RBRACE,
  [1316] = 2,
    ACTIONS(269), 1,
      anon_sym_LBRACE,
    ACTIONS(267), 4,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      aux_sym_attribute_name_token1,
      anon_sym_LBRACE_RBRACE,
  [1326] = 2,
    ACTIONS(273), 1,
      anon_sym_LBRACE,
    ACTIONS(271), 4,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      aux_sym_attribute_name_token1,
      anon_sym_LBRACE_RBRACE,
  [1336] = 2,
    ACTIONS(277), 1,
      anon_sym_LBRACE,
    ACTIONS(275), 4,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      aux_sym_attribute_name_token1,
      anon_sym_LBRACE_RBRACE,
  [1346] = 2,
    ACTIONS(259), 1,
      anon_sym_LBRACE,
    ACTIONS(257), 4,
      anon_sym_GT,
      anon_sym_EQ,
      aux_sym_attribute_name_token1,
      anon_sym_LBRACE_RBRACE,
  [1356] = 2,
    ACTIONS(281), 1,
      anon_sym_LBRACE,
    ACTIONS(279), 4,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      aux_sym_attribute_name_token1,
      anon_sym_LBRACE_RBRACE,
  [1366] = 2,
    ACTIONS(285), 1,
      anon_sym_LBRACE,
    ACTIONS(283), 4,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      aux_sym_attribute_name_token1,
      anon_sym_LBRACE_RBRACE,
  [1376] = 2,
    ACTIONS(159), 1,
      anon_sym_LBRACE,
    ACTIONS(161), 4,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      aux_sym_attribute_name_token1,
      anon_sym_LBRACE_RBRACE,
  [1386] = 2,
    ACTIONS(171), 1,
      anon_sym_LBRACE,
    ACTIONS(173), 4,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      aux_sym_attribute_name_token1,
      anon_sym_LBRACE_RBRACE,
  [1396] = 2,
    STATE(120), 1,
      sym__special_block_start_tag,
    ACTIONS(287), 3,
      anon_sym_if,
      anon_sym_each,
      anon_sym_await,
  [1405] = 2,
    STATE(137), 1,
      sym__special_block_end_tag,
    ACTIONS(289), 3,
      anon_sym_if,
      anon_sym_each,
      anon_sym_await,
  [1414] = 2,
    ACTIONS(159), 1,
      anon_sym_LBRACE,
    ACTIONS(161), 3,
      anon_sym_GT,
      aux_sym_attribute_name_token1,
      anon_sym_LBRACE_RBRACE,
  [1423] = 2,
    ACTIONS(281), 1,
      anon_sym_LBRACE,
    ACTIONS(279), 3,
      anon_sym_GT,
      aux_sym_attribute_name_token1,
      anon_sym_LBRACE_RBRACE,
  [1432] = 2,
    ACTIONS(171), 1,
      anon_sym_LBRACE,
    ACTIONS(173), 3,
      anon_sym_GT,
      aux_sym_attribute_name_token1,
      anon_sym_LBRACE_RBRACE,
  [1441] = 2,
    ACTIONS(269), 1,
      anon_sym_LBRACE,
    ACTIONS(267), 3,
      anon_sym_GT,
      aux_sym_attribute_name_token1,
      anon_sym_LBRACE_RBRACE,
  [1450] = 2,
    ACTIONS(277), 1,
      anon_sym_LBRACE,
    ACTIONS(275), 3,
      anon_sym_GT,
      aux_sym_attribute_name_token1,
      anon_sym_LBRACE_RBRACE,
  [1459] = 2,
    ACTIONS(273), 1,
      anon_sym_LBRACE,
    ACTIONS(271), 3,
      anon_sym_GT,
      aux_sym_attribute_name_token1,
      anon_sym_LBRACE_RBRACE,
  [1468] = 2,
    STATE(126), 1,
      sym__special_block_end_tag,
    ACTIONS(291), 3,
      anon_sym_if,
      anon_sym_each,
      anon_sym_await,
  [1477] = 2,
    STATE(132), 1,
      sym__special_block_start_tag,
    ACTIONS(293), 3,
      anon_sym_if,
      anon_sym_each,
      anon_sym_await,
  [1486] = 2,
    ACTIONS(119), 1,
      anon_sym_LBRACE,
    ACTIONS(121), 3,
      anon_sym_GT,
      aux_sym_attribute_name_token1,
      anon_sym_LBRACE_RBRACE,
  [1495] = 2,
    ACTIONS(285), 1,
      anon_sym_LBRACE,
    ACTIONS(283), 3,
      anon_sym_GT,
      aux_sym_attribute_name_token1,
      anon_sym_LBRACE_RBRACE,
  [1504] = 2,
    ACTIONS(265), 1,
      anon_sym_LBRACE,
    ACTIONS(263), 3,
      anon_sym_GT,
      aux_sym_attribute_name_token1,
      anon_sym_LBRACE_RBRACE,
  [1513] = 3,
    ACTIONS(295), 1,
      anon_sym_LT_SLASH,
    ACTIONS(297), 1,
      sym_raw_text,
    STATE(19), 1,
      sym_end_tag,
  [1523] = 3,
    ACTIONS(295), 1,
      anon_sym_LT_SLASH,
    ACTIONS(299), 1,
      sym_raw_text,
    STATE(20), 1,
      sym_end_tag,
  [1533] = 3,
    ACTIONS(301), 1,
      anon_sym_LT_SLASH,
    ACTIONS(303), 1,
      sym_raw_text,
    STATE(33), 1,
      sym_end_tag,
  [1543] = 3,
    ACTIONS(301), 1,
      anon_sym_LT_SLASH,
    ACTIONS(305), 1,
      sym_raw_text,
    STATE(31), 1,
      sym_end_tag,
  [1553] = 3,
    ACTIONS(307), 1,
      sym__start_tag_name,
    ACTIONS(309), 1,
      sym__script_start_tag_name,
    ACTIONS(311), 1,
      sym__style_start_tag_name,
  [1563] = 3,
    ACTIONS(309), 1,
      sym__script_start_tag_name,
    ACTIONS(311), 1,
      sym__style_start_tag_name,
    ACTIONS(313), 1,
      sym__start_tag_name,
  [1573] = 1,
    ACTIONS(315), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1578] = 2,
    ACTIONS(301), 1,
      anon_sym_LT_SLASH,
    STATE(50), 1,
      sym_end_tag,
  [1585] = 2,
    ACTIONS(317), 1,
      sym_raw_text_expr,
    ACTIONS(319), 1,
      sym_html,
  [1592] = 2,
    ACTIONS(301), 1,
      anon_sym_LT_SLASH,
    STATE(51), 1,
      sym_end_tag,
  [1599] = 2,
    ACTIONS(321), 1,
      sym_raw_text_expr,
    ACTIONS(323), 1,
      sym_html,
  [1606] = 2,
    ACTIONS(325), 1,
      anon_sym_RBRACE,
    ACTIONS(327), 1,
      sym_raw_text_expr,
  [1613] = 2,
    ACTIONS(329), 1,
      sym_raw_text_expr,
    ACTIONS(331), 1,
      sym_html,
  [1620] = 2,
    ACTIONS(333), 1,
      sym_raw_text_expr,
    ACTIONS(335), 1,
      sym_html,
  [1627] = 1,
    ACTIONS(337), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1632] = 1,
    ACTIONS(339), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1637] = 2,
    ACTIONS(341), 1,
      anon_sym_DQUOTE,
    ACTIONS(343), 1,
      aux_sym_quoted_attribute_value_token2,
  [1644] = 2,
    ACTIONS(341), 1,
      anon_sym_SQUOTE,
    ACTIONS(345), 1,
      aux_sym_quoted_attribute_value_token1,
  [1651] = 2,
    ACTIONS(347), 1,
      anon_sym_DQUOTE,
    ACTIONS(349), 1,
      aux_sym_quoted_attribute_value_token2,
  [1658] = 2,
    ACTIONS(347), 1,
      anon_sym_SQUOTE,
    ACTIONS(351), 1,
      aux_sym_quoted_attribute_value_token1,
  [1665] = 2,
    ACTIONS(353), 1,
      anon_sym_RBRACE,
    ACTIONS(355), 1,
      sym_raw_text_expr,
  [1672] = 2,
    ACTIONS(295), 1,
      anon_sym_LT_SLASH,
    STATE(12), 1,
      sym_end_tag,
  [1679] = 1,
    ACTIONS(357), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1684] = 2,
    ACTIONS(295), 1,
      anon_sym_LT_SLASH,
    STATE(11), 1,
      sym_end_tag,
  [1691] = 1,
    ACTIONS(359), 1,
      anon_sym_GT,
  [1695] = 1,
    ACTIONS(361), 1,
      anon_sym_RBRACE,
  [1699] = 1,
    ACTIONS(363), 1,
      anon_sym_RBRACE,
  [1703] = 1,
    ACTIONS(365), 1,
      anon_sym_RBRACE,
  [1707] = 1,
    ACTIONS(367), 1,
      anon_sym_RBRACE,
  [1711] = 1,
    ACTIONS(369), 1,
      ts_builtin_sym_end,
  [1715] = 1,
    ACTIONS(371), 1,
      anon_sym_RBRACE,
  [1719] = 1,
    ACTIONS(373), 1,
      anon_sym_GT,
  [1723] = 1,
    ACTIONS(375), 1,
      anon_sym_RBRACE,
  [1727] = 1,
    ACTIONS(377), 1,
      sym_raw_text_expr,
  [1731] = 1,
    ACTIONS(379), 1,
      anon_sym_SQUOTE,
  [1735] = 1,
    ACTIONS(381), 1,
      anon_sym_SQUOTE,
  [1739] = 1,
    ACTIONS(381), 1,
      anon_sym_DQUOTE,
  [1743] = 1,
    ACTIONS(383), 1,
      anon_sym_RBRACE,
  [1747] = 1,
    ACTIONS(385), 1,
      anon_sym_RBRACE,
  [1751] = 1,
    ACTIONS(387), 1,
      anon_sym_RBRACE,
  [1755] = 1,
    ACTIONS(389), 1,
      anon_sym_RBRACE,
  [1759] = 1,
    ACTIONS(379), 1,
      anon_sym_DQUOTE,
  [1763] = 1,
    ACTIONS(391), 1,
      sym__end_tag_name,
  [1767] = 1,
    ACTIONS(393), 1,
      anon_sym_RBRACE,
  [1771] = 1,
    ACTIONS(395), 1,
      sym_raw_text_expr,
  [1775] = 1,
    ACTIONS(397), 1,
      sym_raw_text_expr,
  [1779] = 1,
    ACTIONS(399), 1,
      sym_raw_text_expr,
  [1783] = 1,
    ACTIONS(401), 1,
      sym__end_tag_name,
  [1787] = 1,
    ACTIONS(403), 1,
      anon_sym_RBRACE,
  [1791] = 1,
    ACTIONS(405), 1,
      sym_raw_text_expr,
  [1795] = 1,
    ACTIONS(407), 1,
      anon_sym_RBRACE,
  [1799] = 1,
    ACTIONS(409), 1,
      sym_raw_text_expr,
  [1803] = 1,
    ACTIONS(411), 1,
      anon_sym_RBRACE,
};

static uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 58,
  [SMALL_STATE(4)] = 116,
  [SMALL_STATE(5)] = 174,
  [SMALL_STATE(6)] = 232,
  [SMALL_STATE(7)] = 287,
  [SMALL_STATE(8)] = 339,
  [SMALL_STATE(9)] = 391,
  [SMALL_STATE(10)] = 406,
  [SMALL_STATE(11)] = 421,
  [SMALL_STATE(12)] = 436,
  [SMALL_STATE(13)] = 451,
  [SMALL_STATE(14)] = 466,
  [SMALL_STATE(15)] = 481,
  [SMALL_STATE(16)] = 496,
  [SMALL_STATE(17)] = 511,
  [SMALL_STATE(18)] = 526,
  [SMALL_STATE(19)] = 541,
  [SMALL_STATE(20)] = 556,
  [SMALL_STATE(21)] = 571,
  [SMALL_STATE(22)] = 586,
  [SMALL_STATE(23)] = 601,
  [SMALL_STATE(24)] = 616,
  [SMALL_STATE(25)] = 631,
  [SMALL_STATE(26)] = 646,
  [SMALL_STATE(27)] = 661,
  [SMALL_STATE(28)] = 676,
  [SMALL_STATE(29)] = 691,
  [SMALL_STATE(30)] = 705,
  [SMALL_STATE(31)] = 719,
  [SMALL_STATE(32)] = 733,
  [SMALL_STATE(33)] = 747,
  [SMALL_STATE(34)] = 761,
  [SMALL_STATE(35)] = 775,
  [SMALL_STATE(36)] = 789,
  [SMALL_STATE(37)] = 803,
  [SMALL_STATE(38)] = 817,
  [SMALL_STATE(39)] = 843,
  [SMALL_STATE(40)] = 857,
  [SMALL_STATE(41)] = 871,
  [SMALL_STATE(42)] = 897,
  [SMALL_STATE(43)] = 923,
  [SMALL_STATE(44)] = 947,
  [SMALL_STATE(45)] = 971,
  [SMALL_STATE(46)] = 985,
  [SMALL_STATE(47)] = 999,
  [SMALL_STATE(48)] = 1025,
  [SMALL_STATE(49)] = 1049,
  [SMALL_STATE(50)] = 1063,
  [SMALL_STATE(51)] = 1077,
  [SMALL_STATE(52)] = 1091,
  [SMALL_STATE(53)] = 1105,
  [SMALL_STATE(54)] = 1119,
  [SMALL_STATE(55)] = 1142,
  [SMALL_STATE(56)] = 1165,
  [SMALL_STATE(57)] = 1188,
  [SMALL_STATE(58)] = 1211,
  [SMALL_STATE(59)] = 1234,
  [SMALL_STATE(60)] = 1247,
  [SMALL_STATE(61)] = 1260,
  [SMALL_STATE(62)] = 1273,
  [SMALL_STATE(63)] = 1284,
  [SMALL_STATE(64)] = 1296,
  [SMALL_STATE(65)] = 1306,
  [SMALL_STATE(66)] = 1316,
  [SMALL_STATE(67)] = 1326,
  [SMALL_STATE(68)] = 1336,
  [SMALL_STATE(69)] = 1346,
  [SMALL_STATE(70)] = 1356,
  [SMALL_STATE(71)] = 1366,
  [SMALL_STATE(72)] = 1376,
  [SMALL_STATE(73)] = 1386,
  [SMALL_STATE(74)] = 1396,
  [SMALL_STATE(75)] = 1405,
  [SMALL_STATE(76)] = 1414,
  [SMALL_STATE(77)] = 1423,
  [SMALL_STATE(78)] = 1432,
  [SMALL_STATE(79)] = 1441,
  [SMALL_STATE(80)] = 1450,
  [SMALL_STATE(81)] = 1459,
  [SMALL_STATE(82)] = 1468,
  [SMALL_STATE(83)] = 1477,
  [SMALL_STATE(84)] = 1486,
  [SMALL_STATE(85)] = 1495,
  [SMALL_STATE(86)] = 1504,
  [SMALL_STATE(87)] = 1513,
  [SMALL_STATE(88)] = 1523,
  [SMALL_STATE(89)] = 1533,
  [SMALL_STATE(90)] = 1543,
  [SMALL_STATE(91)] = 1553,
  [SMALL_STATE(92)] = 1563,
  [SMALL_STATE(93)] = 1573,
  [SMALL_STATE(94)] = 1578,
  [SMALL_STATE(95)] = 1585,
  [SMALL_STATE(96)] = 1592,
  [SMALL_STATE(97)] = 1599,
  [SMALL_STATE(98)] = 1606,
  [SMALL_STATE(99)] = 1613,
  [SMALL_STATE(100)] = 1620,
  [SMALL_STATE(101)] = 1627,
  [SMALL_STATE(102)] = 1632,
  [SMALL_STATE(103)] = 1637,
  [SMALL_STATE(104)] = 1644,
  [SMALL_STATE(105)] = 1651,
  [SMALL_STATE(106)] = 1658,
  [SMALL_STATE(107)] = 1665,
  [SMALL_STATE(108)] = 1672,
  [SMALL_STATE(109)] = 1679,
  [SMALL_STATE(110)] = 1684,
  [SMALL_STATE(111)] = 1691,
  [SMALL_STATE(112)] = 1695,
  [SMALL_STATE(113)] = 1699,
  [SMALL_STATE(114)] = 1703,
  [SMALL_STATE(115)] = 1707,
  [SMALL_STATE(116)] = 1711,
  [SMALL_STATE(117)] = 1715,
  [SMALL_STATE(118)] = 1719,
  [SMALL_STATE(119)] = 1723,
  [SMALL_STATE(120)] = 1727,
  [SMALL_STATE(121)] = 1731,
  [SMALL_STATE(122)] = 1735,
  [SMALL_STATE(123)] = 1739,
  [SMALL_STATE(124)] = 1743,
  [SMALL_STATE(125)] = 1747,
  [SMALL_STATE(126)] = 1751,
  [SMALL_STATE(127)] = 1755,
  [SMALL_STATE(128)] = 1759,
  [SMALL_STATE(129)] = 1763,
  [SMALL_STATE(130)] = 1767,
  [SMALL_STATE(131)] = 1771,
  [SMALL_STATE(132)] = 1775,
  [SMALL_STATE(133)] = 1779,
  [SMALL_STATE(134)] = 1783,
  [SMALL_STATE(135)] = 1787,
  [SMALL_STATE(136)] = 1791,
  [SMALL_STATE(137)] = 1795,
  [SMALL_STATE(138)] = 1799,
  [SMALL_STATE(139)] = 1803,
};

static TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(92),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(95),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(91),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(129),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(100),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(134),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [49] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(83),
  [52] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(60),
  [55] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(82),
  [58] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(91),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2),
  [63] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(6),
  [66] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(100),
  [69] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(24),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2),
  [74] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(74),
  [77] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(61),
  [80] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(75),
  [83] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(92),
  [86] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(7),
  [89] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(95),
  [92] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(32),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_special_block_intermediate, 4),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_special_block_intermediate, 4),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_special_block_start, 4),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_special_block_start, 4),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_element, 3),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_element, 3),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_element, 3),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_element, 3),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 3),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 3),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 3),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 3),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag, 3),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag, 3),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_special_block_end, 3),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_special_block_end, 3),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_special_block_intermediate, 3),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_special_block_intermediate, 3),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_end_tag, 3),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_tag, 3),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_element, 2),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_element, 2),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_element, 2),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_element, 2),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 2),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 2),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__text, 1, .production_id = 1),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__text, 1, .production_id = 1),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 1),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 1),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 1),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 4),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 4),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag, 4),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag, 4),
  [171] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 4),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 4),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 3),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 3),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [185] = {.entry = {.count = 1, .reusable = false}}, SHIFT(99),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2),
  [197] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2), SHIFT_REPEAT(62),
  [200] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_start_tag_repeat1, 2), SHIFT_REPEAT(99),
  [203] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2), SHIFT_REPEAT(72),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [212] = {.entry = {.count = 1, .reusable = false}}, SHIFT(97),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [230] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2), SHIFT_REPEAT(69),
  [233] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_start_tag_repeat1, 2), SHIFT_REPEAT(97),
  [236] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2), SHIFT_REPEAT(76),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [243] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 1),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [247] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute, 1),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [251] = {.entry = {.count = 1, .reusable = false}}, SHIFT(107),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [255] = {.entry = {.count = 1, .reusable = false}}, SHIFT(98),
  [257] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_name, 1),
  [259] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute_name, 1),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [263] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3),
  [265] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute, 3),
  [267] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr_attribute_value, 1),
  [269] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expr_attribute_value, 1),
  [271] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 2),
  [273] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted_attribute_value, 2),
  [275] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 1, .production_id = 2),
  [277] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute, 1, .production_id = 2),
  [279] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 3),
  [281] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted_attribute_value, 3),
  [283] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_value, 1),
  [285] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute_value, 1),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(137),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(132),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(134),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [315] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_start_tag, 4),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(135),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(131),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(138),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(130),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(136),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(133),
  [337] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_start_tag, 3),
  [339] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_start_tag, 3),
  [341] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [343] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [345] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [347] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [349] = {.entry = {.count = 1, .reusable = true}}, SHIFT(128),
  [351] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [353] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [355] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [357] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_start_tag, 4),
  [359] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [361] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [363] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [365] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [367] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [369] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [371] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [373] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [375] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [377] = {.entry = {.count = 1, .reusable = true}}, SHIFT(139),
  [379] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [381] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [383] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [385] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [387] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [389] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [391] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [393] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [395] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [397] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [399] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [401] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [403] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [405] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [407] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [409] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [411] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_svelte_external_scanner_create(void);
void tree_sitter_svelte_external_scanner_destroy(void *);
bool tree_sitter_svelte_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_svelte_external_scanner_serialize(void *, char *);
void tree_sitter_svelte_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_svelte(void) {
  static TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .parse_table = (const uint16_t *)ts_parse_table,
    .parse_actions = ts_parse_actions,
    .lex_modes = ts_lex_modes,
    .alias_sequences = (const TSSymbol *)ts_alias_sequences,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .lex_fn = ts_lex,
    .external_scanner = {
      (const bool *)ts_external_scanner_states,
      ts_external_scanner_symbol_map,
      tree_sitter_svelte_external_scanner_create,
      tree_sitter_svelte_external_scanner_destroy,
      tree_sitter_svelte_external_scanner_scan,
      tree_sitter_svelte_external_scanner_serialize,
      tree_sitter_svelte_external_scanner_deserialize,
    },
    .field_count = FIELD_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .small_parse_table = (const uint16_t *)ts_small_parse_table,
    .small_parse_table_map = (const uint32_t *)ts_small_parse_table_map,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .state_count = STATE_COUNT,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
