#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 12
#define STATE_COUNT 137
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 67
#define ALIAS_COUNT 0
#define TOKEN_COUNT 39
#define EXTERNAL_TOKEN_COUNT 12
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4

enum {
  anon_sym_LT = 1,
  anon_sym_GT = 2,
  anon_sym_SLASH_GT = 3,
  anon_sym_LT_SLASH = 4,
  anon_sym_EQ = 5,
  aux_sym_attribute_name_token1 = 6,
  anon_sym_SQUOTE = 7,
  aux_sym_quoted_attribute_value_token1 = 8,
  anon_sym_DQUOTE = 9,
  aux_sym_quoted_attribute_value_token2 = 10,
  aux_sym__text_token1 = 11,
  anon_sym_LBRACE_RBRACE = 12,
  anon_sym_LBRACE = 13,
  anon_sym_RBRACE = 14,
  anon_sym_AThtml = 15,
  anon_sym_POUNDeach = 16,
  anon_sym_as = 17,
  anon_sym_SLASHeach = 18,
  anon_sym_POUNDawait = 19,
  anon_sym_then = 20,
  anon_sym_COLONthen = 21,
  anon_sym_COLONcatch = 22,
  anon_sym_SLASHawait = 23,
  anon_sym_POUNDif = 24,
  anon_sym_COLONelse = 25,
  anon_sym_if = 26,
  anon_sym_SLASHif = 27,
  sym__start_tag_name = 28,
  sym__script_start_tag_name = 29,
  sym__style_start_tag_name = 30,
  sym__end_tag_name = 31,
  sym_errorneous_end_tag_name = 32,
  sym__implicit_end_tag = 33,
  sym_raw_text = 34,
  sym_raw_text_expr = 35,
  sym_raw_text_await = 36,
  sym_raw_text_each = 37,
  sym_comment = 38,
  sym_document = 39,
  sym__node = 40,
  sym__statement = 41,
  sym_element = 42,
  sym_start_tag = 43,
  sym_self_closing_tag = 44,
  sym_end_tag = 45,
  sym_script_element = 46,
  sym_script_start_tag = 47,
  sym_style_element = 48,
  sym_style_start_tag = 49,
  sym_attribute = 50,
  sym_attribute_name = 51,
  sym_attribute_value = 52,
  sym_expr_attribute_value = 53,
  sym_quoted_attribute_value = 54,
  sym__text = 55,
  sym__expression = 56,
  sym_expression = 57,
  sym_html_expr = 58,
  sym_if_statement = 59,
  sym_else_statement = 60,
  sym_if_start_expr = 61,
  sym_else_expr = 62,
  sym_if_end_expr = 63,
  aux_sym_document_repeat1 = 64,
  aux_sym_start_tag_repeat1 = 65,
  aux_sym_if_statement_repeat1 = 66,
};

static const char *ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_SLASH_GT] = "/>",
  [anon_sym_LT_SLASH] = "</",
  [anon_sym_EQ] = "=",
  [aux_sym_attribute_name_token1] = "attribute_name_token1",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_quoted_attribute_value_token1] = "attribute_value",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_quoted_attribute_value_token2] = "attribute_value",
  [aux_sym__text_token1] = "text",
  [anon_sym_LBRACE_RBRACE] = "expression",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_AThtml] = "@html",
  [anon_sym_POUNDeach] = "#each",
  [anon_sym_as] = "as",
  [anon_sym_SLASHeach] = "/each",
  [anon_sym_POUNDawait] = "#await",
  [anon_sym_then] = "then",
  [anon_sym_COLONthen] = ":then",
  [anon_sym_COLONcatch] = ":catch",
  [anon_sym_SLASHawait] = "/await",
  [anon_sym_POUNDif] = "#if",
  [anon_sym_COLONelse] = ":else",
  [anon_sym_if] = "if",
  [anon_sym_SLASHif] = "/if",
  [sym__start_tag_name] = "tag_name",
  [sym__script_start_tag_name] = "tag_name",
  [sym__style_start_tag_name] = "tag_name",
  [sym__end_tag_name] = "tag_name",
  [sym_errorneous_end_tag_name] = "errorneous_end_tag_name",
  [sym__implicit_end_tag] = "_implicit_end_tag",
  [sym_raw_text] = "raw_text",
  [sym_raw_text_expr] = "raw_text_expr",
  [sym_raw_text_await] = "raw_text_await",
  [sym_raw_text_each] = "raw_text_each",
  [sym_comment] = "comment",
  [sym_document] = "document",
  [sym__node] = "_node",
  [sym__statement] = "_statement",
  [sym_element] = "element",
  [sym_start_tag] = "start_tag",
  [sym_self_closing_tag] = "self_closing_tag",
  [sym_end_tag] = "end_tag",
  [sym_script_element] = "script_element",
  [sym_script_start_tag] = "start_tag",
  [sym_style_element] = "style_element",
  [sym_style_start_tag] = "start_tag",
  [sym_attribute] = "attribute",
  [sym_attribute_name] = "attribute_name",
  [sym_attribute_value] = "attribute_value",
  [sym_expr_attribute_value] = "expr_attribute_value",
  [sym_quoted_attribute_value] = "quoted_attribute_value",
  [sym__text] = "_text",
  [sym__expression] = "_expression",
  [sym_expression] = "expression",
  [sym_html_expr] = "html_expr",
  [sym_if_statement] = "if_statement",
  [sym_else_statement] = "else_statement",
  [sym_if_start_expr] = "if_start_expr",
  [sym_else_expr] = "else_expr",
  [sym_if_end_expr] = "if_end_expr",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_start_tag_repeat1] = "start_tag_repeat1",
  [aux_sym_if_statement_repeat1] = "if_statement_repeat1",
};

static TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_SLASH_GT] = anon_sym_SLASH_GT,
  [anon_sym_LT_SLASH] = anon_sym_LT_SLASH,
  [anon_sym_EQ] = anon_sym_EQ,
  [aux_sym_attribute_name_token1] = aux_sym_attribute_name_token1,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_quoted_attribute_value_token1] = sym_attribute_value,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_quoted_attribute_value_token2] = sym_attribute_value,
  [aux_sym__text_token1] = aux_sym__text_token1,
  [anon_sym_LBRACE_RBRACE] = sym_expression,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_AThtml] = anon_sym_AThtml,
  [anon_sym_POUNDeach] = anon_sym_POUNDeach,
  [anon_sym_as] = anon_sym_as,
  [anon_sym_SLASHeach] = anon_sym_SLASHeach,
  [anon_sym_POUNDawait] = anon_sym_POUNDawait,
  [anon_sym_then] = anon_sym_then,
  [anon_sym_COLONthen] = anon_sym_COLONthen,
  [anon_sym_COLONcatch] = anon_sym_COLONcatch,
  [anon_sym_SLASHawait] = anon_sym_SLASHawait,
  [anon_sym_POUNDif] = anon_sym_POUNDif,
  [anon_sym_COLONelse] = anon_sym_COLONelse,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_SLASHif] = anon_sym_SLASHif,
  [sym__start_tag_name] = sym__start_tag_name,
  [sym__script_start_tag_name] = sym__start_tag_name,
  [sym__style_start_tag_name] = sym__start_tag_name,
  [sym__end_tag_name] = sym__start_tag_name,
  [sym_errorneous_end_tag_name] = sym_errorneous_end_tag_name,
  [sym__implicit_end_tag] = sym__implicit_end_tag,
  [sym_raw_text] = sym_raw_text,
  [sym_raw_text_expr] = sym_raw_text_expr,
  [sym_raw_text_await] = sym_raw_text_await,
  [sym_raw_text_each] = sym_raw_text_each,
  [sym_comment] = sym_comment,
  [sym_document] = sym_document,
  [sym__node] = sym__node,
  [sym__statement] = sym__statement,
  [sym_element] = sym_element,
  [sym_start_tag] = sym_start_tag,
  [sym_self_closing_tag] = sym_self_closing_tag,
  [sym_end_tag] = sym_end_tag,
  [sym_script_element] = sym_script_element,
  [sym_script_start_tag] = sym_start_tag,
  [sym_style_element] = sym_style_element,
  [sym_style_start_tag] = sym_start_tag,
  [sym_attribute] = sym_attribute,
  [sym_attribute_name] = sym_attribute_name,
  [sym_attribute_value] = sym_attribute_value,
  [sym_expr_attribute_value] = sym_expr_attribute_value,
  [sym_quoted_attribute_value] = sym_quoted_attribute_value,
  [sym__text] = sym__text,
  [sym__expression] = sym__expression,
  [sym_expression] = sym_expression,
  [sym_html_expr] = sym_html_expr,
  [sym_if_statement] = sym_if_statement,
  [sym_else_statement] = sym_else_statement,
  [sym_if_start_expr] = sym_if_start_expr,
  [sym_else_expr] = sym_else_expr,
  [sym_if_end_expr] = sym_if_end_expr,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_start_tag_repeat1] = aux_sym_start_tag_repeat1,
  [aux_sym_if_statement_repeat1] = aux_sym_if_statement_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_attribute_name_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_attribute_value_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_attribute_value_token2] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__text_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE_RBRACE] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AThtml] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUNDeach] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_as] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SLASHeach] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUNDawait] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_then] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLONthen] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLONcatch] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASHawait] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUNDif] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLONelse] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASHif] = {
    .visible = true,
    .named = false,
  },
  [sym__start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__script_start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__style_start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__end_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_errorneous_end_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__implicit_end_tag] = {
    .visible = false,
    .named = true,
  },
  [sym_raw_text] = {
    .visible = true,
    .named = true,
  },
  [sym_raw_text_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_raw_text_await] = {
    .visible = true,
    .named = true,
  },
  [sym_raw_text_each] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym__node] = {
    .visible = false,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_element] = {
    .visible = true,
    .named = true,
  },
  [sym_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_self_closing_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_script_element] = {
    .visible = true,
    .named = true,
  },
  [sym_script_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_style_element] = {
    .visible = true,
    .named = true,
  },
  [sym_style_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_name] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [sym_expr_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [sym__text] = {
    .visible = false,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_html_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_if_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_else_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_if_start_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_else_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_if_end_expr] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_start_tag_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_if_statement_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static TSSymbol ts_alias_sequences[2][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = sym_attribute_name,
  },
};

static uint16_t ts_non_terminal_alias_map[] = {
  sym_expression, 2,
    sym_expression,
    sym_attribute_name,
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(44);
      if (lookahead == '"') ADVANCE(54);
      if (lookahead == '#') ADVANCE(6);
      if (lookahead == '\'') ADVANCE(51);
      if (lookahead == '/') ADVANCE(5);
      if (lookahead == ':') ADVANCE(12);
      if (lookahead == '<') ADVANCE(45);
      if (lookahead == '=') ADVANCE(49);
      if (lookahead == '>') ADVANCE(46);
      if (lookahead == '@') ADVANCE(22);
      if (lookahead == 'a') ADVANCE(35);
      if (lookahead == 'i') ADVANCE(19);
      if (lookahead == 't') ADVANCE(23);
      if (lookahead == '{') ADVANCE(61);
      if (lookahead == '}') ADVANCE(62);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(54);
      if (lookahead == '\'') ADVANCE(51);
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == '=') ADVANCE(49);
      if (lookahead == '>') ADVANCE(46);
      if (lookahead == '{') ADVANCE(60);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '}') ADVANCE(50);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(54);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(55);
      if (lookahead != 0) ADVANCE(56);
      END_STATE();
    case 3:
      if (lookahead == '\'') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(52);
      if (lookahead != 0) ADVANCE(53);
      END_STATE();
    case 4:
      if (lookahead == '>') ADVANCE(47);
      END_STATE();
    case 5:
      if (lookahead == '>') ADVANCE(47);
      if (lookahead == 'a') ADVANCE(42);
      if (lookahead == 'e') ADVANCE(10);
      if (lookahead == 'i') ADVANCE(21);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(41);
      if (lookahead == 'e') ADVANCE(7);
      if (lookahead == 'i') ADVANCE(20);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(13);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(28);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(40);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(14);
      END_STATE();
    case 11:
      if (lookahead == 'a') ADVANCE(29);
      END_STATE();
    case 12:
      if (lookahead == 'c') ADVANCE(9);
      if (lookahead == 'e') ADVANCE(31);
      if (lookahead == 't') ADVANCE(27);
      END_STATE();
    case 13:
      if (lookahead == 'c') ADVANCE(24);
      END_STATE();
    case 14:
      if (lookahead == 'c') ADVANCE(25);
      END_STATE();
    case 15:
      if (lookahead == 'c') ADVANCE(26);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(33);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(73);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(34);
      END_STATE();
    case 19:
      if (lookahead == 'f') ADVANCE(74);
      END_STATE();
    case 20:
      if (lookahead == 'f') ADVANCE(72);
      END_STATE();
    case 21:
      if (lookahead == 'f') ADVANCE(75);
      END_STATE();
    case 22:
      if (lookahead == 'h') ADVANCE(37);
      END_STATE();
    case 23:
      if (lookahead == 'h') ADVANCE(16);
      END_STATE();
    case 24:
      if (lookahead == 'h') ADVANCE(64);
      END_STATE();
    case 25:
      if (lookahead == 'h') ADVANCE(66);
      END_STATE();
    case 26:
      if (lookahead == 'h') ADVANCE(70);
      END_STATE();
    case 27:
      if (lookahead == 'h') ADVANCE(18);
      END_STATE();
    case 28:
      if (lookahead == 'i') ADVANCE(38);
      END_STATE();
    case 29:
      if (lookahead == 'i') ADVANCE(39);
      END_STATE();
    case 30:
      if (lookahead == 'l') ADVANCE(63);
      END_STATE();
    case 31:
      if (lookahead == 'l') ADVANCE(36);
      END_STATE();
    case 32:
      if (lookahead == 'm') ADVANCE(30);
      END_STATE();
    case 33:
      if (lookahead == 'n') ADVANCE(68);
      END_STATE();
    case 34:
      if (lookahead == 'n') ADVANCE(69);
      END_STATE();
    case 35:
      if (lookahead == 's') ADVANCE(65);
      END_STATE();
    case 36:
      if (lookahead == 's') ADVANCE(17);
      END_STATE();
    case 37:
      if (lookahead == 't') ADVANCE(32);
      END_STATE();
    case 38:
      if (lookahead == 't') ADVANCE(67);
      END_STATE();
    case 39:
      if (lookahead == 't') ADVANCE(71);
      END_STATE();
    case 40:
      if (lookahead == 't') ADVANCE(15);
      END_STATE();
    case 41:
      if (lookahead == 'w') ADVANCE(8);
      END_STATE();
    case 42:
      if (lookahead == 'w') ADVANCE(11);
      END_STATE();
    case 43:
      if (eof) ADVANCE(44);
      if (lookahead == '<') ADVANCE(45);
      if (lookahead == '{') ADVANCE(61);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(57);
      if (lookahead != 0 &&
          lookahead != '>' &&
          lookahead != '}') ADVANCE(58);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '/') ADVANCE(48);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_SLASH_GT);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(aux_sym_attribute_name_token1);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '/' &&
          (lookahead < '<' || '>' < lookahead) &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(50);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(52);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(53);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token1);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(53);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token2);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(55);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(56);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token2);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(56);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(aux_sym__text_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(57);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(58);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(aux_sym__text_token1);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(58);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_LBRACE_RBRACE);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead == '}') ADVANCE(59);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_AThtml);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_POUNDeach);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_as);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_SLASHeach);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_POUNDawait);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_then);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_COLONthen);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_COLONcatch);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_SLASHawait);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_POUNDif);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_COLONelse);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_SLASHif);
      END_STATE();
    default:
      return false;
  }
}

static TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 43, .external_lex_state = 2},
  [2] = {.lex_state = 43, .external_lex_state = 3},
  [3] = {.lex_state = 43, .external_lex_state = 3},
  [4] = {.lex_state = 43, .external_lex_state = 3},
  [5] = {.lex_state = 43, .external_lex_state = 3},
  [6] = {.lex_state = 43, .external_lex_state = 3},
  [7] = {.lex_state = 43, .external_lex_state = 2},
  [8] = {.lex_state = 43, .external_lex_state = 2},
  [9] = {.lex_state = 43, .external_lex_state = 2},
  [10] = {.lex_state = 43, .external_lex_state = 2},
  [11] = {.lex_state = 43, .external_lex_state = 2},
  [12] = {.lex_state = 43, .external_lex_state = 2},
  [13] = {.lex_state = 43, .external_lex_state = 2},
  [14] = {.lex_state = 43, .external_lex_state = 2},
  [15] = {.lex_state = 43, .external_lex_state = 2},
  [16] = {.lex_state = 1, .external_lex_state = 4},
  [17] = {.lex_state = 1, .external_lex_state = 4},
  [18] = {.lex_state = 1, .external_lex_state = 4},
  [19] = {.lex_state = 1, .external_lex_state = 4},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 1, .external_lex_state = 4},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 43, .external_lex_state = 3},
  [24] = {.lex_state = 43, .external_lex_state = 3},
  [25] = {.lex_state = 43, .external_lex_state = 3},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 43, .external_lex_state = 3},
  [29] = {.lex_state = 43, .external_lex_state = 3},
  [30] = {.lex_state = 43, .external_lex_state = 3},
  [31] = {.lex_state = 43, .external_lex_state = 3},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 43, .external_lex_state = 3},
  [34] = {.lex_state = 43, .external_lex_state = 3},
  [35] = {.lex_state = 43, .external_lex_state = 3},
  [36] = {.lex_state = 43, .external_lex_state = 3},
  [37] = {.lex_state = 43, .external_lex_state = 3},
  [38] = {.lex_state = 43, .external_lex_state = 3},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 43, .external_lex_state = 3},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 43, .external_lex_state = 3},
  [43] = {.lex_state = 43, .external_lex_state = 3},
  [44] = {.lex_state = 43, .external_lex_state = 3},
  [45] = {.lex_state = 43, .external_lex_state = 3},
  [46] = {.lex_state = 43, .external_lex_state = 3},
  [47] = {.lex_state = 43, .external_lex_state = 2},
  [48] = {.lex_state = 43, .external_lex_state = 2},
  [49] = {.lex_state = 43, .external_lex_state = 2},
  [50] = {.lex_state = 43, .external_lex_state = 2},
  [51] = {.lex_state = 43, .external_lex_state = 2},
  [52] = {.lex_state = 43, .external_lex_state = 2},
  [53] = {.lex_state = 43, .external_lex_state = 2},
  [54] = {.lex_state = 43, .external_lex_state = 2},
  [55] = {.lex_state = 43, .external_lex_state = 2},
  [56] = {.lex_state = 43, .external_lex_state = 2},
  [57] = {.lex_state = 43, .external_lex_state = 2},
  [58] = {.lex_state = 43, .external_lex_state = 2},
  [59] = {.lex_state = 43, .external_lex_state = 2},
  [60] = {.lex_state = 43, .external_lex_state = 2},
  [61] = {.lex_state = 43, .external_lex_state = 2},
  [62] = {.lex_state = 43, .external_lex_state = 2},
  [63] = {.lex_state = 43, .external_lex_state = 2},
  [64] = {.lex_state = 1, .external_lex_state = 4},
  [65] = {.lex_state = 43, .external_lex_state = 2},
  [66] = {.lex_state = 43, .external_lex_state = 2},
  [67] = {.lex_state = 0, .external_lex_state = 5},
  [68] = {.lex_state = 1, .external_lex_state = 4},
  [69] = {.lex_state = 0, .external_lex_state = 5},
  [70] = {.lex_state = 1, .external_lex_state = 4},
  [71] = {.lex_state = 1, .external_lex_state = 4},
  [72] = {.lex_state = 1, .external_lex_state = 4},
  [73] = {.lex_state = 1, .external_lex_state = 4},
  [74] = {.lex_state = 1, .external_lex_state = 4},
  [75] = {.lex_state = 1, .external_lex_state = 4},
  [76] = {.lex_state = 1},
  [77] = {.lex_state = 1, .external_lex_state = 4},
  [78] = {.lex_state = 1},
  [79] = {.lex_state = 1},
  [80] = {.lex_state = 1},
  [81] = {.lex_state = 0, .external_lex_state = 6},
  [82] = {.lex_state = 0, .external_lex_state = 7},
  [83] = {.lex_state = 0, .external_lex_state = 6},
  [84] = {.lex_state = 0, .external_lex_state = 6},
  [85] = {.lex_state = 0, .external_lex_state = 5},
  [86] = {.lex_state = 0, .external_lex_state = 7},
  [87] = {.lex_state = 1},
  [88] = {.lex_state = 1},
  [89] = {.lex_state = 1},
  [90] = {.lex_state = 1},
  [91] = {.lex_state = 0, .external_lex_state = 5},
  [92] = {.lex_state = 0, .external_lex_state = 6},
  [93] = {.lex_state = 1},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 3},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 2},
  [103] = {.lex_state = 0, .external_lex_state = 6},
  [104] = {.lex_state = 0, .external_lex_state = 6},
  [105] = {.lex_state = 0, .external_lex_state = 6},
  [106] = {.lex_state = 0, .external_lex_state = 6},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 3},
  [109] = {.lex_state = 0, .external_lex_state = 5},
  [110] = {.lex_state = 0, .external_lex_state = 5},
  [111] = {.lex_state = 2},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0, .external_lex_state = 5},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0, .external_lex_state = 8},
  [118] = {.lex_state = 0, .external_lex_state = 9},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0, .external_lex_state = 5},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 0},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 0},
  [131] = {.lex_state = 0},
  [132] = {.lex_state = 0},
  [133] = {.lex_state = 0},
  [134] = {.lex_state = 0, .external_lex_state = 8},
  [135] = {.lex_state = 0},
  [136] = {.lex_state = 0, .external_lex_state = 5},
};

enum {
  ts_external_token__start_tag_name = 0,
  ts_external_token__script_start_tag_name = 1,
  ts_external_token__style_start_tag_name = 2,
  ts_external_token__end_tag_name = 3,
  ts_external_token_errorneous_end_tag_name = 4,
  ts_external_token_SLASH_GT = 5,
  ts_external_token__implicit_end_tag = 6,
  ts_external_token_raw_text = 7,
  ts_external_token_raw_text_expr = 8,
  ts_external_token_raw_text_await = 9,
  ts_external_token_raw_text_each = 10,
  ts_external_token_comment = 11,
};

static TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__start_tag_name] = sym__start_tag_name,
  [ts_external_token__script_start_tag_name] = sym__script_start_tag_name,
  [ts_external_token__style_start_tag_name] = sym__style_start_tag_name,
  [ts_external_token__end_tag_name] = sym__end_tag_name,
  [ts_external_token_errorneous_end_tag_name] = sym_errorneous_end_tag_name,
  [ts_external_token_SLASH_GT] = anon_sym_SLASH_GT,
  [ts_external_token__implicit_end_tag] = sym__implicit_end_tag,
  [ts_external_token_raw_text] = sym_raw_text,
  [ts_external_token_raw_text_expr] = sym_raw_text_expr,
  [ts_external_token_raw_text_await] = sym_raw_text_await,
  [ts_external_token_raw_text_each] = sym_raw_text_each,
  [ts_external_token_comment] = sym_comment,
};

static bool ts_external_scanner_states[10][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__start_tag_name] = true,
    [ts_external_token__script_start_tag_name] = true,
    [ts_external_token__style_start_tag_name] = true,
    [ts_external_token__end_tag_name] = true,
    [ts_external_token_errorneous_end_tag_name] = true,
    [ts_external_token_SLASH_GT] = true,
    [ts_external_token__implicit_end_tag] = true,
    [ts_external_token_raw_text] = true,
    [ts_external_token_raw_text_expr] = true,
    [ts_external_token_raw_text_await] = true,
    [ts_external_token_raw_text_each] = true,
    [ts_external_token_comment] = true,
  },
  [2] = {
    [ts_external_token_comment] = true,
  },
  [3] = {
    [ts_external_token__implicit_end_tag] = true,
    [ts_external_token_comment] = true,
  },
  [4] = {
    [ts_external_token_SLASH_GT] = true,
  },
  [5] = {
    [ts_external_token_raw_text_expr] = true,
  },
  [6] = {
    [ts_external_token_raw_text] = true,
  },
  [7] = {
    [ts_external_token__start_tag_name] = true,
    [ts_external_token__script_start_tag_name] = true,
    [ts_external_token__style_start_tag_name] = true,
  },
  [8] = {
    [ts_external_token__end_tag_name] = true,
  },
  [9] = {
    [ts_external_token__start_tag_name] = true,
  },
};

static uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_SLASH_GT] = ACTIONS(1),
    [anon_sym_LT_SLASH] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_LBRACE_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_AThtml] = ACTIONS(1),
    [anon_sym_POUNDeach] = ACTIONS(1),
    [anon_sym_as] = ACTIONS(1),
    [anon_sym_SLASHeach] = ACTIONS(1),
    [anon_sym_POUNDawait] = ACTIONS(1),
    [anon_sym_then] = ACTIONS(1),
    [anon_sym_COLONthen] = ACTIONS(1),
    [anon_sym_COLONcatch] = ACTIONS(1),
    [anon_sym_SLASHawait] = ACTIONS(1),
    [anon_sym_POUNDif] = ACTIONS(1),
    [anon_sym_COLONelse] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_SLASHif] = ACTIONS(1),
    [sym__start_tag_name] = ACTIONS(1),
    [sym__script_start_tag_name] = ACTIONS(1),
    [sym__style_start_tag_name] = ACTIONS(1),
    [sym__end_tag_name] = ACTIONS(1),
    [sym_errorneous_end_tag_name] = ACTIONS(1),
    [sym__implicit_end_tag] = ACTIONS(1),
    [sym_raw_text] = ACTIONS(1),
    [sym_raw_text_expr] = ACTIONS(1),
    [sym_raw_text_await] = ACTIONS(1),
    [sym_raw_text_each] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
  },
  [1] = {
    [sym_document] = STATE(119),
    [sym__node] = STATE(7),
    [sym__statement] = STATE(7),
    [sym_element] = STATE(7),
    [sym_start_tag] = STATE(3),
    [sym_self_closing_tag] = STATE(56),
    [sym_script_element] = STATE(7),
    [sym_script_start_tag] = STATE(92),
    [sym_style_element] = STATE(7),
    [sym_style_start_tag] = STATE(81),
    [sym__text] = STATE(7),
    [sym__expression] = STATE(7),
    [sym_expression] = STATE(7),
    [sym_html_expr] = STATE(7),
    [sym_if_statement] = STATE(7),
    [sym_if_start_expr] = STATE(10),
    [aux_sym_document_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LT] = ACTIONS(5),
    [aux_sym__text_token1] = ACTIONS(7),
    [anon_sym_LBRACE_RBRACE] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(11),
    [sym_comment] = ACTIONS(7),
  },
};

static uint16_t ts_small_parse_table[] = {
  [0] = 13,
    ACTIONS(13), 1,
      anon_sym_LT,
    ACTIONS(15), 1,
      anon_sym_LT_SLASH,
    ACTIONS(19), 1,
      anon_sym_LBRACE_RBRACE,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      sym__implicit_end_tag,
    STATE(2), 1,
      sym_start_tag,
    STATE(11), 1,
      sym_if_start_expr,
    STATE(35), 1,
      sym_self_closing_tag,
    STATE(42), 1,
      sym_end_tag,
    STATE(83), 1,
      sym_style_start_tag,
    STATE(84), 1,
      sym_script_start_tag,
    ACTIONS(17), 2,
      sym_comment,
      aux_sym__text_token1,
    STATE(4), 11,
      sym__node,
      sym__statement,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym__text,
      sym__expression,
      sym_expression,
      sym_html_expr,
      sym_if_statement,
      aux_sym_document_repeat1,
  [51] = 13,
    ACTIONS(13), 1,
      anon_sym_LT,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_LT_SLASH,
    ACTIONS(29), 1,
      anon_sym_LBRACE_RBRACE,
    ACTIONS(31), 1,
      sym__implicit_end_tag,
    STATE(2), 1,
      sym_start_tag,
    STATE(11), 1,
      sym_if_start_expr,
    STATE(35), 1,
      sym_self_closing_tag,
    STATE(54), 1,
      sym_end_tag,
    STATE(83), 1,
      sym_style_start_tag,
    STATE(84), 1,
      sym_script_start_tag,
    ACTIONS(27), 2,
      sym_comment,
      aux_sym__text_token1,
    STATE(5), 11,
      sym__node,
      sym__statement,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym__text,
      sym__expression,
      sym_expression,
      sym_html_expr,
      sym_if_statement,
      aux_sym_document_repeat1,
  [102] = 13,
    ACTIONS(13), 1,
      anon_sym_LT,
    ACTIONS(15), 1,
      anon_sym_LT_SLASH,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(35), 1,
      anon_sym_LBRACE_RBRACE,
    ACTIONS(37), 1,
      sym__implicit_end_tag,
    STATE(2), 1,
      sym_start_tag,
    STATE(11), 1,
      sym_if_start_expr,
    STATE(35), 1,
      sym_self_closing_tag,
    STATE(36), 1,
      sym_end_tag,
    STATE(83), 1,
      sym_style_start_tag,
    STATE(84), 1,
      sym_script_start_tag,
    ACTIONS(33), 2,
      sym_comment,
      aux_sym__text_token1,
    STATE(6), 11,
      sym__node,
      sym__statement,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym__text,
      sym__expression,
      sym_expression,
      sym_html_expr,
      sym_if_statement,
      aux_sym_document_repeat1,
  [153] = 13,
    ACTIONS(13), 1,
      anon_sym_LT,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_LT_SLASH,
    ACTIONS(35), 1,
      anon_sym_LBRACE_RBRACE,
    ACTIONS(39), 1,
      sym__implicit_end_tag,
    STATE(2), 1,
      sym_start_tag,
    STATE(11), 1,
      sym_if_start_expr,
    STATE(35), 1,
      sym_self_closing_tag,
    STATE(51), 1,
      sym_end_tag,
    STATE(83), 1,
      sym_style_start_tag,
    STATE(84), 1,
      sym_script_start_tag,
    ACTIONS(33), 2,
      sym_comment,
      aux_sym__text_token1,
    STATE(6), 11,
      sym__node,
      sym__statement,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym__text,
      sym__expression,
      sym_expression,
      sym_html_expr,
      sym_if_statement,
      aux_sym_document_repeat1,
  [204] = 12,
    ACTIONS(41), 1,
      anon_sym_LT,
    ACTIONS(44), 1,
      anon_sym_LT_SLASH,
    ACTIONS(49), 1,
      anon_sym_LBRACE_RBRACE,
    ACTIONS(52), 1,
      anon_sym_LBRACE,
    ACTIONS(55), 1,
      sym__implicit_end_tag,
    STATE(2), 1,
      sym_start_tag,
    STATE(11), 1,
      sym_if_start_expr,
    STATE(35), 1,
      sym_self_closing_tag,
    STATE(83), 1,
      sym_style_start_tag,
    STATE(84), 1,
      sym_script_start_tag,
    ACTIONS(46), 2,
      sym_comment,
      aux_sym__text_token1,
    STATE(6), 11,
      sym__node,
      sym__statement,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym__text,
      sym__expression,
      sym_expression,
      sym_html_expr,
      sym_if_statement,
      aux_sym_document_repeat1,
  [252] = 11,
    ACTIONS(5), 1,
      anon_sym_LT,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(57), 1,
      ts_builtin_sym_end,
    ACTIONS(61), 1,
      anon_sym_LBRACE_RBRACE,
    STATE(3), 1,
      sym_start_tag,
    STATE(10), 1,
      sym_if_start_expr,
    STATE(56), 1,
      sym_self_closing_tag,
    STATE(81), 1,
      sym_style_start_tag,
    STATE(92), 1,
      sym_script_start_tag,
    ACTIONS(59), 2,
      sym_comment,
      aux_sym__text_token1,
    STATE(8), 11,
      sym__node,
      sym__statement,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym__text,
      sym__expression,
      sym_expression,
      sym_html_expr,
      sym_if_statement,
      aux_sym_document_repeat1,
  [297] = 11,
    ACTIONS(55), 1,
      ts_builtin_sym_end,
    ACTIONS(63), 1,
      anon_sym_LT,
    ACTIONS(69), 1,
      anon_sym_LBRACE_RBRACE,
    ACTIONS(72), 1,
      anon_sym_LBRACE,
    STATE(3), 1,
      sym_start_tag,
    STATE(10), 1,
      sym_if_start_expr,
    STATE(56), 1,
      sym_self_closing_tag,
    STATE(81), 1,
      sym_style_start_tag,
    STATE(92), 1,
      sym_script_start_tag,
    ACTIONS(66), 2,
      sym_comment,
      aux_sym__text_token1,
    STATE(8), 11,
      sym__node,
      sym__statement,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym__text,
      sym__expression,
      sym_expression,
      sym_html_expr,
      sym_if_statement,
      aux_sym_document_repeat1,
  [342] = 11,
    ACTIONS(75), 1,
      anon_sym_LT,
    ACTIONS(79), 1,
      anon_sym_LBRACE_RBRACE,
    ACTIONS(81), 1,
      anon_sym_LBRACE,
    STATE(3), 1,
      sym_start_tag,
    STATE(10), 1,
      sym_if_start_expr,
    STATE(15), 1,
      sym_else_expr,
    STATE(29), 1,
      sym_if_end_expr,
    STATE(56), 1,
      sym_self_closing_tag,
    STATE(94), 1,
      sym_else_statement,
    ACTIONS(77), 2,
      sym_comment,
      aux_sym__text_token1,
    STATE(13), 8,
      sym__statement,
      sym_element,
      sym__text,
      sym__expression,
      sym_expression,
      sym_html_expr,
      sym_if_statement,
      aux_sym_if_statement_repeat1,
  [384] = 11,
    ACTIONS(75), 1,
      anon_sym_LT,
    ACTIONS(85), 1,
      anon_sym_LBRACE_RBRACE,
    ACTIONS(87), 1,
      anon_sym_LBRACE,
    STATE(3), 1,
      sym_start_tag,
    STATE(10), 1,
      sym_if_start_expr,
    STATE(15), 1,
      sym_else_expr,
    STATE(56), 1,
      sym_self_closing_tag,
    STATE(60), 1,
      sym_if_end_expr,
    STATE(101), 1,
      sym_else_statement,
    ACTIONS(83), 2,
      sym_comment,
      aux_sym__text_token1,
    STATE(12), 8,
      sym__statement,
      sym_element,
      sym__text,
      sym__expression,
      sym_expression,
      sym_html_expr,
      sym_if_statement,
      aux_sym_if_statement_repeat1,
  [426] = 11,
    ACTIONS(75), 1,
      anon_sym_LT,
    ACTIONS(81), 1,
      anon_sym_LBRACE,
    ACTIONS(91), 1,
      anon_sym_LBRACE_RBRACE,
    STATE(3), 1,
      sym_start_tag,
    STATE(10), 1,
      sym_if_start_expr,
    STATE(15), 1,
      sym_else_expr,
    STATE(45), 1,
      sym_if_end_expr,
    STATE(56), 1,
      sym_self_closing_tag,
    STATE(96), 1,
      sym_else_statement,
    ACTIONS(89), 2,
      sym_comment,
      aux_sym__text_token1,
    STATE(9), 8,
      sym__statement,
      sym_element,
      sym__text,
      sym__expression,
      sym_expression,
      sym_html_expr,
      sym_if_statement,
      aux_sym_if_statement_repeat1,
  [468] = 11,
    ACTIONS(75), 1,
      anon_sym_LT,
    ACTIONS(79), 1,
      anon_sym_LBRACE_RBRACE,
    ACTIONS(87), 1,
      anon_sym_LBRACE,
    STATE(3), 1,
      sym_start_tag,
    STATE(10), 1,
      sym_if_start_expr,
    STATE(15), 1,
      sym_else_expr,
    STATE(53), 1,
      sym_if_end_expr,
    STATE(56), 1,
      sym_self_closing_tag,
    STATE(100), 1,
      sym_else_statement,
    ACTIONS(77), 2,
      sym_comment,
      aux_sym__text_token1,
    STATE(13), 8,
      sym__statement,
      sym_element,
      sym__text,
      sym__expression,
      sym_expression,
      sym_html_expr,
      sym_if_statement,
      aux_sym_if_statement_repeat1,
  [510] = 8,
    ACTIONS(93), 1,
      anon_sym_LT,
    ACTIONS(99), 1,
      anon_sym_LBRACE_RBRACE,
    ACTIONS(102), 1,
      anon_sym_LBRACE,
    STATE(3), 1,
      sym_start_tag,
    STATE(10), 1,
      sym_if_start_expr,
    STATE(56), 1,
      sym_self_closing_tag,
    ACTIONS(96), 2,
      sym_comment,
      aux_sym__text_token1,
    STATE(13), 8,
      sym__statement,
      sym_element,
      sym__text,
      sym__expression,
      sym_expression,
      sym_html_expr,
      sym_if_statement,
      aux_sym_if_statement_repeat1,
  [543] = 8,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(75), 1,
      anon_sym_LT,
    ACTIONS(79), 1,
      anon_sym_LBRACE_RBRACE,
    STATE(3), 1,
      sym_start_tag,
    STATE(10), 1,
      sym_if_start_expr,
    STATE(56), 1,
      sym_self_closing_tag,
    ACTIONS(77), 2,
      sym_comment,
      aux_sym__text_token1,
    STATE(13), 8,
      sym__statement,
      sym_element,
      sym__text,
      sym__expression,
      sym_expression,
      sym_html_expr,
      sym_if_statement,
      aux_sym_if_statement_repeat1,
  [576] = 8,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(75), 1,
      anon_sym_LT,
    ACTIONS(107), 1,
      anon_sym_LBRACE_RBRACE,
    STATE(3), 1,
      sym_start_tag,
    STATE(10), 1,
      sym_if_start_expr,
    STATE(56), 1,
      sym_self_closing_tag,
    ACTIONS(105), 2,
      sym_comment,
      aux_sym__text_token1,
    STATE(14), 8,
      sym__statement,
      sym_element,
      sym__text,
      sym__expression,
      sym_expression,
      sym_html_expr,
      sym_if_statement,
      aux_sym_if_statement_repeat1,
  [609] = 7,
    ACTIONS(109), 1,
      anon_sym_GT,
    ACTIONS(111), 1,
      anon_sym_SLASH_GT,
    ACTIONS(113), 1,
      aux_sym_attribute_name_token1,
    ACTIONS(115), 1,
      anon_sym_LBRACE,
    STATE(64), 1,
      sym_attribute_name,
    STATE(72), 1,
      sym_expression,
    STATE(17), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [632] = 6,
    ACTIONS(119), 1,
      aux_sym_attribute_name_token1,
    ACTIONS(122), 1,
      anon_sym_LBRACE,
    STATE(64), 1,
      sym_attribute_name,
    STATE(72), 1,
      sym_expression,
    ACTIONS(117), 2,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    STATE(17), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [653] = 7,
    ACTIONS(113), 1,
      aux_sym_attribute_name_token1,
    ACTIONS(115), 1,
      anon_sym_LBRACE,
    ACTIONS(125), 1,
      anon_sym_GT,
    ACTIONS(127), 1,
      anon_sym_SLASH_GT,
    STATE(64), 1,
      sym_attribute_name,
    STATE(72), 1,
      sym_expression,
    STATE(16), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [676] = 7,
    ACTIONS(113), 1,
      aux_sym_attribute_name_token1,
    ACTIONS(115), 1,
      anon_sym_LBRACE,
    ACTIONS(125), 1,
      anon_sym_GT,
    ACTIONS(129), 1,
      anon_sym_SLASH_GT,
    STATE(64), 1,
      sym_attribute_name,
    STATE(72), 1,
      sym_expression,
    STATE(21), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [699] = 6,
    ACTIONS(115), 1,
      anon_sym_LBRACE,
    ACTIONS(131), 1,
      aux_sym_attribute_name_token1,
    ACTIONS(133), 1,
      anon_sym_SQUOTE,
    ACTIONS(135), 1,
      anon_sym_DQUOTE,
    STATE(74), 1,
      sym_expression,
    STATE(73), 3,
      sym_attribute_value,
      sym_expr_attribute_value,
      sym_quoted_attribute_value,
  [720] = 7,
    ACTIONS(109), 1,
      anon_sym_GT,
    ACTIONS(113), 1,
      aux_sym_attribute_name_token1,
    ACTIONS(115), 1,
      anon_sym_LBRACE,
    ACTIONS(137), 1,
      anon_sym_SLASH_GT,
    STATE(64), 1,
      sym_attribute_name,
    STATE(72), 1,
      sym_expression,
    STATE(17), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [743] = 6,
    ACTIONS(139), 1,
      aux_sym_attribute_name_token1,
    ACTIONS(141), 1,
      anon_sym_SQUOTE,
    ACTIONS(143), 1,
      anon_sym_DQUOTE,
    ACTIONS(145), 1,
      anon_sym_LBRACE,
    STATE(90), 1,
      sym_expression,
    STATE(93), 3,
      sym_attribute_value,
      sym_expr_attribute_value,
      sym_quoted_attribute_value,
  [764] = 2,
    ACTIONS(149), 3,
      sym__implicit_end_tag,
      sym_comment,
      aux_sym__text_token1,
    ACTIONS(147), 4,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACE,
  [776] = 2,
    ACTIONS(153), 3,
      sym__implicit_end_tag,
      sym_comment,
      aux_sym__text_token1,
    ACTIONS(151), 4,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACE,
  [788] = 2,
    ACTIONS(157), 3,
      sym__implicit_end_tag,
      sym_comment,
      aux_sym__text_token1,
    ACTIONS(155), 4,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACE,
  [800] = 6,
    ACTIONS(145), 1,
      anon_sym_LBRACE,
    ACTIONS(159), 1,
      anon_sym_GT,
    ACTIONS(161), 1,
      aux_sym_attribute_name_token1,
    STATE(76), 1,
      sym_attribute_name,
    STATE(79), 1,
      sym_expression,
    STATE(39), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [820] = 6,
    ACTIONS(117), 1,
      anon_sym_GT,
    ACTIONS(163), 1,
      aux_sym_attribute_name_token1,
    ACTIONS(166), 1,
      anon_sym_LBRACE,
    STATE(76), 1,
      sym_attribute_name,
    STATE(79), 1,
      sym_expression,
    STATE(27), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [840] = 2,
    ACTIONS(171), 3,
      sym__implicit_end_tag,
      sym_comment,
      aux_sym__text_token1,
    ACTIONS(169), 4,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACE,
  [852] = 2,
    ACTIONS(175), 3,
      sym__implicit_end_tag,
      sym_comment,
      aux_sym__text_token1,
    ACTIONS(173), 4,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACE,
  [864] = 2,
    ACTIONS(179), 3,
      sym__implicit_end_tag,
      sym_comment,
      aux_sym__text_token1,
    ACTIONS(177), 4,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACE,
  [876] = 2,
    ACTIONS(183), 3,
      sym__implicit_end_tag,
      sym_comment,
      aux_sym__text_token1,
    ACTIONS(181), 4,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACE,
  [888] = 6,
    ACTIONS(145), 1,
      anon_sym_LBRACE,
    ACTIONS(161), 1,
      aux_sym_attribute_name_token1,
    ACTIONS(185), 1,
      anon_sym_GT,
    STATE(76), 1,
      sym_attribute_name,
    STATE(79), 1,
      sym_expression,
    STATE(41), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [908] = 2,
    ACTIONS(189), 3,
      sym__implicit_end_tag,
      sym_comment,
      aux_sym__text_token1,
    ACTIONS(187), 4,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACE,
  [920] = 2,
    ACTIONS(193), 3,
      sym__implicit_end_tag,
      sym_comment,
      aux_sym__text_token1,
    ACTIONS(191), 4,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACE,
  [932] = 2,
    ACTIONS(197), 3,
      sym__implicit_end_tag,
      sym_comment,
      aux_sym__text_token1,
    ACTIONS(195), 4,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACE,
  [944] = 2,
    ACTIONS(201), 3,
      sym__implicit_end_tag,
      sym_comment,
      aux_sym__text_token1,
    ACTIONS(199), 4,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACE,
  [956] = 2,
    ACTIONS(205), 3,
      sym__implicit_end_tag,
      sym_comment,
      aux_sym__text_token1,
    ACTIONS(203), 4,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACE,
  [968] = 2,
    ACTIONS(209), 3,
      sym__implicit_end_tag,
      sym_comment,
      aux_sym__text_token1,
    ACTIONS(207), 4,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACE,
  [980] = 6,
    ACTIONS(145), 1,
      anon_sym_LBRACE,
    ACTIONS(161), 1,
      aux_sym_attribute_name_token1,
    ACTIONS(211), 1,
      anon_sym_GT,
    STATE(76), 1,
      sym_attribute_name,
    STATE(79), 1,
      sym_expression,
    STATE(27), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1000] = 2,
    ACTIONS(215), 3,
      sym__implicit_end_tag,
      sym_comment,
      aux_sym__text_token1,
    ACTIONS(213), 4,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACE,
  [1012] = 6,
    ACTIONS(145), 1,
      anon_sym_LBRACE,
    ACTIONS(161), 1,
      aux_sym_attribute_name_token1,
    ACTIONS(217), 1,
      anon_sym_GT,
    STATE(76), 1,
      sym_attribute_name,
    STATE(79), 1,
      sym_expression,
    STATE(27), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1032] = 2,
    ACTIONS(221), 3,
      sym__implicit_end_tag,
      sym_comment,
      aux_sym__text_token1,
    ACTIONS(219), 4,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACE,
  [1044] = 2,
    ACTIONS(225), 3,
      sym__implicit_end_tag,
      sym_comment,
      aux_sym__text_token1,
    ACTIONS(223), 4,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACE,
  [1056] = 2,
    ACTIONS(229), 3,
      sym__implicit_end_tag,
      sym_comment,
      aux_sym__text_token1,
    ACTIONS(227), 4,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACE,
  [1068] = 2,
    ACTIONS(233), 3,
      sym__implicit_end_tag,
      sym_comment,
      aux_sym__text_token1,
    ACTIONS(231), 4,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACE,
  [1080] = 2,
    ACTIONS(237), 3,
      sym__implicit_end_tag,
      sym_comment,
      aux_sym__text_token1,
    ACTIONS(235), 4,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACE,
  [1092] = 2,
    ACTIONS(207), 3,
      anon_sym_LT,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACE,
    ACTIONS(209), 3,
      sym_comment,
      ts_builtin_sym_end,
      aux_sym__text_token1,
  [1103] = 2,
    ACTIONS(151), 3,
      anon_sym_LT,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACE,
    ACTIONS(153), 3,
      sym_comment,
      ts_builtin_sym_end,
      aux_sym__text_token1,
  [1114] = 2,
    ACTIONS(147), 3,
      anon_sym_LT,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACE,
    ACTIONS(149), 3,
      sym_comment,
      ts_builtin_sym_end,
      aux_sym__text_token1,
  [1125] = 2,
    ACTIONS(191), 3,
      anon_sym_LT,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACE,
    ACTIONS(193), 3,
      sym_comment,
      ts_builtin_sym_end,
      aux_sym__text_token1,
  [1136] = 2,
    ACTIONS(199), 3,
      anon_sym_LT,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACE,
    ACTIONS(201), 3,
      sym_comment,
      ts_builtin_sym_end,
      aux_sym__text_token1,
  [1147] = 2,
    ACTIONS(235), 3,
      anon_sym_LT,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACE,
    ACTIONS(237), 3,
      sym_comment,
      ts_builtin_sym_end,
      aux_sym__text_token1,
  [1158] = 2,
    ACTIONS(173), 3,
      anon_sym_LT,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACE,
    ACTIONS(175), 3,
      sym_comment,
      ts_builtin_sym_end,
      aux_sym__text_token1,
  [1169] = 2,
    ACTIONS(219), 3,
      anon_sym_LT,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACE,
    ACTIONS(221), 3,
      sym_comment,
      ts_builtin_sym_end,
      aux_sym__text_token1,
  [1180] = 2,
    ACTIONS(213), 3,
      anon_sym_LT,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACE,
    ACTIONS(215), 3,
      sym_comment,
      ts_builtin_sym_end,
      aux_sym__text_token1,
  [1191] = 2,
    ACTIONS(195), 3,
      anon_sym_LT,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACE,
    ACTIONS(197), 3,
      sym_comment,
      ts_builtin_sym_end,
      aux_sym__text_token1,
  [1202] = 2,
    ACTIONS(203), 3,
      anon_sym_LT,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACE,
    ACTIONS(205), 3,
      sym_comment,
      ts_builtin_sym_end,
      aux_sym__text_token1,
  [1213] = 2,
    ACTIONS(223), 3,
      anon_sym_LT,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACE,
    ACTIONS(225), 3,
      sym_comment,
      ts_builtin_sym_end,
      aux_sym__text_token1,
  [1224] = 2,
    ACTIONS(169), 3,
      anon_sym_LT,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACE,
    ACTIONS(171), 3,
      sym_comment,
      ts_builtin_sym_end,
      aux_sym__text_token1,
  [1235] = 2,
    ACTIONS(231), 3,
      anon_sym_LT,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACE,
    ACTIONS(233), 3,
      sym_comment,
      ts_builtin_sym_end,
      aux_sym__text_token1,
  [1246] = 2,
    ACTIONS(187), 3,
      anon_sym_LT,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACE,
    ACTIONS(189), 3,
      sym_comment,
      ts_builtin_sym_end,
      aux_sym__text_token1,
  [1257] = 2,
    ACTIONS(227), 3,
      anon_sym_LT,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACE,
    ACTIONS(229), 3,
      sym_comment,
      ts_builtin_sym_end,
      aux_sym__text_token1,
  [1268] = 2,
    ACTIONS(155), 3,
      anon_sym_LT,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACE,
    ACTIONS(157), 3,
      sym_comment,
      ts_builtin_sym_end,
      aux_sym__text_token1,
  [1279] = 2,
    ACTIONS(241), 1,
      anon_sym_EQ,
    ACTIONS(239), 4,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      aux_sym_attribute_name_token1,
      anon_sym_LBRACE,
  [1289] = 2,
    ACTIONS(245), 2,
      sym_comment,
      aux_sym__text_token1,
    ACTIONS(243), 3,
      anon_sym_LT,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACE,
  [1299] = 2,
    ACTIONS(249), 2,
      sym_comment,
      aux_sym__text_token1,
    ACTIONS(247), 3,
      anon_sym_LT,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACE,
  [1309] = 5,
    ACTIONS(251), 1,
      anon_sym_AThtml,
    ACTIONS(253), 1,
      anon_sym_POUNDif,
    ACTIONS(255), 1,
      anon_sym_COLONelse,
    ACTIONS(257), 1,
      anon_sym_SLASHif,
    ACTIONS(259), 1,
      sym_raw_text_expr,
  [1325] = 1,
    ACTIONS(261), 5,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      anon_sym_EQ,
      aux_sym_attribute_name_token1,
      anon_sym_LBRACE,
  [1333] = 5,
    ACTIONS(251), 1,
      anon_sym_AThtml,
    ACTIONS(253), 1,
      anon_sym_POUNDif,
    ACTIONS(255), 1,
      anon_sym_COLONelse,
    ACTIONS(259), 1,
      sym_raw_text_expr,
    ACTIONS(263), 1,
      anon_sym_SLASHif,
  [1349] = 1,
    ACTIONS(215), 4,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      aux_sym_attribute_name_token1,
      anon_sym_LBRACE,
  [1356] = 1,
    ACTIONS(265), 4,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      aux_sym_attribute_name_token1,
      anon_sym_LBRACE,
  [1363] = 1,
    ACTIONS(267), 4,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      aux_sym_attribute_name_token1,
      anon_sym_LBRACE,
  [1370] = 1,
    ACTIONS(269), 4,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      aux_sym_attribute_name_token1,
      anon_sym_LBRACE,
  [1377] = 1,
    ACTIONS(271), 4,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      aux_sym_attribute_name_token1,
      anon_sym_LBRACE,
  [1384] = 1,
    ACTIONS(273), 4,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      aux_sym_attribute_name_token1,
      anon_sym_LBRACE,
  [1391] = 2,
    ACTIONS(275), 1,
      anon_sym_EQ,
    ACTIONS(239), 3,
      anon_sym_GT,
      aux_sym_attribute_name_token1,
      anon_sym_LBRACE,
  [1400] = 1,
    ACTIONS(277), 4,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      aux_sym_attribute_name_token1,
      anon_sym_LBRACE,
  [1407] = 1,
    ACTIONS(261), 4,
      anon_sym_GT,
      anon_sym_EQ,
      aux_sym_attribute_name_token1,
      anon_sym_LBRACE,
  [1414] = 1,
    ACTIONS(267), 3,
      anon_sym_GT,
      aux_sym_attribute_name_token1,
      anon_sym_LBRACE,
  [1420] = 1,
    ACTIONS(265), 3,
      anon_sym_GT,
      aux_sym_attribute_name_token1,
      anon_sym_LBRACE,
  [1426] = 3,
    ACTIONS(279), 1,
      anon_sym_LT_SLASH,
    ACTIONS(281), 1,
      sym_raw_text,
    STATE(52), 1,
      sym_end_tag,
  [1436] = 3,
    ACTIONS(283), 1,
      sym__start_tag_name,
    ACTIONS(285), 1,
      sym__script_start_tag_name,
    ACTIONS(287), 1,
      sym__style_start_tag_name,
  [1446] = 3,
    ACTIONS(289), 1,
      anon_sym_LT_SLASH,
    ACTIONS(291), 1,
      sym_raw_text,
    STATE(46), 1,
      sym_end_tag,
  [1456] = 3,
    ACTIONS(289), 1,
      anon_sym_LT_SLASH,
    ACTIONS(293), 1,
      sym_raw_text,
    STATE(34), 1,
      sym_end_tag,
  [1466] = 3,
    ACTIONS(251), 1,
      anon_sym_AThtml,
    ACTIONS(253), 1,
      anon_sym_POUNDif,
    ACTIONS(259), 1,
      sym_raw_text_expr,
  [1476] = 3,
    ACTIONS(285), 1,
      sym__script_start_tag_name,
    ACTIONS(287), 1,
      sym__style_start_tag_name,
    ACTIONS(295), 1,
      sym__start_tag_name,
  [1486] = 1,
    ACTIONS(215), 3,
      anon_sym_GT,
      aux_sym_attribute_name_token1,
      anon_sym_LBRACE,
  [1492] = 1,
    ACTIONS(277), 3,
      anon_sym_GT,
      aux_sym_attribute_name_token1,
      anon_sym_LBRACE,
  [1498] = 1,
    ACTIONS(273), 3,
      anon_sym_GT,
      aux_sym_attribute_name_token1,
      anon_sym_LBRACE,
  [1504] = 1,
    ACTIONS(271), 3,
      anon_sym_GT,
      aux_sym_attribute_name_token1,
      anon_sym_LBRACE,
  [1510] = 3,
    ACTIONS(253), 1,
      anon_sym_POUNDif,
    ACTIONS(297), 1,
      anon_sym_AThtml,
    ACTIONS(299), 1,
      sym_raw_text_expr,
  [1520] = 3,
    ACTIONS(279), 1,
      anon_sym_LT_SLASH,
    ACTIONS(301), 1,
      sym_raw_text,
    STATE(50), 1,
      sym_end_tag,
  [1530] = 1,
    ACTIONS(269), 3,
      anon_sym_GT,
      aux_sym_attribute_name_token1,
      anon_sym_LBRACE,
  [1536] = 2,
    ACTIONS(303), 1,
      anon_sym_LBRACE,
    STATE(33), 1,
      sym_if_end_expr,
  [1543] = 2,
    ACTIONS(305), 1,
      anon_sym_SQUOTE,
    ACTIONS(307), 1,
      aux_sym_quoted_attribute_value_token1,
  [1550] = 2,
    ACTIONS(303), 1,
      anon_sym_LBRACE,
    STATE(29), 1,
      sym_if_end_expr,
  [1557] = 2,
    ACTIONS(279), 1,
      anon_sym_LT_SLASH,
    STATE(49), 1,
      sym_end_tag,
  [1564] = 2,
    ACTIONS(279), 1,
      anon_sym_LT_SLASH,
    STATE(48), 1,
      sym_end_tag,
  [1571] = 2,
    ACTIONS(289), 1,
      anon_sym_LT_SLASH,
    STATE(23), 1,
      sym_end_tag,
  [1578] = 2,
    ACTIONS(309), 1,
      anon_sym_LBRACE,
    STATE(61), 1,
      sym_if_end_expr,
  [1585] = 2,
    ACTIONS(309), 1,
      anon_sym_LBRACE,
    STATE(53), 1,
      sym_if_end_expr,
  [1592] = 2,
    ACTIONS(305), 1,
      anon_sym_DQUOTE,
    ACTIONS(311), 1,
      aux_sym_quoted_attribute_value_token2,
  [1599] = 1,
    ACTIONS(313), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1604] = 1,
    ACTIONS(315), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1609] = 1,
    ACTIONS(317), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1614] = 1,
    ACTIONS(319), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1619] = 2,
    ACTIONS(289), 1,
      anon_sym_LT_SLASH,
    STATE(24), 1,
      sym_end_tag,
  [1626] = 2,
    ACTIONS(321), 1,
      anon_sym_SQUOTE,
    ACTIONS(323), 1,
      aux_sym_quoted_attribute_value_token1,
  [1633] = 2,
    ACTIONS(325), 1,
      anon_sym_RBRACE,
    ACTIONS(327), 1,
      sym_raw_text_expr,
  [1640] = 2,
    ACTIONS(329), 1,
      anon_sym_RBRACE,
    ACTIONS(331), 1,
      sym_raw_text_expr,
  [1647] = 2,
    ACTIONS(321), 1,
      anon_sym_DQUOTE,
    ACTIONS(333), 1,
      aux_sym_quoted_attribute_value_token2,
  [1654] = 1,
    ACTIONS(335), 1,
      anon_sym_GT,
  [1658] = 1,
    ACTIONS(337), 1,
      sym_raw_text_expr,
  [1662] = 1,
    ACTIONS(339), 1,
      anon_sym_RBRACE,
  [1666] = 1,
    ACTIONS(341), 1,
      anon_sym_RBRACE,
  [1670] = 1,
    ACTIONS(343), 1,
      anon_sym_SQUOTE,
  [1674] = 1,
    ACTIONS(345), 1,
      sym__end_tag_name,
  [1678] = 1,
    ACTIONS(295), 1,
      sym__start_tag_name,
  [1682] = 1,
    ACTIONS(347), 1,
      ts_builtin_sym_end,
  [1686] = 1,
    ACTIONS(349), 1,
      anon_sym_RBRACE,
  [1690] = 1,
    ACTIONS(351), 1,
      anon_sym_GT,
  [1694] = 1,
    ACTIONS(353), 1,
      anon_sym_RBRACE,
  [1698] = 1,
    ACTIONS(263), 1,
      anon_sym_SLASHif,
  [1702] = 1,
    ACTIONS(355), 1,
      sym_raw_text_expr,
  [1706] = 1,
    ACTIONS(357), 1,
      anon_sym_RBRACE,
  [1710] = 1,
    ACTIONS(359), 1,
      anon_sym_RBRACE,
  [1714] = 1,
    ACTIONS(361), 1,
      anon_sym_RBRACE,
  [1718] = 1,
    ACTIONS(363), 1,
      anon_sym_SQUOTE,
  [1722] = 1,
    ACTIONS(363), 1,
      anon_sym_DQUOTE,
  [1726] = 1,
    ACTIONS(365), 1,
      anon_sym_RBRACE,
  [1730] = 1,
    ACTIONS(367), 1,
      anon_sym_RBRACE,
  [1734] = 1,
    ACTIONS(369), 1,
      anon_sym_RBRACE,
  [1738] = 1,
    ACTIONS(257), 1,
      anon_sym_SLASHif,
  [1742] = 1,
    ACTIONS(371), 1,
      sym__end_tag_name,
  [1746] = 1,
    ACTIONS(343), 1,
      anon_sym_DQUOTE,
  [1750] = 1,
    ACTIONS(373), 1,
      sym_raw_text_expr,
};

static uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 51,
  [SMALL_STATE(4)] = 102,
  [SMALL_STATE(5)] = 153,
  [SMALL_STATE(6)] = 204,
  [SMALL_STATE(7)] = 252,
  [SMALL_STATE(8)] = 297,
  [SMALL_STATE(9)] = 342,
  [SMALL_STATE(10)] = 384,
  [SMALL_STATE(11)] = 426,
  [SMALL_STATE(12)] = 468,
  [SMALL_STATE(13)] = 510,
  [SMALL_STATE(14)] = 543,
  [SMALL_STATE(15)] = 576,
  [SMALL_STATE(16)] = 609,
  [SMALL_STATE(17)] = 632,
  [SMALL_STATE(18)] = 653,
  [SMALL_STATE(19)] = 676,
  [SMALL_STATE(20)] = 699,
  [SMALL_STATE(21)] = 720,
  [SMALL_STATE(22)] = 743,
  [SMALL_STATE(23)] = 764,
  [SMALL_STATE(24)] = 776,
  [SMALL_STATE(25)] = 788,
  [SMALL_STATE(26)] = 800,
  [SMALL_STATE(27)] = 820,
  [SMALL_STATE(28)] = 840,
  [SMALL_STATE(29)] = 852,
  [SMALL_STATE(30)] = 864,
  [SMALL_STATE(31)] = 876,
  [SMALL_STATE(32)] = 888,
  [SMALL_STATE(33)] = 908,
  [SMALL_STATE(34)] = 920,
  [SMALL_STATE(35)] = 932,
  [SMALL_STATE(36)] = 944,
  [SMALL_STATE(37)] = 956,
  [SMALL_STATE(38)] = 968,
  [SMALL_STATE(39)] = 980,
  [SMALL_STATE(40)] = 1000,
  [SMALL_STATE(41)] = 1012,
  [SMALL_STATE(42)] = 1032,
  [SMALL_STATE(43)] = 1044,
  [SMALL_STATE(44)] = 1056,
  [SMALL_STATE(45)] = 1068,
  [SMALL_STATE(46)] = 1080,
  [SMALL_STATE(47)] = 1092,
  [SMALL_STATE(48)] = 1103,
  [SMALL_STATE(49)] = 1114,
  [SMALL_STATE(50)] = 1125,
  [SMALL_STATE(51)] = 1136,
  [SMALL_STATE(52)] = 1147,
  [SMALL_STATE(53)] = 1158,
  [SMALL_STATE(54)] = 1169,
  [SMALL_STATE(55)] = 1180,
  [SMALL_STATE(56)] = 1191,
  [SMALL_STATE(57)] = 1202,
  [SMALL_STATE(58)] = 1213,
  [SMALL_STATE(59)] = 1224,
  [SMALL_STATE(60)] = 1235,
  [SMALL_STATE(61)] = 1246,
  [SMALL_STATE(62)] = 1257,
  [SMALL_STATE(63)] = 1268,
  [SMALL_STATE(64)] = 1279,
  [SMALL_STATE(65)] = 1289,
  [SMALL_STATE(66)] = 1299,
  [SMALL_STATE(67)] = 1309,
  [SMALL_STATE(68)] = 1325,
  [SMALL_STATE(69)] = 1333,
  [SMALL_STATE(70)] = 1349,
  [SMALL_STATE(71)] = 1356,
  [SMALL_STATE(72)] = 1363,
  [SMALL_STATE(73)] = 1370,
  [SMALL_STATE(74)] = 1377,
  [SMALL_STATE(75)] = 1384,
  [SMALL_STATE(76)] = 1391,
  [SMALL_STATE(77)] = 1400,
  [SMALL_STATE(78)] = 1407,
  [SMALL_STATE(79)] = 1414,
  [SMALL_STATE(80)] = 1420,
  [SMALL_STATE(81)] = 1426,
  [SMALL_STATE(82)] = 1436,
  [SMALL_STATE(83)] = 1446,
  [SMALL_STATE(84)] = 1456,
  [SMALL_STATE(85)] = 1466,
  [SMALL_STATE(86)] = 1476,
  [SMALL_STATE(87)] = 1486,
  [SMALL_STATE(88)] = 1492,
  [SMALL_STATE(89)] = 1498,
  [SMALL_STATE(90)] = 1504,
  [SMALL_STATE(91)] = 1510,
  [SMALL_STATE(92)] = 1520,
  [SMALL_STATE(93)] = 1530,
  [SMALL_STATE(94)] = 1536,
  [SMALL_STATE(95)] = 1543,
  [SMALL_STATE(96)] = 1550,
  [SMALL_STATE(97)] = 1557,
  [SMALL_STATE(98)] = 1564,
  [SMALL_STATE(99)] = 1571,
  [SMALL_STATE(100)] = 1578,
  [SMALL_STATE(101)] = 1585,
  [SMALL_STATE(102)] = 1592,
  [SMALL_STATE(103)] = 1599,
  [SMALL_STATE(104)] = 1604,
  [SMALL_STATE(105)] = 1609,
  [SMALL_STATE(106)] = 1614,
  [SMALL_STATE(107)] = 1619,
  [SMALL_STATE(108)] = 1626,
  [SMALL_STATE(109)] = 1633,
  [SMALL_STATE(110)] = 1640,
  [SMALL_STATE(111)] = 1647,
  [SMALL_STATE(112)] = 1654,
  [SMALL_STATE(113)] = 1658,
  [SMALL_STATE(114)] = 1662,
  [SMALL_STATE(115)] = 1666,
  [SMALL_STATE(116)] = 1670,
  [SMALL_STATE(117)] = 1674,
  [SMALL_STATE(118)] = 1678,
  [SMALL_STATE(119)] = 1682,
  [SMALL_STATE(120)] = 1686,
  [SMALL_STATE(121)] = 1690,
  [SMALL_STATE(122)] = 1694,
  [SMALL_STATE(123)] = 1698,
  [SMALL_STATE(124)] = 1702,
  [SMALL_STATE(125)] = 1706,
  [SMALL_STATE(126)] = 1710,
  [SMALL_STATE(127)] = 1714,
  [SMALL_STATE(128)] = 1718,
  [SMALL_STATE(129)] = 1722,
  [SMALL_STATE(130)] = 1726,
  [SMALL_STATE(131)] = 1730,
  [SMALL_STATE(132)] = 1734,
  [SMALL_STATE(133)] = 1738,
  [SMALL_STATE(134)] = 1742,
  [SMALL_STATE(135)] = 1746,
  [SMALL_STATE(136)] = 1750,
};

static TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(85),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(134),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(91),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(117),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(82),
  [44] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(6),
  [49] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(6),
  [52] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(91),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [63] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(86),
  [66] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(8),
  [69] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(8),
  [72] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(85),
  [75] = {.entry = {.count = 1, .reusable = false}}, SHIFT(118),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [79] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [81] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [85] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [87] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [91] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [93] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_if_statement_repeat1, 2), SHIFT_REPEAT(118),
  [96] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_if_statement_repeat1, 2), SHIFT_REPEAT(13),
  [99] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_if_statement_repeat1, 2), SHIFT_REPEAT(13),
  [102] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_if_statement_repeat1, 2), SHIFT_REPEAT(85),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [107] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2),
  [119] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2), SHIFT_REPEAT(68),
  [122] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2), SHIFT_REPEAT(124),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(136),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_element, 3),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_element, 3),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_element, 3),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_element, 3),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_html_expr, 4),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_html_expr, 4),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [163] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2), SHIFT_REPEAT(78),
  [166] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2), SHIFT_REPEAT(136),
  [169] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag, 4),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag, 4),
  [173] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 3),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 3),
  [177] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 4),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 4),
  [181] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 3),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 3),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [187] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 4),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 4),
  [191] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_element, 2),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_element, 2),
  [195] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 1),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 1),
  [199] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 3),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 3),
  [203] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_end_tag, 3),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_tag, 3),
  [207] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_html_expr, 3),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_html_expr, 3),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [213] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 3),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 3),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [219] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 2),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 2),
  [223] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag, 3),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag, 3),
  [227] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_end_expr, 3),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_end_expr, 3),
  [231] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 2),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 2),
  [235] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_element, 2),
  [237] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_element, 2),
  [239] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 1),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [243] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_start_expr, 4),
  [245] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_start_expr, 4),
  [247] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_else_expr, 3),
  [249] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_else_expr, 3),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(132),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [261] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_name, 1),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [265] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_value, 1),
  [267] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 1, .production_id = 1),
  [269] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3),
  [271] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr_attribute_value, 1),
  [273] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 2),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [277] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 3),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(134),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [305] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(133),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(135),
  [313] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_start_tag, 3),
  [315] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_start_tag, 3),
  [317] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_start_tag, 4),
  [319] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_start_tag, 4),
  [321] = {.entry = {.count = 1, .reusable = false}}, SHIFT(89),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(128),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [339] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [343] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [345] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [347] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [349] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [351] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [353] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [355] = {.entry = {.count = 1, .reusable = true}}, SHIFT(130),
  [357] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [359] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [361] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [363] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [365] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [367] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [369] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [371] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [373] = {.entry = {.count = 1, .reusable = true}}, SHIFT(131),
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_svelte_external_scanner_create(void);
void tree_sitter_svelte_external_scanner_destroy(void *);
bool tree_sitter_svelte_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_svelte_external_scanner_serialize(void *, char *);
void tree_sitter_svelte_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_svelte(void) {
  static TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .parse_table = (const uint16_t *)ts_parse_table,
    .parse_actions = ts_parse_actions,
    .lex_modes = ts_lex_modes,
    .alias_sequences = (const TSSymbol *)ts_alias_sequences,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .lex_fn = ts_lex,
    .external_scanner = {
      (const bool *)ts_external_scanner_states,
      ts_external_scanner_symbol_map,
      tree_sitter_svelte_external_scanner_create,
      tree_sitter_svelte_external_scanner_destroy,
      tree_sitter_svelte_external_scanner_scan,
      tree_sitter_svelte_external_scanner_serialize,
      tree_sitter_svelte_external_scanner_deserialize,
    },
    .field_count = FIELD_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .small_parse_table = (const uint16_t *)ts_small_parse_table,
    .small_parse_table_map = (const uint32_t *)ts_small_parse_table_map,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .state_count = STATE_COUNT,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
