#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 12
#define STATE_COUNT 138
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 62
#define ALIAS_COUNT 0
#define TOKEN_COUNT 36
#define EXTERNAL_TOKEN_COUNT 10
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4

enum {
  anon_sym_LBRACE_AThtml = 1,
  anon_sym_RBRACE = 2,
  anon_sym_LBRACE_POUND = 3,
  anon_sym_if = 4,
  anon_sym_each = 5,
  anon_sym_await = 6,
  anon_sym_LBRACE_COLON = 7,
  anon_sym_elseif = 8,
  anon_sym_elseif2 = 9,
  anon_sym_else = 10,
  anon_sym_then = 11,
  anon_sym_catch = 12,
  anon_sym_LBRACE_SLASH = 13,
  anon_sym_LT = 14,
  anon_sym_GT = 15,
  anon_sym_SLASH_GT = 16,
  anon_sym_LT_SLASH = 17,
  anon_sym_EQ = 18,
  aux_sym_attribute_name_token1 = 19,
  anon_sym_SQUOTE = 20,
  aux_sym_quoted_attribute_value_token1 = 21,
  anon_sym_DQUOTE = 22,
  aux_sym_quoted_attribute_value_token2 = 23,
  aux_sym__text_token1 = 24,
  anon_sym_LBRACE = 25,
  anon_sym_LBRACE_RBRACE = 26,
  sym__start_tag_name = 27,
  sym__script_start_tag_name = 28,
  sym__style_start_tag_name = 29,
  sym__end_tag_name = 30,
  sym_errorneous_end_tag_name = 31,
  sym__implicit_end_tag = 32,
  sym_raw_text = 33,
  sym_raw_text_expr = 34,
  sym_comment = 35,
  sym_document = 36,
  sym__node = 37,
  sym_element = 38,
  sym_html_block = 39,
  sym_special_block_start = 40,
  sym__special_block_start_tag = 41,
  sym_special_block_intermediate = 42,
  sym__special_block_intermediate_tag = 43,
  sym_special_block_end = 44,
  sym__special_block_end_tag = 45,
  sym_start_tag = 46,
  sym_self_closing_tag = 47,
  sym_end_tag = 48,
  sym_script_element = 49,
  sym_script_start_tag = 50,
  sym_style_element = 51,
  sym_style_start_tag = 52,
  sym_attribute = 53,
  sym_attribute_name = 54,
  sym_attribute_value = 55,
  sym_expr_attribute_value = 56,
  sym_quoted_attribute_value = 57,
  sym__text = 58,
  sym__expression = 59,
  aux_sym_document_repeat1 = 60,
  aux_sym_start_tag_repeat1 = 61,
};

static const char *ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACE_AThtml] = "{@html",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LBRACE_POUND] = "{#",
  [anon_sym_if] = "if_tag",
  [anon_sym_each] = "each_tag",
  [anon_sym_await] = "await_tag",
  [anon_sym_LBRACE_COLON] = "{:",
  [anon_sym_elseif] = "elseif_tag",
  [anon_sym_elseif2] = "elseif_tag",
  [anon_sym_else] = "else_tag",
  [anon_sym_then] = "then_tag",
  [anon_sym_catch] = "catch",
  [anon_sym_LBRACE_SLASH] = "{/",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_SLASH_GT] = "/>",
  [anon_sym_LT_SLASH] = "</",
  [anon_sym_EQ] = "=",
  [aux_sym_attribute_name_token1] = "attribute_name_token1",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_quoted_attribute_value_token1] = "attribute_value",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_quoted_attribute_value_token2] = "attribute_value",
  [aux_sym__text_token1] = "text",
  [anon_sym_LBRACE] = "{",
  [anon_sym_LBRACE_RBRACE] = "{}",
  [sym__start_tag_name] = "tag_name",
  [sym__script_start_tag_name] = "tag_name",
  [sym__style_start_tag_name] = "tag_name",
  [sym__end_tag_name] = "tag_name",
  [sym_errorneous_end_tag_name] = "errorneous_end_tag_name",
  [sym__implicit_end_tag] = "_implicit_end_tag",
  [sym_raw_text] = "raw_text",
  [sym_raw_text_expr] = "raw_text_expr",
  [sym_comment] = "comment",
  [sym_document] = "document",
  [sym__node] = "_node",
  [sym_element] = "element",
  [sym_html_block] = "html_block",
  [sym_special_block_start] = "special_block_start",
  [sym__special_block_start_tag] = "_special_block_start_tag",
  [sym_special_block_intermediate] = "special_block_intermediate",
  [sym__special_block_intermediate_tag] = "_special_block_intermediate_tag",
  [sym_special_block_end] = "special_block_end",
  [sym__special_block_end_tag] = "_special_block_end_tag",
  [sym_start_tag] = "start_tag",
  [sym_self_closing_tag] = "self_closing_tag",
  [sym_end_tag] = "end_tag",
  [sym_script_element] = "script_element",
  [sym_script_start_tag] = "start_tag",
  [sym_style_element] = "style_element",
  [sym_style_start_tag] = "start_tag",
  [sym_attribute] = "attribute",
  [sym_attribute_name] = "attribute_name",
  [sym_attribute_value] = "attribute_value",
  [sym_expr_attribute_value] = "expr_attribute_value",
  [sym_quoted_attribute_value] = "quoted_attribute_value",
  [sym__text] = "_text",
  [sym__expression] = "_expression",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_start_tag_repeat1] = "start_tag_repeat1",
};

static TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACE_AThtml] = anon_sym_LBRACE_AThtml,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LBRACE_POUND] = anon_sym_LBRACE_POUND,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_each] = anon_sym_each,
  [anon_sym_await] = anon_sym_await,
  [anon_sym_LBRACE_COLON] = anon_sym_LBRACE_COLON,
  [anon_sym_elseif] = anon_sym_elseif,
  [anon_sym_elseif2] = anon_sym_elseif,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_then] = anon_sym_then,
  [anon_sym_catch] = anon_sym_catch,
  [anon_sym_LBRACE_SLASH] = anon_sym_LBRACE_SLASH,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_SLASH_GT] = anon_sym_SLASH_GT,
  [anon_sym_LT_SLASH] = anon_sym_LT_SLASH,
  [anon_sym_EQ] = anon_sym_EQ,
  [aux_sym_attribute_name_token1] = aux_sym_attribute_name_token1,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_quoted_attribute_value_token1] = sym_attribute_value,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_quoted_attribute_value_token2] = sym_attribute_value,
  [aux_sym__text_token1] = aux_sym__text_token1,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_LBRACE_RBRACE] = anon_sym_LBRACE_RBRACE,
  [sym__start_tag_name] = sym__start_tag_name,
  [sym__script_start_tag_name] = sym__start_tag_name,
  [sym__style_start_tag_name] = sym__start_tag_name,
  [sym__end_tag_name] = sym__start_tag_name,
  [sym_errorneous_end_tag_name] = sym_errorneous_end_tag_name,
  [sym__implicit_end_tag] = sym__implicit_end_tag,
  [sym_raw_text] = sym_raw_text,
  [sym_raw_text_expr] = sym_raw_text_expr,
  [sym_comment] = sym_comment,
  [sym_document] = sym_document,
  [sym__node] = sym__node,
  [sym_element] = sym_element,
  [sym_html_block] = sym_html_block,
  [sym_special_block_start] = sym_special_block_start,
  [sym__special_block_start_tag] = sym__special_block_start_tag,
  [sym_special_block_intermediate] = sym_special_block_intermediate,
  [sym__special_block_intermediate_tag] = sym__special_block_intermediate_tag,
  [sym_special_block_end] = sym_special_block_end,
  [sym__special_block_end_tag] = sym__special_block_end_tag,
  [sym_start_tag] = sym_start_tag,
  [sym_self_closing_tag] = sym_self_closing_tag,
  [sym_end_tag] = sym_end_tag,
  [sym_script_element] = sym_script_element,
  [sym_script_start_tag] = sym_start_tag,
  [sym_style_element] = sym_style_element,
  [sym_style_start_tag] = sym_start_tag,
  [sym_attribute] = sym_attribute,
  [sym_attribute_name] = sym_attribute_name,
  [sym_attribute_value] = sym_attribute_value,
  [sym_expr_attribute_value] = sym_expr_attribute_value,
  [sym_quoted_attribute_value] = sym_quoted_attribute_value,
  [sym__text] = sym__text,
  [sym__expression] = sym__expression,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_start_tag_repeat1] = aux_sym_start_tag_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACE_AThtml] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_each] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_await] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_elseif] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_elseif2] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_then] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_catch] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_attribute_name_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_attribute_value_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_attribute_value_token2] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__text_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym__start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__script_start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__style_start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__end_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_errorneous_end_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__implicit_end_tag] = {
    .visible = false,
    .named = true,
  },
  [sym_raw_text] = {
    .visible = true,
    .named = true,
  },
  [sym_raw_text_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym__node] = {
    .visible = false,
    .named = true,
  },
  [sym_element] = {
    .visible = true,
    .named = true,
  },
  [sym_html_block] = {
    .visible = true,
    .named = true,
  },
  [sym_special_block_start] = {
    .visible = true,
    .named = true,
  },
  [sym__special_block_start_tag] = {
    .visible = false,
    .named = true,
  },
  [sym_special_block_intermediate] = {
    .visible = true,
    .named = true,
  },
  [sym__special_block_intermediate_tag] = {
    .visible = false,
    .named = true,
  },
  [sym_special_block_end] = {
    .visible = true,
    .named = true,
  },
  [sym__special_block_end_tag] = {
    .visible = false,
    .named = true,
  },
  [sym_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_self_closing_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_script_element] = {
    .visible = true,
    .named = true,
  },
  [sym_script_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_style_element] = {
    .visible = true,
    .named = true,
  },
  [sym_style_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_name] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [sym_expr_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [sym__text] = {
    .visible = false,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_start_tag_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static TSSymbol ts_alias_sequences[2][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = sym_attribute_name,
  },
};

static uint16_t ts_non_terminal_alias_map[] = {
  sym__expression, 2,
    sym__expression,
    sym_attribute_name,
  0,
};

static inline bool aux_sym_attribute_name_token1_character_set_1(int32_t lookahead) {
  return
    lookahead == 0 ||
    lookahead == '\t' ||
    lookahead == '\n' ||
    lookahead == '\r' ||
    lookahead == ' ' ||
    lookahead == '"' ||
    lookahead == '\'' ||
    lookahead == '/' ||
    ('<' <= lookahead && lookahead <= '>') ||
    lookahead == '{' ||
    lookahead == '}';
}

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(31);
      if (lookahead == '"') ADVANCE(79);
      if (lookahead == '\'') ADVANCE(76);
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == '<') ADVANCE(52);
      if (lookahead == '=') ADVANCE(56);
      if (lookahead == '>') ADVANCE(53);
      if (lookahead == 'a') ADVANCE(74);
      if (lookahead == 'c') ADVANCE(57);
      if (lookahead == 'e') ADVANCE(58);
      if (lookahead == 'i') ADVANCE(64);
      if (lookahead == 't') ADVANCE(66);
      if (lookahead == '{') ADVANCE(83);
      if (lookahead == '}') ADVANCE(33);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (lookahead != 0) ADVANCE(75);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(79);
      if (lookahead == '\'') ADVANCE(76);
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == '=') ADVANCE(56);
      if (lookahead == '>') ADVANCE(53);
      if (lookahead == '{') ADVANCE(84);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '}') ADVANCE(75);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(79);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(80);
      if (lookahead != 0) ADVANCE(81);
      END_STATE();
    case 3:
      if (lookahead == '\'') ADVANCE(76);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(77);
      if (lookahead != 0) ADVANCE(78);
      END_STATE();
    case 4:
      if (lookahead == '>') ADVANCE(54);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(29);
      if (lookahead == 'c') ADVANCE(8);
      if (lookahead == 'e') ADVANCE(6);
      if (lookahead == 'i') ADVANCE(13);
      if (lookahead == 't') ADVANCE(17);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(5)
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(9);
      if (lookahead == 'l') ADVANCE(25);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(20);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(28);
      END_STATE();
    case 9:
      if (lookahead == 'c') ADVANCE(18);
      END_STATE();
    case 10:
      if (lookahead == 'c') ADVANCE(19);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(24);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(45);
      END_STATE();
    case 13:
      if (lookahead == 'f') ADVANCE(35);
      END_STATE();
    case 14:
      if (lookahead == 'f') ADVANCE(43);
      END_STATE();
    case 15:
      if (lookahead == 'f') ADVANCE(42);
      END_STATE();
    case 16:
      if (lookahead == 'h') ADVANCE(26);
      END_STATE();
    case 17:
      if (lookahead == 'h') ADVANCE(11);
      END_STATE();
    case 18:
      if (lookahead == 'h') ADVANCE(37);
      END_STATE();
    case 19:
      if (lookahead == 'h') ADVANCE(49);
      END_STATE();
    case 20:
      if (lookahead == 'i') ADVANCE(27);
      END_STATE();
    case 21:
      if (lookahead == 'i') ADVANCE(15);
      END_STATE();
    case 22:
      if (lookahead == 'l') ADVANCE(32);
      END_STATE();
    case 23:
      if (lookahead == 'm') ADVANCE(22);
      END_STATE();
    case 24:
      if (lookahead == 'n') ADVANCE(47);
      END_STATE();
    case 25:
      if (lookahead == 's') ADVANCE(12);
      END_STATE();
    case 26:
      if (lookahead == 't') ADVANCE(23);
      END_STATE();
    case 27:
      if (lookahead == 't') ADVANCE(39);
      END_STATE();
    case 28:
      if (lookahead == 't') ADVANCE(10);
      END_STATE();
    case 29:
      if (lookahead == 'w') ADVANCE(7);
      END_STATE();
    case 30:
      if (eof) ADVANCE(31);
      if (lookahead == '<') ADVANCE(52);
      if (lookahead == '{') ADVANCE(83);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(30)
      if (lookahead != 0 &&
          lookahead != '>' &&
          lookahead != '}') ADVANCE(82);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_LBRACE_AThtml);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_LBRACE_POUND);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_if);
      if (!aux_sym_attribute_name_token1_character_set_1(lookahead)) ADVANCE(75);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_each);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_each);
      if (!aux_sym_attribute_name_token1_character_set_1(lookahead)) ADVANCE(75);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_await);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_await);
      if (!aux_sym_attribute_name_token1_character_set_1(lookahead)) ADVANCE(75);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_LBRACE_COLON);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_elseif);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_elseif2);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_elseif2);
      if (!aux_sym_attribute_name_token1_character_set_1(lookahead)) ADVANCE(75);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_else);
      if (lookahead == ' ') ADVANCE(21);
      if (lookahead == 'i') ADVANCE(14);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_else);
      if (lookahead == 'i') ADVANCE(65);
      if (!aux_sym_attribute_name_token1_character_set_1(lookahead)) ADVANCE(75);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_then);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_then);
      if (!aux_sym_attribute_name_token1_character_set_1(lookahead)) ADVANCE(75);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_catch);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_catch);
      if (!aux_sym_attribute_name_token1_character_set_1(lookahead)) ADVANCE(75);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_LBRACE_SLASH);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '/') ADVANCE(55);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_SLASH_GT);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(aux_sym_attribute_name_token1);
      if (lookahead == 'a') ADVANCE(73);
      if (!aux_sym_attribute_name_token1_character_set_1(lookahead)) ADVANCE(75);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(aux_sym_attribute_name_token1);
      if (lookahead == 'a') ADVANCE(60);
      if (lookahead == 'l') ADVANCE(71);
      if (!aux_sym_attribute_name_token1_character_set_1(lookahead)) ADVANCE(75);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(aux_sym_attribute_name_token1);
      if (lookahead == 'a') ADVANCE(69);
      if (!aux_sym_attribute_name_token1_character_set_1(lookahead)) ADVANCE(75);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(aux_sym_attribute_name_token1);
      if (lookahead == 'c') ADVANCE(67);
      if (!aux_sym_attribute_name_token1_character_set_1(lookahead)) ADVANCE(75);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(aux_sym_attribute_name_token1);
      if (lookahead == 'c') ADVANCE(68);
      if (!aux_sym_attribute_name_token1_character_set_1(lookahead)) ADVANCE(75);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(aux_sym_attribute_name_token1);
      if (lookahead == 'e') ADVANCE(70);
      if (!aux_sym_attribute_name_token1_character_set_1(lookahead)) ADVANCE(75);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(aux_sym_attribute_name_token1);
      if (lookahead == 'e') ADVANCE(46);
      if (!aux_sym_attribute_name_token1_character_set_1(lookahead)) ADVANCE(75);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(aux_sym_attribute_name_token1);
      if (lookahead == 'f') ADVANCE(36);
      if (!aux_sym_attribute_name_token1_character_set_1(lookahead)) ADVANCE(75);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(aux_sym_attribute_name_token1);
      if (lookahead == 'f') ADVANCE(44);
      if (!aux_sym_attribute_name_token1_character_set_1(lookahead)) ADVANCE(75);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(aux_sym_attribute_name_token1);
      if (lookahead == 'h') ADVANCE(62);
      if (!aux_sym_attribute_name_token1_character_set_1(lookahead)) ADVANCE(75);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(aux_sym_attribute_name_token1);
      if (lookahead == 'h') ADVANCE(38);
      if (!aux_sym_attribute_name_token1_character_set_1(lookahead)) ADVANCE(75);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(aux_sym_attribute_name_token1);
      if (lookahead == 'h') ADVANCE(50);
      if (!aux_sym_attribute_name_token1_character_set_1(lookahead)) ADVANCE(75);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(aux_sym_attribute_name_token1);
      if (lookahead == 'i') ADVANCE(72);
      if (!aux_sym_attribute_name_token1_character_set_1(lookahead)) ADVANCE(75);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(aux_sym_attribute_name_token1);
      if (lookahead == 'n') ADVANCE(48);
      if (!aux_sym_attribute_name_token1_character_set_1(lookahead)) ADVANCE(75);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(aux_sym_attribute_name_token1);
      if (lookahead == 's') ADVANCE(63);
      if (!aux_sym_attribute_name_token1_character_set_1(lookahead)) ADVANCE(75);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(aux_sym_attribute_name_token1);
      if (lookahead == 't') ADVANCE(40);
      if (!aux_sym_attribute_name_token1_character_set_1(lookahead)) ADVANCE(75);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(aux_sym_attribute_name_token1);
      if (lookahead == 't') ADVANCE(61);
      if (!aux_sym_attribute_name_token1_character_set_1(lookahead)) ADVANCE(75);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(aux_sym_attribute_name_token1);
      if (lookahead == 'w') ADVANCE(59);
      if (!aux_sym_attribute_name_token1_character_set_1(lookahead)) ADVANCE(75);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(aux_sym_attribute_name_token1);
      if (!aux_sym_attribute_name_token1_character_set_1(lookahead)) ADVANCE(75);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(77);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(78);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token1);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(78);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token2);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(80);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(81);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token2);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(81);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(aux_sym__text_token1);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '<' &&
          lookahead != '>' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(82);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead == '#') ADVANCE(34);
      if (lookahead == '/') ADVANCE(51);
      if (lookahead == ':') ADVANCE(41);
      if (lookahead == '@') ADVANCE(16);
      if (lookahead == '}') ADVANCE(85);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead == '}') ADVANCE(85);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_LBRACE_RBRACE);
      END_STATE();
    default:
      return false;
  }
}

static TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 30, .external_lex_state = 2},
  [2] = {.lex_state = 30, .external_lex_state = 3},
  [3] = {.lex_state = 30, .external_lex_state = 3},
  [4] = {.lex_state = 30, .external_lex_state = 3},
  [5] = {.lex_state = 30, .external_lex_state = 3},
  [6] = {.lex_state = 30, .external_lex_state = 3},
  [7] = {.lex_state = 30, .external_lex_state = 2},
  [8] = {.lex_state = 30, .external_lex_state = 2},
  [9] = {.lex_state = 30, .external_lex_state = 3},
  [10] = {.lex_state = 30, .external_lex_state = 3},
  [11] = {.lex_state = 30, .external_lex_state = 3},
  [12] = {.lex_state = 30, .external_lex_state = 3},
  [13] = {.lex_state = 30, .external_lex_state = 3},
  [14] = {.lex_state = 30, .external_lex_state = 3},
  [15] = {.lex_state = 30, .external_lex_state = 3},
  [16] = {.lex_state = 30, .external_lex_state = 3},
  [17] = {.lex_state = 30, .external_lex_state = 3},
  [18] = {.lex_state = 30, .external_lex_state = 3},
  [19] = {.lex_state = 30, .external_lex_state = 3},
  [20] = {.lex_state = 30, .external_lex_state = 3},
  [21] = {.lex_state = 30, .external_lex_state = 3},
  [22] = {.lex_state = 30, .external_lex_state = 3},
  [23] = {.lex_state = 30, .external_lex_state = 3},
  [24] = {.lex_state = 30, .external_lex_state = 3},
  [25] = {.lex_state = 30, .external_lex_state = 3},
  [26] = {.lex_state = 30, .external_lex_state = 3},
  [27] = {.lex_state = 30, .external_lex_state = 3},
  [28] = {.lex_state = 30, .external_lex_state = 3},
  [29] = {.lex_state = 30, .external_lex_state = 3},
  [30] = {.lex_state = 30, .external_lex_state = 2},
  [31] = {.lex_state = 30, .external_lex_state = 2},
  [32] = {.lex_state = 30, .external_lex_state = 2},
  [33] = {.lex_state = 30, .external_lex_state = 2},
  [34] = {.lex_state = 30, .external_lex_state = 2},
  [35] = {.lex_state = 30, .external_lex_state = 2},
  [36] = {.lex_state = 30, .external_lex_state = 2},
  [37] = {.lex_state = 30, .external_lex_state = 2},
  [38] = {.lex_state = 30, .external_lex_state = 2},
  [39] = {.lex_state = 30, .external_lex_state = 2},
  [40] = {.lex_state = 30, .external_lex_state = 2},
  [41] = {.lex_state = 30, .external_lex_state = 2},
  [42] = {.lex_state = 30, .external_lex_state = 2},
  [43] = {.lex_state = 30, .external_lex_state = 2},
  [44] = {.lex_state = 30, .external_lex_state = 2},
  [45] = {.lex_state = 30, .external_lex_state = 2},
  [46] = {.lex_state = 30, .external_lex_state = 2},
  [47] = {.lex_state = 30, .external_lex_state = 2},
  [48] = {.lex_state = 30, .external_lex_state = 2},
  [49] = {.lex_state = 1, .external_lex_state = 4},
  [50] = {.lex_state = 1, .external_lex_state = 4},
  [51] = {.lex_state = 1, .external_lex_state = 4},
  [52] = {.lex_state = 1},
  [53] = {.lex_state = 1, .external_lex_state = 4},
  [54] = {.lex_state = 1, .external_lex_state = 4},
  [55] = {.lex_state = 1},
  [56] = {.lex_state = 1},
  [57] = {.lex_state = 1},
  [58] = {.lex_state = 1},
  [59] = {.lex_state = 1},
  [60] = {.lex_state = 1},
  [61] = {.lex_state = 5},
  [62] = {.lex_state = 5},
  [63] = {.lex_state = 1, .external_lex_state = 4},
  [64] = {.lex_state = 1, .external_lex_state = 4},
  [65] = {.lex_state = 1, .external_lex_state = 4},
  [66] = {.lex_state = 1, .external_lex_state = 4},
  [67] = {.lex_state = 1, .external_lex_state = 4},
  [68] = {.lex_state = 1},
  [69] = {.lex_state = 1, .external_lex_state = 4},
  [70] = {.lex_state = 1, .external_lex_state = 4},
  [71] = {.lex_state = 1},
  [72] = {.lex_state = 1, .external_lex_state = 4},
  [73] = {.lex_state = 1, .external_lex_state = 4},
  [74] = {.lex_state = 1, .external_lex_state = 4},
  [75] = {.lex_state = 1, .external_lex_state = 4},
  [76] = {.lex_state = 1},
  [77] = {.lex_state = 1},
  [78] = {.lex_state = 5},
  [79] = {.lex_state = 1},
  [80] = {.lex_state = 5},
  [81] = {.lex_state = 1},
  [82] = {.lex_state = 1},
  [83] = {.lex_state = 1},
  [84] = {.lex_state = 1},
  [85] = {.lex_state = 1},
  [86] = {.lex_state = 1},
  [87] = {.lex_state = 5},
  [88] = {.lex_state = 5},
  [89] = {.lex_state = 0, .external_lex_state = 5},
  [90] = {.lex_state = 0, .external_lex_state = 5},
  [91] = {.lex_state = 0, .external_lex_state = 5},
  [92] = {.lex_state = 0, .external_lex_state = 6},
  [93] = {.lex_state = 0, .external_lex_state = 6},
  [94] = {.lex_state = 0, .external_lex_state = 5},
  [95] = {.lex_state = 0, .external_lex_state = 5},
  [96] = {.lex_state = 2},
  [97] = {.lex_state = 0, .external_lex_state = 7},
  [98] = {.lex_state = 3},
  [99] = {.lex_state = 3},
  [100] = {.lex_state = 0, .external_lex_state = 5},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 2},
  [104] = {.lex_state = 0, .external_lex_state = 7},
  [105] = {.lex_state = 0, .external_lex_state = 7},
  [106] = {.lex_state = 0, .external_lex_state = 7},
  [107] = {.lex_state = 0, .external_lex_state = 7},
  [108] = {.lex_state = 0, .external_lex_state = 5},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0, .external_lex_state = 7},
  [111] = {.lex_state = 0, .external_lex_state = 7},
  [112] = {.lex_state = 0, .external_lex_state = 5},
  [113] = {.lex_state = 0, .external_lex_state = 7},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 0},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 0, .external_lex_state = 8},
  [131] = {.lex_state = 0},
  [132] = {.lex_state = 0},
  [133] = {.lex_state = 0},
  [134] = {.lex_state = 0, .external_lex_state = 7},
  [135] = {.lex_state = 0, .external_lex_state = 7},
  [136] = {.lex_state = 0, .external_lex_state = 8},
  [137] = {.lex_state = 0},
};

enum {
  ts_external_token__start_tag_name = 0,
  ts_external_token__script_start_tag_name = 1,
  ts_external_token__style_start_tag_name = 2,
  ts_external_token__end_tag_name = 3,
  ts_external_token_errorneous_end_tag_name = 4,
  ts_external_token_SLASH_GT = 5,
  ts_external_token__implicit_end_tag = 6,
  ts_external_token_raw_text = 7,
  ts_external_token_raw_text_expr = 8,
  ts_external_token_comment = 9,
};

static TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__start_tag_name] = sym__start_tag_name,
  [ts_external_token__script_start_tag_name] = sym__script_start_tag_name,
  [ts_external_token__style_start_tag_name] = sym__style_start_tag_name,
  [ts_external_token__end_tag_name] = sym__end_tag_name,
  [ts_external_token_errorneous_end_tag_name] = sym_errorneous_end_tag_name,
  [ts_external_token_SLASH_GT] = anon_sym_SLASH_GT,
  [ts_external_token__implicit_end_tag] = sym__implicit_end_tag,
  [ts_external_token_raw_text] = sym_raw_text,
  [ts_external_token_raw_text_expr] = sym_raw_text_expr,
  [ts_external_token_comment] = sym_comment,
};

static bool ts_external_scanner_states[9][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__start_tag_name] = true,
    [ts_external_token__script_start_tag_name] = true,
    [ts_external_token__style_start_tag_name] = true,
    [ts_external_token__end_tag_name] = true,
    [ts_external_token_errorneous_end_tag_name] = true,
    [ts_external_token_SLASH_GT] = true,
    [ts_external_token__implicit_end_tag] = true,
    [ts_external_token_raw_text] = true,
    [ts_external_token_raw_text_expr] = true,
    [ts_external_token_comment] = true,
  },
  [2] = {
    [ts_external_token_comment] = true,
  },
  [3] = {
    [ts_external_token__implicit_end_tag] = true,
    [ts_external_token_comment] = true,
  },
  [4] = {
    [ts_external_token_SLASH_GT] = true,
  },
  [5] = {
    [ts_external_token_raw_text] = true,
  },
  [6] = {
    [ts_external_token__start_tag_name] = true,
    [ts_external_token__script_start_tag_name] = true,
    [ts_external_token__style_start_tag_name] = true,
  },
  [7] = {
    [ts_external_token_raw_text_expr] = true,
  },
  [8] = {
    [ts_external_token__end_tag_name] = true,
  },
};

static uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACE_AThtml] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACE_POUND] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_each] = ACTIONS(1),
    [anon_sym_await] = ACTIONS(1),
    [anon_sym_LBRACE_COLON] = ACTIONS(1),
    [anon_sym_elseif2] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_then] = ACTIONS(1),
    [anon_sym_catch] = ACTIONS(1),
    [anon_sym_LBRACE_SLASH] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_SLASH_GT] = ACTIONS(1),
    [anon_sym_LT_SLASH] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [aux_sym_attribute_name_token1] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_LBRACE_RBRACE] = ACTIONS(1),
    [sym__start_tag_name] = ACTIONS(1),
    [sym__script_start_tag_name] = ACTIONS(1),
    [sym__style_start_tag_name] = ACTIONS(1),
    [sym__end_tag_name] = ACTIONS(1),
    [sym_errorneous_end_tag_name] = ACTIONS(1),
    [sym__implicit_end_tag] = ACTIONS(1),
    [sym_raw_text] = ACTIONS(1),
    [sym_raw_text_expr] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
  },
  [1] = {
    [sym_document] = STATE(121),
    [sym__node] = STATE(7),
    [sym_element] = STATE(7),
    [sym_html_block] = STATE(7),
    [sym_special_block_start] = STATE(7),
    [sym_special_block_intermediate] = STATE(7),
    [sym_special_block_end] = STATE(7),
    [sym_start_tag] = STATE(5),
    [sym_self_closing_tag] = STATE(34),
    [sym_script_element] = STATE(7),
    [sym_script_start_tag] = STATE(94),
    [sym_style_element] = STATE(7),
    [sym_style_start_tag] = STATE(89),
    [sym__text] = STATE(7),
    [sym__expression] = STATE(7),
    [aux_sym_document_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LBRACE_AThtml] = ACTIONS(5),
    [anon_sym_LBRACE_POUND] = ACTIONS(7),
    [anon_sym_LBRACE_COLON] = ACTIONS(9),
    [anon_sym_LBRACE_SLASH] = ACTIONS(11),
    [anon_sym_LT] = ACTIONS(13),
    [aux_sym__text_token1] = ACTIONS(15),
    [anon_sym_LBRACE] = ACTIONS(17),
    [anon_sym_LBRACE_RBRACE] = ACTIONS(19),
    [sym_comment] = ACTIONS(15),
  },
};

static uint16_t ts_small_parse_table[] = {
  [0] = 16,
    ACTIONS(21), 1,
      anon_sym_LBRACE_AThtml,
    ACTIONS(23), 1,
      anon_sym_LBRACE_POUND,
    ACTIONS(25), 1,
      anon_sym_LBRACE_COLON,
    ACTIONS(27), 1,
      anon_sym_LBRACE_SLASH,
    ACTIONS(29), 1,
      anon_sym_LT,
    ACTIONS(31), 1,
      anon_sym_LT_SLASH,
    ACTIONS(35), 1,
      anon_sym_LBRACE,
    ACTIONS(37), 1,
      anon_sym_LBRACE_RBRACE,
    ACTIONS(39), 1,
      sym__implicit_end_tag,
    STATE(3), 1,
      sym_start_tag,
    STATE(12), 1,
      sym_end_tag,
    STATE(24), 1,
      sym_self_closing_tag,
    STATE(90), 1,
      sym_style_start_tag,
    STATE(91), 1,
      sym_script_start_tag,
    ACTIONS(33), 2,
      sym_comment,
      aux_sym__text_token1,
    STATE(6), 11,
      sym__node,
      sym_element,
      sym_html_block,
      sym_special_block_start,
      sym_special_block_intermediate,
      sym_special_block_end,
      sym_script_element,
      sym_style_element,
      sym__text,
      sym__expression,
      aux_sym_document_repeat1,
  [60] = 16,
    ACTIONS(21), 1,
      anon_sym_LBRACE_AThtml,
    ACTIONS(23), 1,
      anon_sym_LBRACE_POUND,
    ACTIONS(25), 1,
      anon_sym_LBRACE_COLON,
    ACTIONS(27), 1,
      anon_sym_LBRACE_SLASH,
    ACTIONS(29), 1,
      anon_sym_LT,
    ACTIONS(31), 1,
      anon_sym_LT_SLASH,
    ACTIONS(35), 1,
      anon_sym_LBRACE,
    ACTIONS(37), 1,
      anon_sym_LBRACE_RBRACE,
    ACTIONS(43), 1,
      sym__implicit_end_tag,
    STATE(3), 1,
      sym_start_tag,
    STATE(21), 1,
      sym_end_tag,
    STATE(24), 1,
      sym_self_closing_tag,
    STATE(90), 1,
      sym_style_start_tag,
    STATE(91), 1,
      sym_script_start_tag,
    ACTIONS(41), 2,
      sym_comment,
      aux_sym__text_token1,
    STATE(2), 11,
      sym__node,
      sym_element,
      sym_html_block,
      sym_special_block_start,
      sym_special_block_intermediate,
      sym_special_block_end,
      sym_script_element,
      sym_style_element,
      sym__text,
      sym__expression,
      aux_sym_document_repeat1,
  [120] = 16,
    ACTIONS(21), 1,
      anon_sym_LBRACE_AThtml,
    ACTIONS(23), 1,
      anon_sym_LBRACE_POUND,
    ACTIONS(25), 1,
      anon_sym_LBRACE_COLON,
    ACTIONS(27), 1,
      anon_sym_LBRACE_SLASH,
    ACTIONS(29), 1,
      anon_sym_LT,
    ACTIONS(35), 1,
      anon_sym_LBRACE,
    ACTIONS(37), 1,
      anon_sym_LBRACE_RBRACE,
    ACTIONS(45), 1,
      anon_sym_LT_SLASH,
    ACTIONS(47), 1,
      sym__implicit_end_tag,
    STATE(3), 1,
      sym_start_tag,
    STATE(24), 1,
      sym_self_closing_tag,
    STATE(47), 1,
      sym_end_tag,
    STATE(90), 1,
      sym_style_start_tag,
    STATE(91), 1,
      sym_script_start_tag,
    ACTIONS(33), 2,
      sym_comment,
      aux_sym__text_token1,
    STATE(6), 11,
      sym__node,
      sym_element,
      sym_html_block,
      sym_special_block_start,
      sym_special_block_intermediate,
      sym_special_block_end,
      sym_script_element,
      sym_style_element,
      sym__text,
      sym__expression,
      aux_sym_document_repeat1,
  [180] = 16,
    ACTIONS(21), 1,
      anon_sym_LBRACE_AThtml,
    ACTIONS(23), 1,
      anon_sym_LBRACE_POUND,
    ACTIONS(25), 1,
      anon_sym_LBRACE_COLON,
    ACTIONS(27), 1,
      anon_sym_LBRACE_SLASH,
    ACTIONS(29), 1,
      anon_sym_LT,
    ACTIONS(35), 1,
      anon_sym_LBRACE,
    ACTIONS(37), 1,
      anon_sym_LBRACE_RBRACE,
    ACTIONS(45), 1,
      anon_sym_LT_SLASH,
    ACTIONS(51), 1,
      sym__implicit_end_tag,
    STATE(3), 1,
      sym_start_tag,
    STATE(24), 1,
      sym_self_closing_tag,
    STATE(41), 1,
      sym_end_tag,
    STATE(90), 1,
      sym_style_start_tag,
    STATE(91), 1,
      sym_script_start_tag,
    ACTIONS(49), 2,
      sym_comment,
      aux_sym__text_token1,
    STATE(4), 11,
      sym__node,
      sym_element,
      sym_html_block,
      sym_special_block_start,
      sym_special_block_intermediate,
      sym_special_block_end,
      sym_script_element,
      sym_style_element,
      sym__text,
      sym__expression,
      aux_sym_document_repeat1,
  [240] = 14,
    ACTIONS(53), 1,
      anon_sym_LBRACE_AThtml,
    ACTIONS(56), 1,
      anon_sym_LBRACE_POUND,
    ACTIONS(59), 1,
      anon_sym_LBRACE_COLON,
    ACTIONS(62), 1,
      anon_sym_LBRACE_SLASH,
    ACTIONS(65), 1,
      anon_sym_LT,
    ACTIONS(73), 1,
      anon_sym_LBRACE,
    ACTIONS(76), 1,
      anon_sym_LBRACE_RBRACE,
    STATE(3), 1,
      sym_start_tag,
    STATE(24), 1,
      sym_self_closing_tag,
    STATE(90), 1,
      sym_style_start_tag,
    STATE(91), 1,
      sym_script_start_tag,
    ACTIONS(68), 2,
      sym__implicit_end_tag,
      anon_sym_LT_SLASH,
    ACTIONS(70), 2,
      sym_comment,
      aux_sym__text_token1,
    STATE(6), 11,
      sym__node,
      sym_element,
      sym_html_block,
      sym_special_block_start,
      sym_special_block_intermediate,
      sym_special_block_end,
      sym_script_element,
      sym_style_element,
      sym__text,
      sym__expression,
      aux_sym_document_repeat1,
  [295] = 14,
    ACTIONS(5), 1,
      anon_sym_LBRACE_AThtml,
    ACTIONS(7), 1,
      anon_sym_LBRACE_POUND,
    ACTIONS(9), 1,
      anon_sym_LBRACE_COLON,
    ACTIONS(11), 1,
      anon_sym_LBRACE_SLASH,
    ACTIONS(13), 1,
      anon_sym_LT,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_LBRACE_RBRACE,
    ACTIONS(79), 1,
      ts_builtin_sym_end,
    STATE(5), 1,
      sym_start_tag,
    STATE(34), 1,
      sym_self_closing_tag,
    STATE(89), 1,
      sym_style_start_tag,
    STATE(94), 1,
      sym_script_start_tag,
    ACTIONS(81), 2,
      sym_comment,
      aux_sym__text_token1,
    STATE(8), 11,
      sym__node,
      sym_element,
      sym_html_block,
      sym_special_block_start,
      sym_special_block_intermediate,
      sym_special_block_end,
      sym_script_element,
      sym_style_element,
      sym__text,
      sym__expression,
      aux_sym_document_repeat1,
  [349] = 14,
    ACTIONS(68), 1,
      ts_builtin_sym_end,
    ACTIONS(83), 1,
      anon_sym_LBRACE_AThtml,
    ACTIONS(86), 1,
      anon_sym_LBRACE_POUND,
    ACTIONS(89), 1,
      anon_sym_LBRACE_COLON,
    ACTIONS(92), 1,
      anon_sym_LBRACE_SLASH,
    ACTIONS(95), 1,
      anon_sym_LT,
    ACTIONS(101), 1,
      anon_sym_LBRACE,
    ACTIONS(104), 1,
      anon_sym_LBRACE_RBRACE,
    STATE(5), 1,
      sym_start_tag,
    STATE(34), 1,
      sym_self_closing_tag,
    STATE(89), 1,
      sym_style_start_tag,
    STATE(94), 1,
      sym_script_start_tag,
    ACTIONS(98), 2,
      sym_comment,
      aux_sym__text_token1,
    STATE(8), 11,
      sym__node,
      sym_element,
      sym_html_block,
      sym_special_block_start,
      sym_special_block_intermediate,
      sym_special_block_end,
      sym_script_element,
      sym_style_element,
      sym__text,
      sym__expression,
      aux_sym_document_repeat1,
  [403] = 2,
    ACTIONS(109), 2,
      anon_sym_LT,
      anon_sym_LBRACE,
    ACTIONS(107), 9,
      sym__implicit_end_tag,
      sym_comment,
      anon_sym_LBRACE_AThtml,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT_SLASH,
      aux_sym__text_token1,
      anon_sym_LBRACE_RBRACE,
  [419] = 2,
    ACTIONS(113), 2,
      anon_sym_LT,
      anon_sym_LBRACE,
    ACTIONS(111), 9,
      sym__implicit_end_tag,
      sym_comment,
      anon_sym_LBRACE_AThtml,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT_SLASH,
      aux_sym__text_token1,
      anon_sym_LBRACE_RBRACE,
  [435] = 2,
    ACTIONS(117), 2,
      anon_sym_LT,
      anon_sym_LBRACE,
    ACTIONS(115), 9,
      sym__implicit_end_tag,
      sym_comment,
      anon_sym_LBRACE_AThtml,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT_SLASH,
      aux_sym__text_token1,
      anon_sym_LBRACE_RBRACE,
  [451] = 2,
    ACTIONS(121), 2,
      anon_sym_LT,
      anon_sym_LBRACE,
    ACTIONS(119), 9,
      sym__implicit_end_tag,
      sym_comment,
      anon_sym_LBRACE_AThtml,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT_SLASH,
      aux_sym__text_token1,
      anon_sym_LBRACE_RBRACE,
  [467] = 2,
    ACTIONS(125), 2,
      anon_sym_LT,
      anon_sym_LBRACE,
    ACTIONS(123), 9,
      sym__implicit_end_tag,
      sym_comment,
      anon_sym_LBRACE_AThtml,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT_SLASH,
      aux_sym__text_token1,
      anon_sym_LBRACE_RBRACE,
  [483] = 2,
    ACTIONS(129), 2,
      anon_sym_LT,
      anon_sym_LBRACE,
    ACTIONS(127), 9,
      sym__implicit_end_tag,
      sym_comment,
      anon_sym_LBRACE_AThtml,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT_SLASH,
      aux_sym__text_token1,
      anon_sym_LBRACE_RBRACE,
  [499] = 2,
    ACTIONS(133), 2,
      anon_sym_LT,
      anon_sym_LBRACE,
    ACTIONS(131), 9,
      sym__implicit_end_tag,
      sym_comment,
      anon_sym_LBRACE_AThtml,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT_SLASH,
      aux_sym__text_token1,
      anon_sym_LBRACE_RBRACE,
  [515] = 2,
    ACTIONS(137), 2,
      anon_sym_LT,
      anon_sym_LBRACE,
    ACTIONS(135), 9,
      sym__implicit_end_tag,
      sym_comment,
      anon_sym_LBRACE_AThtml,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT_SLASH,
      aux_sym__text_token1,
      anon_sym_LBRACE_RBRACE,
  [531] = 2,
    ACTIONS(141), 2,
      anon_sym_LT,
      anon_sym_LBRACE,
    ACTIONS(139), 9,
      sym__implicit_end_tag,
      sym_comment,
      anon_sym_LBRACE_AThtml,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT_SLASH,
      aux_sym__text_token1,
      anon_sym_LBRACE_RBRACE,
  [547] = 2,
    ACTIONS(145), 2,
      anon_sym_LT,
      anon_sym_LBRACE,
    ACTIONS(143), 9,
      sym__implicit_end_tag,
      sym_comment,
      anon_sym_LBRACE_AThtml,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT_SLASH,
      aux_sym__text_token1,
      anon_sym_LBRACE_RBRACE,
  [563] = 2,
    ACTIONS(149), 2,
      anon_sym_LT,
      anon_sym_LBRACE,
    ACTIONS(147), 9,
      sym__implicit_end_tag,
      sym_comment,
      anon_sym_LBRACE_AThtml,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT_SLASH,
      aux_sym__text_token1,
      anon_sym_LBRACE_RBRACE,
  [579] = 2,
    ACTIONS(153), 2,
      anon_sym_LT,
      anon_sym_LBRACE,
    ACTIONS(151), 9,
      sym__implicit_end_tag,
      sym_comment,
      anon_sym_LBRACE_AThtml,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT_SLASH,
      aux_sym__text_token1,
      anon_sym_LBRACE_RBRACE,
  [595] = 2,
    ACTIONS(157), 2,
      anon_sym_LT,
      anon_sym_LBRACE,
    ACTIONS(155), 9,
      sym__implicit_end_tag,
      sym_comment,
      anon_sym_LBRACE_AThtml,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT_SLASH,
      aux_sym__text_token1,
      anon_sym_LBRACE_RBRACE,
  [611] = 2,
    ACTIONS(161), 2,
      anon_sym_LT,
      anon_sym_LBRACE,
    ACTIONS(159), 9,
      sym__implicit_end_tag,
      sym_comment,
      anon_sym_LBRACE_AThtml,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT_SLASH,
      aux_sym__text_token1,
      anon_sym_LBRACE_RBRACE,
  [627] = 2,
    ACTIONS(165), 2,
      anon_sym_LT,
      anon_sym_LBRACE,
    ACTIONS(163), 9,
      sym__implicit_end_tag,
      sym_comment,
      anon_sym_LBRACE_AThtml,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT_SLASH,
      aux_sym__text_token1,
      anon_sym_LBRACE_RBRACE,
  [643] = 2,
    ACTIONS(169), 2,
      anon_sym_LT,
      anon_sym_LBRACE,
    ACTIONS(167), 9,
      sym__implicit_end_tag,
      sym_comment,
      anon_sym_LBRACE_AThtml,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT_SLASH,
      aux_sym__text_token1,
      anon_sym_LBRACE_RBRACE,
  [659] = 2,
    ACTIONS(173), 2,
      anon_sym_LT,
      anon_sym_LBRACE,
    ACTIONS(171), 9,
      sym__implicit_end_tag,
      sym_comment,
      anon_sym_LBRACE_AThtml,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT_SLASH,
      aux_sym__text_token1,
      anon_sym_LBRACE_RBRACE,
  [675] = 2,
    ACTIONS(177), 2,
      anon_sym_LT,
      anon_sym_LBRACE,
    ACTIONS(175), 9,
      sym__implicit_end_tag,
      sym_comment,
      anon_sym_LBRACE_AThtml,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT_SLASH,
      aux_sym__text_token1,
      anon_sym_LBRACE_RBRACE,
  [691] = 2,
    ACTIONS(181), 2,
      anon_sym_LT,
      anon_sym_LBRACE,
    ACTIONS(179), 9,
      sym__implicit_end_tag,
      sym_comment,
      anon_sym_LBRACE_AThtml,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT_SLASH,
      aux_sym__text_token1,
      anon_sym_LBRACE_RBRACE,
  [707] = 2,
    ACTIONS(185), 2,
      anon_sym_LT,
      anon_sym_LBRACE,
    ACTIONS(183), 9,
      sym__implicit_end_tag,
      sym_comment,
      anon_sym_LBRACE_AThtml,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT_SLASH,
      aux_sym__text_token1,
      anon_sym_LBRACE_RBRACE,
  [723] = 2,
    ACTIONS(189), 2,
      anon_sym_LT,
      anon_sym_LBRACE,
    ACTIONS(187), 9,
      sym__implicit_end_tag,
      sym_comment,
      anon_sym_LBRACE_AThtml,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT_SLASH,
      aux_sym__text_token1,
      anon_sym_LBRACE_RBRACE,
  [739] = 2,
    ACTIONS(185), 1,
      anon_sym_LBRACE,
    ACTIONS(183), 9,
      sym_comment,
      ts_builtin_sym_end,
      anon_sym_LBRACE_AThtml,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT,
      aux_sym__text_token1,
      anon_sym_LBRACE_RBRACE,
  [754] = 2,
    ACTIONS(161), 1,
      anon_sym_LBRACE,
    ACTIONS(159), 9,
      sym_comment,
      ts_builtin_sym_end,
      anon_sym_LBRACE_AThtml,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT,
      aux_sym__text_token1,
      anon_sym_LBRACE_RBRACE,
  [769] = 2,
    ACTIONS(173), 1,
      anon_sym_LBRACE,
    ACTIONS(171), 9,
      sym_comment,
      ts_builtin_sym_end,
      anon_sym_LBRACE_AThtml,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT,
      aux_sym__text_token1,
      anon_sym_LBRACE_RBRACE,
  [784] = 2,
    ACTIONS(153), 1,
      anon_sym_LBRACE,
    ACTIONS(151), 9,
      sym_comment,
      ts_builtin_sym_end,
      anon_sym_LBRACE_AThtml,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT,
      aux_sym__text_token1,
      anon_sym_LBRACE_RBRACE,
  [799] = 2,
    ACTIONS(169), 1,
      anon_sym_LBRACE,
    ACTIONS(167), 9,
      sym_comment,
      ts_builtin_sym_end,
      anon_sym_LBRACE_AThtml,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT,
      aux_sym__text_token1,
      anon_sym_LBRACE_RBRACE,
  [814] = 2,
    ACTIONS(149), 1,
      anon_sym_LBRACE,
    ACTIONS(147), 9,
      sym_comment,
      ts_builtin_sym_end,
      anon_sym_LBRACE_AThtml,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT,
      aux_sym__text_token1,
      anon_sym_LBRACE_RBRACE,
  [829] = 2,
    ACTIONS(141), 1,
      anon_sym_LBRACE,
    ACTIONS(139), 9,
      sym_comment,
      ts_builtin_sym_end,
      anon_sym_LBRACE_AThtml,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT,
      aux_sym__text_token1,
      anon_sym_LBRACE_RBRACE,
  [844] = 2,
    ACTIONS(165), 1,
      anon_sym_LBRACE,
    ACTIONS(163), 9,
      sym_comment,
      ts_builtin_sym_end,
      anon_sym_LBRACE_AThtml,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT,
      aux_sym__text_token1,
      anon_sym_LBRACE_RBRACE,
  [859] = 2,
    ACTIONS(137), 1,
      anon_sym_LBRACE,
    ACTIONS(135), 9,
      sym_comment,
      ts_builtin_sym_end,
      anon_sym_LBRACE_AThtml,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT,
      aux_sym__text_token1,
      anon_sym_LBRACE_RBRACE,
  [874] = 2,
    ACTIONS(133), 1,
      anon_sym_LBRACE,
    ACTIONS(131), 9,
      sym_comment,
      ts_builtin_sym_end,
      anon_sym_LBRACE_AThtml,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT,
      aux_sym__text_token1,
      anon_sym_LBRACE_RBRACE,
  [889] = 2,
    ACTIONS(129), 1,
      anon_sym_LBRACE,
    ACTIONS(127), 9,
      sym_comment,
      ts_builtin_sym_end,
      anon_sym_LBRACE_AThtml,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT,
      aux_sym__text_token1,
      anon_sym_LBRACE_RBRACE,
  [904] = 2,
    ACTIONS(157), 1,
      anon_sym_LBRACE,
    ACTIONS(155), 9,
      sym_comment,
      ts_builtin_sym_end,
      anon_sym_LBRACE_AThtml,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT,
      aux_sym__text_token1,
      anon_sym_LBRACE_RBRACE,
  [919] = 2,
    ACTIONS(145), 1,
      anon_sym_LBRACE,
    ACTIONS(143), 9,
      sym_comment,
      ts_builtin_sym_end,
      anon_sym_LBRACE_AThtml,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT,
      aux_sym__text_token1,
      anon_sym_LBRACE_RBRACE,
  [934] = 2,
    ACTIONS(181), 1,
      anon_sym_LBRACE,
    ACTIONS(179), 9,
      sym_comment,
      ts_builtin_sym_end,
      anon_sym_LBRACE_AThtml,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT,
      aux_sym__text_token1,
      anon_sym_LBRACE_RBRACE,
  [949] = 2,
    ACTIONS(109), 1,
      anon_sym_LBRACE,
    ACTIONS(107), 9,
      sym_comment,
      ts_builtin_sym_end,
      anon_sym_LBRACE_AThtml,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT,
      aux_sym__text_token1,
      anon_sym_LBRACE_RBRACE,
  [964] = 2,
    ACTIONS(113), 1,
      anon_sym_LBRACE,
    ACTIONS(111), 9,
      sym_comment,
      ts_builtin_sym_end,
      anon_sym_LBRACE_AThtml,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT,
      aux_sym__text_token1,
      anon_sym_LBRACE_RBRACE,
  [979] = 2,
    ACTIONS(117), 1,
      anon_sym_LBRACE,
    ACTIONS(115), 9,
      sym_comment,
      ts_builtin_sym_end,
      anon_sym_LBRACE_AThtml,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT,
      aux_sym__text_token1,
      anon_sym_LBRACE_RBRACE,
  [994] = 2,
    ACTIONS(121), 1,
      anon_sym_LBRACE,
    ACTIONS(119), 9,
      sym_comment,
      ts_builtin_sym_end,
      anon_sym_LBRACE_AThtml,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT,
      aux_sym__text_token1,
      anon_sym_LBRACE_RBRACE,
  [1009] = 2,
    ACTIONS(125), 1,
      anon_sym_LBRACE,
    ACTIONS(123), 9,
      sym_comment,
      ts_builtin_sym_end,
      anon_sym_LBRACE_AThtml,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_SLASH,
      anon_sym_LT,
      aux_sym__text_token1,
      anon_sym_LBRACE_RBRACE,
  [1024] = 8,
    ACTIONS(191), 1,
      anon_sym_GT,
    ACTIONS(193), 1,
      anon_sym_SLASH_GT,
    ACTIONS(195), 1,
      aux_sym_attribute_name_token1,
    ACTIONS(197), 1,
      anon_sym_LBRACE,
    ACTIONS(199), 1,
      anon_sym_LBRACE_RBRACE,
    STATE(63), 1,
      sym_attribute_name,
    STATE(65), 1,
      sym__expression,
    STATE(53), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1050] = 8,
    ACTIONS(195), 1,
      aux_sym_attribute_name_token1,
    ACTIONS(197), 1,
      anon_sym_LBRACE,
    ACTIONS(199), 1,
      anon_sym_LBRACE_RBRACE,
    ACTIONS(201), 1,
      anon_sym_GT,
    ACTIONS(203), 1,
      anon_sym_SLASH_GT,
    STATE(63), 1,
      sym_attribute_name,
    STATE(65), 1,
      sym__expression,
    STATE(49), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1076] = 8,
    ACTIONS(191), 1,
      anon_sym_GT,
    ACTIONS(195), 1,
      aux_sym_attribute_name_token1,
    ACTIONS(197), 1,
      anon_sym_LBRACE,
    ACTIONS(199), 1,
      anon_sym_LBRACE_RBRACE,
    ACTIONS(205), 1,
      anon_sym_SLASH_GT,
    STATE(63), 1,
      sym_attribute_name,
    STATE(65), 1,
      sym__expression,
    STATE(53), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1102] = 7,
    ACTIONS(197), 1,
      anon_sym_LBRACE,
    ACTIONS(199), 1,
      anon_sym_LBRACE_RBRACE,
    ACTIONS(207), 1,
      aux_sym_attribute_name_token1,
    ACTIONS(209), 1,
      anon_sym_SQUOTE,
    ACTIONS(211), 1,
      anon_sym_DQUOTE,
    STATE(66), 1,
      sym__expression,
    STATE(69), 3,
      sym_attribute_value,
      sym_expr_attribute_value,
      sym_quoted_attribute_value,
  [1126] = 7,
    ACTIONS(215), 1,
      aux_sym_attribute_name_token1,
    ACTIONS(218), 1,
      anon_sym_LBRACE,
    ACTIONS(221), 1,
      anon_sym_LBRACE_RBRACE,
    STATE(63), 1,
      sym_attribute_name,
    STATE(65), 1,
      sym__expression,
    ACTIONS(213), 2,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    STATE(53), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1150] = 8,
    ACTIONS(195), 1,
      aux_sym_attribute_name_token1,
    ACTIONS(197), 1,
      anon_sym_LBRACE,
    ACTIONS(199), 1,
      anon_sym_LBRACE_RBRACE,
    ACTIONS(201), 1,
      anon_sym_GT,
    ACTIONS(224), 1,
      anon_sym_SLASH_GT,
    STATE(63), 1,
      sym_attribute_name,
    STATE(65), 1,
      sym__expression,
    STATE(51), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1176] = 7,
    ACTIONS(226), 1,
      aux_sym_attribute_name_token1,
    ACTIONS(228), 1,
      anon_sym_SQUOTE,
    ACTIONS(230), 1,
      anon_sym_DQUOTE,
    ACTIONS(232), 1,
      anon_sym_LBRACE,
    ACTIONS(234), 1,
      anon_sym_LBRACE_RBRACE,
    STATE(76), 1,
      sym__expression,
    STATE(84), 3,
      sym_attribute_value,
      sym_expr_attribute_value,
      sym_quoted_attribute_value,
  [1200] = 7,
    ACTIONS(232), 1,
      anon_sym_LBRACE,
    ACTIONS(234), 1,
      anon_sym_LBRACE_RBRACE,
    ACTIONS(236), 1,
      anon_sym_GT,
    ACTIONS(238), 1,
      aux_sym_attribute_name_token1,
    STATE(68), 1,
      sym_attribute_name,
    STATE(85), 1,
      sym__expression,
    STATE(60), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1223] = 7,
    ACTIONS(232), 1,
      anon_sym_LBRACE,
    ACTIONS(234), 1,
      anon_sym_LBRACE_RBRACE,
    ACTIONS(238), 1,
      aux_sym_attribute_name_token1,
    ACTIONS(240), 1,
      anon_sym_GT,
    STATE(68), 1,
      sym_attribute_name,
    STATE(85), 1,
      sym__expression,
    STATE(59), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1246] = 7,
    ACTIONS(232), 1,
      anon_sym_LBRACE,
    ACTIONS(234), 1,
      anon_sym_LBRACE_RBRACE,
    ACTIONS(238), 1,
      aux_sym_attribute_name_token1,
    ACTIONS(242), 1,
      anon_sym_GT,
    STATE(68), 1,
      sym_attribute_name,
    STATE(85), 1,
      sym__expression,
    STATE(56), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1269] = 7,
    ACTIONS(232), 1,
      anon_sym_LBRACE,
    ACTIONS(234), 1,
      anon_sym_LBRACE_RBRACE,
    ACTIONS(238), 1,
      aux_sym_attribute_name_token1,
    ACTIONS(244), 1,
      anon_sym_GT,
    STATE(68), 1,
      sym_attribute_name,
    STATE(85), 1,
      sym__expression,
    STATE(60), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1292] = 7,
    ACTIONS(213), 1,
      anon_sym_GT,
    ACTIONS(246), 1,
      aux_sym_attribute_name_token1,
    ACTIONS(249), 1,
      anon_sym_LBRACE,
    ACTIONS(252), 1,
      anon_sym_LBRACE_RBRACE,
    STATE(68), 1,
      sym_attribute_name,
    STATE(85), 1,
      sym__expression,
    STATE(60), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1315] = 3,
    ACTIONS(257), 1,
      anon_sym_else,
    STATE(105), 1,
      sym__special_block_intermediate_tag,
    ACTIONS(255), 4,
      anon_sym_elseif,
      anon_sym_elseif2,
      anon_sym_then,
      anon_sym_catch,
  [1328] = 3,
    ACTIONS(261), 1,
      anon_sym_else,
    STATE(111), 1,
      sym__special_block_intermediate_tag,
    ACTIONS(259), 4,
      anon_sym_elseif,
      anon_sym_elseif2,
      anon_sym_then,
      anon_sym_catch,
  [1341] = 3,
    ACTIONS(265), 1,
      anon_sym_EQ,
    ACTIONS(267), 1,
      anon_sym_LBRACE,
    ACTIONS(263), 4,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      aux_sym_attribute_name_token1,
      anon_sym_LBRACE_RBRACE,
  [1354] = 2,
    ACTIONS(271), 1,
      anon_sym_LBRACE,
    ACTIONS(269), 5,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      anon_sym_EQ,
      aux_sym_attribute_name_token1,
      anon_sym_LBRACE_RBRACE,
  [1365] = 2,
    ACTIONS(275), 1,
      anon_sym_LBRACE,
    ACTIONS(273), 4,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      aux_sym_attribute_name_token1,
      anon_sym_LBRACE_RBRACE,
  [1375] = 2,
    ACTIONS(279), 1,
      anon_sym_LBRACE,
    ACTIONS(277), 4,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      aux_sym_attribute_name_token1,
      anon_sym_LBRACE_RBRACE,
  [1385] = 2,
    ACTIONS(283), 1,
      anon_sym_LBRACE,
    ACTIONS(281), 4,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      aux_sym_attribute_name_token1,
      anon_sym_LBRACE_RBRACE,
  [1395] = 3,
    ACTIONS(267), 1,
      anon_sym_LBRACE,
    ACTIONS(285), 1,
      anon_sym_EQ,
    ACTIONS(263), 3,
      anon_sym_GT,
      aux_sym_attribute_name_token1,
      anon_sym_LBRACE_RBRACE,
  [1407] = 2,
    ACTIONS(289), 1,
      anon_sym_LBRACE,
    ACTIONS(287), 4,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      aux_sym_attribute_name_token1,
      anon_sym_LBRACE_RBRACE,
  [1417] = 2,
    ACTIONS(293), 1,
      anon_sym_LBRACE,
    ACTIONS(291), 4,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      aux_sym_attribute_name_token1,
      anon_sym_LBRACE_RBRACE,
  [1427] = 2,
    ACTIONS(271), 1,
      anon_sym_LBRACE,
    ACTIONS(269), 4,
      anon_sym_GT,
      anon_sym_EQ,
      aux_sym_attribute_name_token1,
      anon_sym_LBRACE_RBRACE,
  [1437] = 2,
    ACTIONS(125), 1,
      anon_sym_LBRACE,
    ACTIONS(123), 4,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      aux_sym_attribute_name_token1,
      anon_sym_LBRACE_RBRACE,
  [1447] = 2,
    ACTIONS(297), 1,
      anon_sym_LBRACE,
    ACTIONS(295), 4,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      aux_sym_attribute_name_token1,
      anon_sym_LBRACE_RBRACE,
  [1457] = 2,
    ACTIONS(173), 1,
      anon_sym_LBRACE,
    ACTIONS(171), 4,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      aux_sym_attribute_name_token1,
      anon_sym_LBRACE_RBRACE,
  [1467] = 2,
    ACTIONS(161), 1,
      anon_sym_LBRACE,
    ACTIONS(159), 4,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      aux_sym_attribute_name_token1,
      anon_sym_LBRACE_RBRACE,
  [1477] = 2,
    ACTIONS(279), 1,
      anon_sym_LBRACE,
    ACTIONS(277), 3,
      anon_sym_GT,
      aux_sym_attribute_name_token1,
      anon_sym_LBRACE_RBRACE,
  [1486] = 2,
    ACTIONS(161), 1,
      anon_sym_LBRACE,
    ACTIONS(159), 3,
      anon_sym_GT,
      aux_sym_attribute_name_token1,
      anon_sym_LBRACE_RBRACE,
  [1495] = 2,
    STATE(134), 1,
      sym__special_block_start_tag,
    ACTIONS(299), 3,
      anon_sym_if,
      anon_sym_each,
      anon_sym_await,
  [1504] = 2,
    ACTIONS(125), 1,
      anon_sym_LBRACE,
    ACTIONS(123), 3,
      anon_sym_GT,
      aux_sym_attribute_name_token1,
      anon_sym_LBRACE_RBRACE,
  [1513] = 2,
    STATE(116), 1,
      sym__special_block_end_tag,
    ACTIONS(301), 3,
      anon_sym_if,
      anon_sym_each,
      anon_sym_await,
  [1522] = 2,
    ACTIONS(173), 1,
      anon_sym_LBRACE,
    ACTIONS(171), 3,
      anon_sym_GT,
      aux_sym_attribute_name_token1,
      anon_sym_LBRACE_RBRACE,
  [1531] = 2,
    ACTIONS(293), 1,
      anon_sym_LBRACE,
    ACTIONS(291), 3,
      anon_sym_GT,
      aux_sym_attribute_name_token1,
      anon_sym_LBRACE_RBRACE,
  [1540] = 2,
    ACTIONS(283), 1,
      anon_sym_LBRACE,
    ACTIONS(281), 3,
      anon_sym_GT,
      aux_sym_attribute_name_token1,
      anon_sym_LBRACE_RBRACE,
  [1549] = 2,
    ACTIONS(289), 1,
      anon_sym_LBRACE,
    ACTIONS(287), 3,
      anon_sym_GT,
      aux_sym_attribute_name_token1,
      anon_sym_LBRACE_RBRACE,
  [1558] = 2,
    ACTIONS(275), 1,
      anon_sym_LBRACE,
    ACTIONS(273), 3,
      anon_sym_GT,
      aux_sym_attribute_name_token1,
      anon_sym_LBRACE_RBRACE,
  [1567] = 2,
    ACTIONS(297), 1,
      anon_sym_LBRACE,
    ACTIONS(295), 3,
      anon_sym_GT,
      aux_sym_attribute_name_token1,
      anon_sym_LBRACE_RBRACE,
  [1576] = 2,
    STATE(133), 1,
      sym__special_block_end_tag,
    ACTIONS(303), 3,
      anon_sym_if,
      anon_sym_each,
      anon_sym_await,
  [1585] = 2,
    STATE(135), 1,
      sym__special_block_start_tag,
    ACTIONS(305), 3,
      anon_sym_if,
      anon_sym_each,
      anon_sym_await,
  [1594] = 3,
    ACTIONS(45), 1,
      anon_sym_LT_SLASH,
    ACTIONS(307), 1,
      sym_raw_text,
    STATE(35), 1,
      sym_end_tag,
  [1604] = 3,
    ACTIONS(31), 1,
      anon_sym_LT_SLASH,
    ACTIONS(309), 1,
      sym_raw_text,
    STATE(19), 1,
      sym_end_tag,
  [1614] = 3,
    ACTIONS(31), 1,
      anon_sym_LT_SLASH,
    ACTIONS(311), 1,
      sym_raw_text,
    STATE(20), 1,
      sym_end_tag,
  [1624] = 3,
    ACTIONS(313), 1,
      sym__start_tag_name,
    ACTIONS(315), 1,
      sym__script_start_tag_name,
    ACTIONS(317), 1,
      sym__style_start_tag_name,
  [1634] = 3,
    ACTIONS(315), 1,
      sym__script_start_tag_name,
    ACTIONS(317), 1,
      sym__style_start_tag_name,
    ACTIONS(319), 1,
      sym__start_tag_name,
  [1644] = 3,
    ACTIONS(45), 1,
      anon_sym_LT_SLASH,
    ACTIONS(321), 1,
      sym_raw_text,
    STATE(33), 1,
      sym_end_tag,
  [1654] = 1,
    ACTIONS(323), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1659] = 2,
    ACTIONS(325), 1,
      anon_sym_DQUOTE,
    ACTIONS(327), 1,
      aux_sym_quoted_attribute_value_token2,
  [1666] = 2,
    ACTIONS(329), 1,
      anon_sym_RBRACE,
    ACTIONS(331), 1,
      sym_raw_text_expr,
  [1673] = 2,
    ACTIONS(325), 1,
      anon_sym_SQUOTE,
    ACTIONS(333), 1,
      aux_sym_quoted_attribute_value_token1,
  [1680] = 2,
    ACTIONS(335), 1,
      anon_sym_SQUOTE,
    ACTIONS(337), 1,
      aux_sym_quoted_attribute_value_token1,
  [1687] = 1,
    ACTIONS(339), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1692] = 2,
    ACTIONS(45), 1,
      anon_sym_LT_SLASH,
    STATE(45), 1,
      sym_end_tag,
  [1699] = 2,
    ACTIONS(31), 1,
      anon_sym_LT_SLASH,
    STATE(10), 1,
      sym_end_tag,
  [1706] = 2,
    ACTIONS(335), 1,
      anon_sym_DQUOTE,
    ACTIONS(341), 1,
      aux_sym_quoted_attribute_value_token2,
  [1713] = 2,
    ACTIONS(343), 1,
      anon_sym_RBRACE,
    ACTIONS(345), 1,
      sym_raw_text_expr,
  [1720] = 2,
    ACTIONS(347), 1,
      anon_sym_RBRACE,
    ACTIONS(349), 1,
      sym_raw_text_expr,
  [1727] = 2,
    ACTIONS(351), 1,
      anon_sym_RBRACE,
    ACTIONS(353), 1,
      sym_raw_text_expr,
  [1734] = 2,
    ACTIONS(355), 1,
      anon_sym_RBRACE,
    ACTIONS(357), 1,
      sym_raw_text_expr,
  [1741] = 1,
    ACTIONS(359), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1746] = 2,
    ACTIONS(45), 1,
      anon_sym_LT_SLASH,
    STATE(46), 1,
      sym_end_tag,
  [1753] = 2,
    ACTIONS(361), 1,
      anon_sym_RBRACE,
    ACTIONS(363), 1,
      sym_raw_text_expr,
  [1760] = 2,
    ACTIONS(365), 1,
      anon_sym_RBRACE,
    ACTIONS(367), 1,
      sym_raw_text_expr,
  [1767] = 1,
    ACTIONS(369), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1772] = 2,
    ACTIONS(371), 1,
      anon_sym_RBRACE,
    ACTIONS(373), 1,
      sym_raw_text_expr,
  [1779] = 2,
    ACTIONS(31), 1,
      anon_sym_LT_SLASH,
    STATE(11), 1,
      sym_end_tag,
  [1786] = 1,
    ACTIONS(375), 1,
      anon_sym_RBRACE,
  [1790] = 1,
    ACTIONS(377), 1,
      anon_sym_RBRACE,
  [1794] = 1,
    ACTIONS(379), 1,
      anon_sym_RBRACE,
  [1798] = 1,
    ACTIONS(381), 1,
      anon_sym_RBRACE,
  [1802] = 1,
    ACTIONS(383), 1,
      anon_sym_RBRACE,
  [1806] = 1,
    ACTIONS(385), 1,
      anon_sym_RBRACE,
  [1810] = 1,
    ACTIONS(387), 1,
      ts_builtin_sym_end,
  [1814] = 1,
    ACTIONS(389), 1,
      anon_sym_GT,
  [1818] = 1,
    ACTIONS(391), 1,
      anon_sym_DQUOTE,
  [1822] = 1,
    ACTIONS(391), 1,
      anon_sym_SQUOTE,
  [1826] = 1,
    ACTIONS(393), 1,
      anon_sym_GT,
  [1830] = 1,
    ACTIONS(395), 1,
      anon_sym_SQUOTE,
  [1834] = 1,
    ACTIONS(395), 1,
      anon_sym_DQUOTE,
  [1838] = 1,
    ACTIONS(397), 1,
      anon_sym_RBRACE,
  [1842] = 1,
    ACTIONS(399), 1,
      anon_sym_RBRACE,
  [1846] = 1,
    ACTIONS(401), 1,
      sym__end_tag_name,
  [1850] = 1,
    ACTIONS(403), 1,
      anon_sym_RBRACE,
  [1854] = 1,
    ACTIONS(405), 1,
      anon_sym_RBRACE,
  [1858] = 1,
    ACTIONS(407), 1,
      anon_sym_RBRACE,
  [1862] = 1,
    ACTIONS(409), 1,
      sym_raw_text_expr,
  [1866] = 1,
    ACTIONS(411), 1,
      sym_raw_text_expr,
  [1870] = 1,
    ACTIONS(413), 1,
      sym__end_tag_name,
  [1874] = 1,
    ACTIONS(415), 1,
      anon_sym_RBRACE,
};

static uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 60,
  [SMALL_STATE(4)] = 120,
  [SMALL_STATE(5)] = 180,
  [SMALL_STATE(6)] = 240,
  [SMALL_STATE(7)] = 295,
  [SMALL_STATE(8)] = 349,
  [SMALL_STATE(9)] = 403,
  [SMALL_STATE(10)] = 419,
  [SMALL_STATE(11)] = 435,
  [SMALL_STATE(12)] = 451,
  [SMALL_STATE(13)] = 467,
  [SMALL_STATE(14)] = 483,
  [SMALL_STATE(15)] = 499,
  [SMALL_STATE(16)] = 515,
  [SMALL_STATE(17)] = 531,
  [SMALL_STATE(18)] = 547,
  [SMALL_STATE(19)] = 563,
  [SMALL_STATE(20)] = 579,
  [SMALL_STATE(21)] = 595,
  [SMALL_STATE(22)] = 611,
  [SMALL_STATE(23)] = 627,
  [SMALL_STATE(24)] = 643,
  [SMALL_STATE(25)] = 659,
  [SMALL_STATE(26)] = 675,
  [SMALL_STATE(27)] = 691,
  [SMALL_STATE(28)] = 707,
  [SMALL_STATE(29)] = 723,
  [SMALL_STATE(30)] = 739,
  [SMALL_STATE(31)] = 754,
  [SMALL_STATE(32)] = 769,
  [SMALL_STATE(33)] = 784,
  [SMALL_STATE(34)] = 799,
  [SMALL_STATE(35)] = 814,
  [SMALL_STATE(36)] = 829,
  [SMALL_STATE(37)] = 844,
  [SMALL_STATE(38)] = 859,
  [SMALL_STATE(39)] = 874,
  [SMALL_STATE(40)] = 889,
  [SMALL_STATE(41)] = 904,
  [SMALL_STATE(42)] = 919,
  [SMALL_STATE(43)] = 934,
  [SMALL_STATE(44)] = 949,
  [SMALL_STATE(45)] = 964,
  [SMALL_STATE(46)] = 979,
  [SMALL_STATE(47)] = 994,
  [SMALL_STATE(48)] = 1009,
  [SMALL_STATE(49)] = 1024,
  [SMALL_STATE(50)] = 1050,
  [SMALL_STATE(51)] = 1076,
  [SMALL_STATE(52)] = 1102,
  [SMALL_STATE(53)] = 1126,
  [SMALL_STATE(54)] = 1150,
  [SMALL_STATE(55)] = 1176,
  [SMALL_STATE(56)] = 1200,
  [SMALL_STATE(57)] = 1223,
  [SMALL_STATE(58)] = 1246,
  [SMALL_STATE(59)] = 1269,
  [SMALL_STATE(60)] = 1292,
  [SMALL_STATE(61)] = 1315,
  [SMALL_STATE(62)] = 1328,
  [SMALL_STATE(63)] = 1341,
  [SMALL_STATE(64)] = 1354,
  [SMALL_STATE(65)] = 1365,
  [SMALL_STATE(66)] = 1375,
  [SMALL_STATE(67)] = 1385,
  [SMALL_STATE(68)] = 1395,
  [SMALL_STATE(69)] = 1407,
  [SMALL_STATE(70)] = 1417,
  [SMALL_STATE(71)] = 1427,
  [SMALL_STATE(72)] = 1437,
  [SMALL_STATE(73)] = 1447,
  [SMALL_STATE(74)] = 1457,
  [SMALL_STATE(75)] = 1467,
  [SMALL_STATE(76)] = 1477,
  [SMALL_STATE(77)] = 1486,
  [SMALL_STATE(78)] = 1495,
  [SMALL_STATE(79)] = 1504,
  [SMALL_STATE(80)] = 1513,
  [SMALL_STATE(81)] = 1522,
  [SMALL_STATE(82)] = 1531,
  [SMALL_STATE(83)] = 1540,
  [SMALL_STATE(84)] = 1549,
  [SMALL_STATE(85)] = 1558,
  [SMALL_STATE(86)] = 1567,
  [SMALL_STATE(87)] = 1576,
  [SMALL_STATE(88)] = 1585,
  [SMALL_STATE(89)] = 1594,
  [SMALL_STATE(90)] = 1604,
  [SMALL_STATE(91)] = 1614,
  [SMALL_STATE(92)] = 1624,
  [SMALL_STATE(93)] = 1634,
  [SMALL_STATE(94)] = 1644,
  [SMALL_STATE(95)] = 1654,
  [SMALL_STATE(96)] = 1659,
  [SMALL_STATE(97)] = 1666,
  [SMALL_STATE(98)] = 1673,
  [SMALL_STATE(99)] = 1680,
  [SMALL_STATE(100)] = 1687,
  [SMALL_STATE(101)] = 1692,
  [SMALL_STATE(102)] = 1699,
  [SMALL_STATE(103)] = 1706,
  [SMALL_STATE(104)] = 1713,
  [SMALL_STATE(105)] = 1720,
  [SMALL_STATE(106)] = 1727,
  [SMALL_STATE(107)] = 1734,
  [SMALL_STATE(108)] = 1741,
  [SMALL_STATE(109)] = 1746,
  [SMALL_STATE(110)] = 1753,
  [SMALL_STATE(111)] = 1760,
  [SMALL_STATE(112)] = 1767,
  [SMALL_STATE(113)] = 1772,
  [SMALL_STATE(114)] = 1779,
  [SMALL_STATE(115)] = 1786,
  [SMALL_STATE(116)] = 1790,
  [SMALL_STATE(117)] = 1794,
  [SMALL_STATE(118)] = 1798,
  [SMALL_STATE(119)] = 1802,
  [SMALL_STATE(120)] = 1806,
  [SMALL_STATE(121)] = 1810,
  [SMALL_STATE(122)] = 1814,
  [SMALL_STATE(123)] = 1818,
  [SMALL_STATE(124)] = 1822,
  [SMALL_STATE(125)] = 1826,
  [SMALL_STATE(126)] = 1830,
  [SMALL_STATE(127)] = 1834,
  [SMALL_STATE(128)] = 1838,
  [SMALL_STATE(129)] = 1842,
  [SMALL_STATE(130)] = 1846,
  [SMALL_STATE(131)] = 1850,
  [SMALL_STATE(132)] = 1854,
  [SMALL_STATE(133)] = 1858,
  [SMALL_STATE(134)] = 1862,
  [SMALL_STATE(135)] = 1866,
  [SMALL_STATE(136)] = 1870,
  [SMALL_STATE(137)] = 1874,
};

static TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(110),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(93),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(136),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(107),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(130),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(106),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(88),
  [59] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(62),
  [62] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(80),
  [65] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(93),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2),
  [70] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(6),
  [73] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(107),
  [76] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(25),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [83] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(97),
  [86] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(78),
  [89] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(61),
  [92] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(87),
  [95] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(92),
  [98] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(8),
  [101] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(110),
  [104] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(32),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_special_block_start, 4),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_special_block_start, 4),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_element, 3),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_element, 3),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_element, 3),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_element, 3),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 3),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 3),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 3),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 3),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag, 3),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag, 3),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_special_block_end, 3),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_special_block_end, 3),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_special_block_intermediate, 3),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_special_block_intermediate, 3),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_html_block, 3),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_html_block, 3),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_tag, 3),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_end_tag, 3),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_element, 2),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_element, 2),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_element, 2),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_element, 2),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 2),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 2),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 2),
  [161] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 2),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_html_block, 2),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_html_block, 2),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 1),
  [169] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 1),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1),
  [173] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 1),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 4),
  [177] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 4),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_special_block_intermediate, 4),
  [181] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_special_block_intermediate, 4),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag, 4),
  [185] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag, 4),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 3),
  [189] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 3),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [197] = {.entry = {.count = 1, .reusable = false}}, SHIFT(104),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2),
  [215] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2), SHIFT_REPEAT(64),
  [218] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_start_tag_repeat1, 2), SHIFT_REPEAT(104),
  [221] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2), SHIFT_REPEAT(74),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [232] = {.entry = {.count = 1, .reusable = false}}, SHIFT(113),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [246] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2), SHIFT_REPEAT(71),
  [249] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_start_tag_repeat1, 2), SHIFT_REPEAT(113),
  [252] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2), SHIFT_REPEAT(81),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [257] = {.entry = {.count = 1, .reusable = false}}, SHIFT(105),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [261] = {.entry = {.count = 1, .reusable = false}}, SHIFT(111),
  [263] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 1),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [267] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute, 1),
  [269] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_name, 1),
  [271] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute_name, 1),
  [273] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 1, .production_id = 1),
  [275] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute, 1, .production_id = 1),
  [277] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr_attribute_value, 1),
  [279] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expr_attribute_value, 1),
  [281] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 2),
  [283] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted_attribute_value, 2),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [287] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3),
  [289] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute, 3),
  [291] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 3),
  [293] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted_attribute_value, 3),
  [295] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_value, 1),
  [297] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute_value, 1),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(134),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(133),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(135),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [323] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_start_tag, 4),
  [325] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(137),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [335] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [339] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_start_tag, 4),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [343] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [345] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [347] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [349] = {.entry = {.count = 1, .reusable = true}}, SHIFT(128),
  [351] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [353] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [355] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [357] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [359] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_start_tag, 3),
  [361] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [363] = {.entry = {.count = 1, .reusable = true}}, SHIFT(132),
  [365] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [367] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [369] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_start_tag, 3),
  [371] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [373] = {.entry = {.count = 1, .reusable = true}}, SHIFT(131),
  [375] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [377] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [379] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [381] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [383] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [385] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [387] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [389] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [391] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [393] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [395] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [397] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [399] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [401] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [403] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [405] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [407] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [409] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [411] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [413] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [415] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_svelte_external_scanner_create(void);
void tree_sitter_svelte_external_scanner_destroy(void *);
bool tree_sitter_svelte_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_svelte_external_scanner_serialize(void *, char *);
void tree_sitter_svelte_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_svelte(void) {
  static TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .parse_table = (const uint16_t *)ts_parse_table,
    .parse_actions = ts_parse_actions,
    .lex_modes = ts_lex_modes,
    .alias_sequences = (const TSSymbol *)ts_alias_sequences,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .lex_fn = ts_lex,
    .external_scanner = {
      (const bool *)ts_external_scanner_states,
      ts_external_scanner_symbol_map,
      tree_sitter_svelte_external_scanner_create,
      tree_sitter_svelte_external_scanner_destroy,
      tree_sitter_svelte_external_scanner_scan,
      tree_sitter_svelte_external_scanner_serialize,
      tree_sitter_svelte_external_scanner_deserialize,
    },
    .field_count = FIELD_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .small_parse_table = (const uint16_t *)ts_small_parse_table,
    .small_parse_table_map = (const uint32_t *)ts_small_parse_table_map,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .state_count = STATE_COUNT,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
